CocoaPods/CocoaPods

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/2579. 
I also changed the validator to correctly report warnings from xcodebuild as warnings rather than notes
> [Validator] Fix detection of errors in xcodebuild

- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
* What did you do?
`pod search sort --full keyword`
* What did you expect to happen?
A sorted search of all the pods using their full text
* What happened instead?
A big crash, with this stack trace. Locally, adding this one line solved the problem completely.
```
CocoaPods : 0.35.0
Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
RubyGems : 2.2.2
Host : Mac OS X 10.10.1 (14B25)
Xcode : 6.1.1 (6A2008a)
Git : git version 2.2.1
Ruby lib dir : /Users/timshadel/.rbenv/versions/2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d4c063d7e2712deead4993a44c4ae06bc47e229d
shadelsoftware - https://github.com/ShadelSoftware/CocoaPodSpecs.git @ 329894a10dc6722d9ca90f2bf87db69a900681ac
```
```
cocoapods-plugins       : 0.3.2
cocoapods-sorted-search : 0.2.3 …
```
> Fix uninitialized constant Class::YAML crash

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
Along with fixing #2946, I think it makes more sense if by default. That only the master spec repository is used. If a user wants a custom repository they should have to explicitly specified this in their Podfile.
This change means that a Podfile on one system will have the exact same dependencies on another. Currently you could consume another Podfile and have different dependencies since by default, the Podfile would pick up all sources which might change the dependencies.
> [Podfile] Change the default spec repository to the master

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
Updated Analyzer::update_repositories_if_needed to only update a spec repository if it is a git sourced repository.
This is a proposed fix for #2558
/cc: @neonichu @kylef
> [Analyzer] Only update git sourced spec repos

- CHANGELOG.md
- lib/cocoapods/external_sources/podspec_source.rb
- spec/unit/external_sources/podspec_source_spec.rb
This fixes an issue @tgoyne has been having.
@kylef, a quick merge of this would be much appreciated. The failures are in the integration spec, and are expected.
> [PodspecSource] Evaluate :podspec dependencies in their own directory if the path is local.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/installer_spec.rb
Set the APPLICATION_EXTENSION_API_ONLY build setting if integrating with an app extension target.
This gets rid of warnings inside Xcode and also better ensures that one only uses Pods which are safe for App Store approval in app extension targets.
Closes #2980
> Configure as extension only for app extensions

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
No code signing identity needed anymore :key: 
Fixes CocoaPods/swift#13
> Build for iOS simulator only during validation

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
Explicitly specifying `--color=never` to avoid ASCII color codes getting into the file path:
> No colors when grepping.

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Have to use dynamic frameworks for Swift and they are unsupported on iOS 7.
Fixes #2963
> [Frameworks] Fail lint for Swift on iOS < 8.

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
This should ensure that they're not recopied if unchanged, because the
destination will be newer if they changed due to code-signing.
Supersedes #3149
> Copy Swift libraries using `rsync -u`

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/target.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
- spec/unit/installer_spec.rb
- spec/unit/target/aggregate_target_spec.rb
- spec/unit/target/pod_target_spec.rb
- spec/unit/validator_spec.rb
Looks like this right now:
```
Analyzing dependencies
Downloading dependencies
Using Alamofire (1.1.4)
[!] Pods written in Swift can only be integrated as frameworks; this feature is still 
in beta. Add `use_frameworks!` to your Podfile or target to opt in to using it.
```
> Require explicit use of `use_frameworks!`

- lib/cocoapods/command/repo/push.rb
- spec/functional/command/repo/push_spec.rb
See #3168, IMHO shouldn't get a dedicated changelog entry as it should've been included in that change.
> Add `--use-libraries` option for `pod repo push`

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
We don't need to add $PODS_FRAMEWORK_BUILD_PATH, if there is no pod target, which should be build.
Fixes #3213.
> Set FRAMEWORK_SEARCH_PATHS only when needed

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
This limits our check for static transitive dependencies to those which are known to not work.
Reasoning:
- `should_build? == false` means the static library or framework will be linked directly to the user target
- Linking a pod target which depends transitively on the same static library or framework will fail because of missing symbols
- Linking both targets against the static library or framework will likely result in duplicated symbols
=> this kind of dependency cannot be fulfilled if the integration is done via frameworks.
This fixes #3194
> Fix static binaries check

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
Before all xcassets used in pod sources where unconditionally integrated into the bundle's car file, even if the xcasset file wasn't referenced by the podspec. Now only files, which are explicitly specified in the spec, will be integrated.
See CocoaPods/swift#11.
> Only copy the required xcasset files into the user bundle

- lib/cocoapods/generator/copy_resources_script.rb
Wrong `xcassets` path in generated `Pods-resources.sh` file. This bug can be reproduced by adding [1PasswordExtension spec](https://github.com/CocoaPods/Specs/blob/master/Specs/1PasswordExtension/1.1.2/1PasswordExtension.podspec.json) to demo app.
> [Generator] use absolute xcasset file path in copy resource script

- lib/cocoapods/generator/copy_resources_script.rb
If there are any pods being used containing `.xcassets` (for example, [1PasswordExtension](https://github.com/AgileBits/onepassword-app-extension)), while the main project also has a `.xcassets`, the one from the main project will be unexpectedly discarded.
> [CopyResourcesScript] Do not discard `.xcassets` from the main project if there are any pods containing `.xcassets`.

- spec/integration.rb
This adds two specs, which were accidentally never executed to integration.rb.
* install_custom_module_name
* install_non_objective_c_files
Furthermore this removes one spec from the submodule, as discussed in #3355.
> [IntegrationSpec] Add missing specs to integration.rb

- CHANGELOG.md
- lib/cocoapods/command/repo.rb
- lib/cocoapods/command/repo/list.rb
- spec/functional/command/repo/list_spec.rb
I noticed a couple of bugs / nonsensical things with `pod repo list`. Here’s a pull request making this sane.
This pull request addresses does following:
- Use `source.url` instead of determining the git remote manually
- Show the branch instead of remote for git repositories, it makes no sense to show the remote since 1) it can only ever be origin according to `source.url` an 2) we’re printing the value of the remote anyway
- Always show the URI for local repositories (so people know what they can put in `source ‘’` in a Podfile
Before
```
b
- Type: git ()
- URL:
- Path: /Users/kyle/.cocoapods/repos/b
```
After
```
b
- Type: git (master)
- URL:  file:///Users/kyle/.cocoapods/repos/b/.git
- Path: /Users/kyle/.cocoapods/repos/b
- Add tests around existing behaviour and the changes.
```
It …
> [pod repo list] Fix issue showing the URL for git

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
Allow support for pods with xcasset bundles using `:path`.
Closes #1549
Closes #3384
Closes #3358
> [Copy Resources] Resolve various problems with xcasset bundles

- lib/cocoapods/command/lib.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
That's helpful for i.e. multi-platforms specs and/or specs with subspecs, especially in combination with `--no-clean`.
> [Linter] Allow to fail-fast

- CHANGELOG.md
- lib/cocoapods/generator/module_map.rb
- lib/cocoapods/installer/target_installer.rb
- lib/cocoapods/installer/target_installer/pod_target_installer.rb
- spec/unit/generator/module_map_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/2974.
\c @mrackwitz @kylef
> Ensure private headers are declared as such in a framework's generated module map.

- CHANGELOG.md
- lib/cocoapods/installer/pod_source_installer.rb
- spec/unit/installer/pod_source_installer_spec.rb
🌈
Seems like this should probably be the default behavior, instead of a plugin. When this gets released, I'll deprecate the plugin and put up a note saying that it's now built in.
> Automatically lock Pod source files after installing (#1154)

- CHANGELOG.md
- Gemfile.lock
- cocoapods.gemspec
- lib/cocoapods/executable.rb
- spec/unit/executable_spec.rb
Potentially closes #3101.
It also gets rid of the `open4` dependency entirely, and isn't that many lines of code more.
\c @alloy @kylef
> [Executable] Use popen3 instead of open4 to execute commands

- CHANGELOG.md
- lib/cocoapods/config.rb
- spec/unit/sources_manager_spec.rb
This adds `COCOAPODS_SKIP_NEW_VERSION` env var to skip the new version message, as mentioned in #3364
> [Config] Add environment variable COCOAPODS_SKIP_NEW_VERSION

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/pod_target_spec.rb
This allows "fake" frameworks and static libraries to be linked directly against the user target, avoiding symbol reexport problems when integrating as frameworks. It also applies to integration as static libraries to reduce build times by not creating unnecessary targets.
Fixes #3106
> No pod target if `source_files` only has headers.

- CHANGELOG.md
- lib/cocoapods/downloader/cache.rb
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/pod_source_installer.rb
- lib/cocoapods/installer/pod_source_preparer.rb
- spec/integration.rb
- spec/unit/installer/pod_source_installer_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/3435.
This supersedes #3457.
> [Cache] Run the prepare_command before cleaning

- bin/pod
🌈
This means operations like:
POD_VERSION="`pod --version`"
Work correctly even if LANG isn't set (e.g. within Jenkins).
> [pod] Write the UTF-8 warning to stderr, rather than stdout.

- CHANGELOG.md
- lib/cocoapods/sandbox/file_accessor.rb
- spec/unit/sandbox/file_accessor_spec.rb
Some Pods may include C++ source files with `.cc` extension (for example, `Objective-LevelDB 2.1.0`).
Without this patch, `inhibit_all_warnings!` will lose its functionality on `.cc` files.
> [Sandbox::FileAccessor] Add missing `.cc` extension for C++ to `SOURCE_FILE_EXTENSIONS`.

- lib/cocoapods/command/outdated.rb
```bash
bundle exec pod outdated --project-directory=src
Updating spec repositories
CocoaPods 0.37.0.rc.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.
No updates are available.
```
In this output, there is simultaneously an update available (CocoaPods gem) and no updates available (CocoaPods libraries). I've updated the latter message to "No pod updates are available." to hopefully disambiguate these states and clarify CocoaPods (gem) vs pod (libraries).
> [UI] Disambiguate gem and pod updates

- CHANGELOG.md
- lib/cocoapods/installer/pod_source_installer.rb
This patch check if a file is a regular file instead of checking if the file is a
directory.
It fixes a crash when the file being installed is a broken symbolic link.
I didn't know exactly where to put this modification in the changelog.
Let me know what you think.
------
```
/Users/dbarden/.gem/ruby/2.1.2/bin/pod install
```
* What did you do?
I ran into a pod file that contains a broken symbolic link and when trying to install the crash below happened
* What did you expect to happen?
That the dependency would be successfully installed
* What happened instead?
CocoaPods crashed with the log below
```
CocoaPods : 0.37.0
Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
RubyGems : 2.2.2
Host : Mac OS X 10.10.3 (14D136)
Xcode : 6.3.1 (6D1002)
Git : git version 2.3.5
Ruby …
```
> [Installer] Check for regular file on lock

- CHANGELOG.md
- lib/cocoapods/downloader/cache.rb
If `destination` exists already, `source` is not copied directly `destination` but instead to `copy+source.basename`.
> [Cache] Fix the cache to handle re-downloads properly

- lib/cocoapods/resolver.rb
… to #resolve.
Methods, which work like getters, shouldn't have side-effects.
> [Resolver] Move side-effect of storing head pods from #specs_by_target

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
This makes it easier to individually build the product of a development pod from a checked-in project, e.g. when using the pod-template, allowing for improved sharing with non-CocoaPods users.
> Shares schemes of any development pods.

- CHANGELOG.md
- lib/cocoapods/downloader/cache.rb
- spec/unit/downloader/cache_spec.rb
If the execution of `pod install` is interrupted, this could happen while the cache is being prepared or files are copied. That a pod is already downloaded was indicated before just by the existence of the file directory. With this PR, the cache is valid first, if the podspec is also present in the cache, regardless whether a podspec is associated with the request or not. That has the advantage that the podspec is written to the cache in the last phase of the download and this process is in comparison "more atomic".
/c @segiddins
> [Cache] Recognize incomplete cache for released pods

- CHANGELOG.md
- lib/cocoapods/executable.rb
- spec/unit/executable_spec.rb
This should make it unlikely that we don't catch the full output of
commands we are executing.
> Flush stdin/stderr and wait a bit in `executable`.

- CHANGELOG.md
- lib/cocoapods/installer/target_installer/pod_target_installer.rb
- spec/unit/installer/target_installer/pod_target_installer_spec.rb
`-analyzer-disable-checker` without arguments causes an error in the
static analyzer, but due to a bug in Xcode < 6.0 it was silently
ignored. As of Xcode 6.1 `-analyzer-disable-all-checks` can be used
to disable static analysis for specfic files.
rdar://18907351
https://github.com/CocoaPods/CocoaPods/issues/2402
> Use `-analyzer-disable-all-checks` for disabling static analysis.

- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
If both the parent and the transitive dependency are linked directly to the user target (`should_build? == false` for both of them), we can let transitive static libraries pass as everything will work just fine.
> Tweak transitive deps check for working cases

- CHANGELOG.md
- lib/cocoapods/sandbox/file_accessor.rb
- lib/cocoapods/sandbox/path_list.rb
I'm not sure if caching paths_for_attribute is wise or not, but in my test it makes `pod install` on our app much faster: 140 sec → 20 sec. All specs still pass.
It might be problematic if the content on the file system changes during the run, that's why it's more of an experiment that anything else.
What do you think?
> Cache globbing in PathList to speed up pod install

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/podfile_validator.rb
- spec/unit/installer/podfile_validator_spec.rb
Adds some simple validations of the dependencies in the podfile aimed at identifying conflicts in the download strategy/external sources.
Closes: #995
> [Podfile] Validations

- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
I found that a while ago while reviewing the `TargetIntegrator`, but it staled locally.
Do we want to allow user changes to the script or ensure at this place that updates to the script are applied, if needed?
Meanwhile there is still a bigger issue, that existing targets are not re-integrated on changes to the integration process, which is to a certain extent blocked by CocoaPods/Xcodeproj#202.
> [TargetIntegrator] Ensure to reset the contents of the Manifest.lock Script Phase

- spec/unit/installer/post_install_hooks_context_spec.rb
- spec/unit/installer/pre_install_hooks_context_spec.rb
The tests in `pre_install_hooks_context_spec.rb` and `post_install_hooks_context_spec.rb` are currently swapped, with the `pre_install` spec in the `post_install` file and vice versa.
Simple swap.
> [Specs] Fixed plugin specs in the incorrect files

- .gitattributes
From [GitLab's Blog](https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders) / https://github.com/artsy/eigen/pull/656
> ayufan suggested a much better solution in the comments of this article. If you add CHANGELOG merge=union to the .gitattributes file in the root of the repo you should not have any conflicts. Instead of leaving conflicts the [union merge](http://git-scm.com/docs/git-merge-file) option will resolve conflicts favouring both side of the lines. An example of such a setting change is in the endgamesingularity repo. Thanks ayufan, we’ll try this instead.
> Add a flag in the git attributes to do union merges

- CHANGELOG.md
- lib/cocoapods/installer.rb
Now it includes the offending Pods so that the user can take action
to remove the Pods, if they don’t want to move to frameworks yet.
```
[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it.
```
```
[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: FBSnapshotTestCase
```
> [Installer] Improve error message when using Swift in static libs.

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
Ensure that the header search paths include the public headers in the sandbox, if there are any pods that are statically compiled into the user target, when integrating Pods as frameworks.
Fixes #3857.
> Add header search paths for static library pods to the user target when integrating Pods as frameworks

- CHANGELOG.md
- lib/cocoapods/installer/file_references_installer.rb
- spec/fixtures/monkey/monkey.podspec
- spec/unit/installer/file_references_installer_spec.rb
When integrating Pods as frameworks, only link public headers into the sandbox if those headers are from a Pod that is not being built (that is, a static library Pod that's being statically linked into the user target).
Addresses #3867.
Depends on https://github.com/CocoaPods/cocoapods-integration-specs/pull/41
> When integrating Pods as frameworks, only link public headers in the sandbox for static Pods

- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
The missing space causes clang to produce `Cannot specify -o when generating multiple output files` errors in some cases.
Closes #3893
> Fix Issue #3893

- lib/cocoapods.rb
Hooks API was removed by #3649.
> Remove Hooks module definition with autoloads

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
This was an oversight in the watchOS 2 support PR.
> Use APPLICATION_EXTENSION_API_ONLY for watchOS 2 extensions

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/source_provider_hooks_context.rb
- spec/unit/installer/source_provider_hooks_context_spec.rb
- spec/unit/installer_spec.rb
This PR provides an initial/example implementation for the source provider plugin api described in #3190
I very much welcome suggestions for improvements - still new to both Ruby and the CocoaPods code base so it is very likely I am missing something.
The API would allow plugins to supply their own sources, whether they be un-versioned or using an unsupported VCS such as CVS, Hg, SVN, etc.
Example:
```ruby
plugin 'cocoapods-repo-svn', {
:sources => [
'https://svn.myrepository.com'
]
}
Pod::HooksManager.register('cocoapods-repo-svn', :source_provider) do |context, options|
source_names = options['sources']
source_names.each do |name|
source = MyCustomCreateSourceFunction(name)
context.add_source(source)
end
end
```
> [Installer] Add support for source provider plugin hook

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
Hi,
This PR fixes a bug that caused Xcode 7 (tested with beta 4 only) to build generic archives instead of iOS app archives.
I noticed this bug in a project that has an embedded framework. Both the app and the framework targets define pod dependencies. When the copy_resources script runs for the framework target, it copies the pod framework into the installation directory, even though `SKIP_INSTALL` is set to `YES`.
The resulting archive (before my changes) is displayed in Xcode like this:
Inspecting the archive file reveals that it contains multiple products - one for the app and one for the embedded framework:
For some reason it worked before with Xcode 6.4.
I put together a [demo project](https://github.com/nubbel/Cococapods-Xcode7GenericArchive) that allows you to verify the issue.
It …
> 🌈 Fix generic archives built by Xcode 7

- CONTRIBUTING.md
I was thinking about adding something like:
>* **Use [GitHub-flavored Markdown](https://help.github.com/articles/markdown-basics/).** Especially put code blocks and console outputs in backticks (```` ``` ````). That increases the readability. Bonus points for applying the appropriate syntax highlighting. (Tip: Podfiles are written in a Ruby DSL.)
>* **Show respect, spell the name of the project correctly.** It's CocoaPods. In upper camel case.
While I suspect that those who are doing it wrong, won't bother to read those recommendations.
> [CONTRIBUTING] Minor improvements

- lib/cocoapods/validator.rb
This means we'll actually print the part of the spec that's failing, which can be non-obvious in some cases, like when the invocation of xcodebuild fails.
\c @orta
> [Validator] Print the name of the attribute that has the result

- CHANGELOG.md
- lib/cocoapods/installer/file_references_installer.rb
- lib/cocoapods/sandbox/headers_store.rb
- spec/unit/sandbox/headers_store_spec.rb
See https://github.com/CocoaPods/CocoaPods/pull/4042.
Closes #1437. Closes #3760.
\c @neonichu
> The `HEADER_SEARCH_PATHS` will no longer be constructed recursively.

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
- Add missing `$(inherited)` values for the build settings `LIBRARY_SEARCH_PATHS` and `HEADER_SEARCH_PATHS` in generated xcconfig files.
- Update tests to explicitly check for these `$(inherited)` values.
Fixes #3908
This is my first PR to CocoaPods, so hopefully I did things correctly :) Also, I'm pretty sure that I was able to find and fix the two places where $(inherited) was missing. But I would greatly appreciate someone else's eyes on this, as this my first time looking at and touching this code.
> [Generator] Fix missing `$(inherited)` in xcconfig build settings

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/command/lib.rb
- lib/cocoapods/command/repo/push.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/downloader.rb
- lib/cocoapods/executable.rb
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/sandbox/file_accessor.rb
- lib/cocoapods/target/pod_target.rb
- lib/cocoapods/validator.rb
- spec/integration.rb
- spec/integration/file_tree.rb
- spec/unit/generator/embed_frameworks_script_spec.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
- spec/unit/installer/target_installer/aggregate_target_installer_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer_spec.rb
- spec/unit/sources_manager_spec.rb
- spec/unit/validator_spec.rb
Closes #1993.
Closes https://github.com/CocoaPods/CocoaPods/issues/3870.
Closes https://github.com/CocoaPods/CocoaPods/issues/3992.
Too tired to finish this.
- Adds support for more configurable `Executable` usage (including `executable?`)
- Adds support for vendored dynamic frameworks
- Removes reliance on the network in the specs (except for the integration specs)
- Ensure `-ObjC` is added when there are static vendored frameworks
\c @steipete
> Better vendored framework support

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/resolver.rb
- spec/unit/resolver_spec.rb
> [Resolver] Allow platform detection to work for nested dependencies

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
This fixes watchOS pods not being built using the `-sdk watchsimulator` SDK. 
Not doing this makes validation fail in bad ways. E.g. if you rely on preprocessor macros such as `TARGET_OS_IOS` vs. `TARGET_OS_WATCH` (not to be confused with `TARGET_OS_IPHONE` wich is true for watchOS and iOS).
> [Validator] build watchOS pods against watchossimulator for validation 🌈

- CHANGELOG.md
- lib/cocoapods/sandbox/file_accessor.rb
- spec/unit/sandbox/file_accessor_spec.rb
Added file extension '.i' (output of the C or C++ preprocessor) to the list of source file extensions.
It's necessary to set custom compiler flags for these files.
Example of pod that contains these files and sets custom compiler flags: https://github.com/CocoaPods/Specs/blob/master/Specs/glues/1.5/glues.podspec.json
> [Sandbox::FileAccessor] Add C++ Sources (.i)

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
This was causing warnings with the iOS 9 SDK as this path doesn't even exist anymore and seemingly wasn't needed since XCTest came along.
Fixes #4168
> Remove SDKROOT relative search path

- CHANGELOG.md
- lib/cocoapods/resolver.rb
- spec/fixtures/spec-repos/test_repo/PrereleaseMonkey/1.0-alpha1/PrereleaseMonkey.podspec
- spec/fixtures/spec-repos/test_repo/PrereleaseMonkey/1.0-beta1/PrereleaseMonkey.podspec
- spec/unit/resolver_spec.rb
As stated in #4197, `pod install` and `pod update` commands print wrong error information for the following case:
- There are only pre-release versions available for a pod specified in the Podfile (no stable versions).
- User does not explicitly set a version for the pod. She just uses `pod 'PodName'`
This PR fixes the case by  providing a meaningful error message for the occurring dependency conflict. 
While handling resolver error in `handle_resolver_error` method of `resolver.rb` file, the code will check if the specification that is not satisfying given requirement was a pre-release version, and if the requirement was including any explicit version or source. If spec is a pre-release version, and there is no explicit version or source for the requirement, the code will print a message …
> [Resolver] Give a meaningful message for the case where there is no stable version for a pod, and user do not explicitly specify the required version.

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
Successor to https://github.com/CocoaPods/CocoaPods/pull/4221.
Closes https://github.com/CocoaPods/CocoaPods/issues/4188.
\c @neonichu @orta @samdmarshall
> [EmbedFrameworksScript] Only manually copy swift runtime libs in Xcode 6

- CODE_OF_CONDUCT.md
Supersedes #3705
I have fixed the broken URL and incorporated 1.2.0 changes.
We still have to agree on a wording for when contributors are actively representing the project — I didn't really feel we reached a conclusion in the earlier discussion.
cc @alloy @samdmarshall
> Integrate Code of Covenant 1.2.0 changes

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
When running `pod install --no-integrate`, it's not required to validate that the `platform` attribute is specified for targets that don't declare any dependencies.
> [Analyzer] Don't require platform for podless targets when not integrating

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/fixtures/monkey/monkey.podspec
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
🌈 :thumbsup: 
This pull requests adds support for recursively processing `dependent_targets` to ensure that all `vendored_frameworks` and `vendored_libraries` are included in the target's build settings. This is only done if `use_frameworks` is specified.
> [XCConfig Helper] Add dependency target vendored libs and frameworks to build settings.

- CHANGELOG.md
- lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/target_installer/aggregate_target_installer_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
The AggregateTarget is linked to the user target, so that Xcode can find implicit dependencies. As it contains no symbols a user target can reference to, it was safe to weak link it only and not copy it in the app bundle as it would never loaded. By static linking it instead, we can achieve the same and after link-time there will be no trace left. By avoiding weak linking the aggregate target, we can fix some issues with bitcode and AppStore deployment validation, but that needs larger testing and validation with real-world projects.
There could be one alternative way to fix that all together and make explicit target dependencies happen: when the Pods.xcodeproj and the aggregate targets are generated, the existing UUID of the prior project need to be picked up or they need to be generated …
> [Installer] Always Link the AggregateTarget as static

- CHANGELOG.md
- lib/cocoapods/resolver/lazy_specification.rb
Closes #4345. The existing specs actually caught this once I ran them against ruby HEAD.
> [Resolver] Fix resolution on Ruby 2.3

- Rakefile
Hi,
As it stands, the following error is making PRs fail on Travis: https://travis-ci.org/CocoaPods/CocoaPods/jobs/85140003
The TL;DR for the cause is: Rake requires inch (inch-0.5.10/lib/inch/core_ext/string.rb), which requires Term::ANSIColor, and then it requires clintegracon (clintegracon-0.6.1/lib/CLIntegracon/diff.rb:2), which requires Colored. Since Colored is included after, its 'String#color' method, which has arity 1, is called instead of Term::ANSIColor's, which has arity 2. Hence the error.
This PR avoids it because the second`String.send(:include, Colored)` become an empty operation, since it was called at the very beginning of the tests.
> Fixing rake's Inch

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/pod_target.rb
…, by avoiding computing previously computed dependency trees.
On our cases, this makes what would be a 20min+ `pod install`, back into a 2min (measured with the performance gains described on the https://github.com/CocoaPods/CocoaPods/issues/4374 issue).
This gain is huge for projects with a lot of targets (20+) and pods (100+), when the de-duplication process happens.
> improving the performance of Pod::Installer::Analyzer#generate_pod_targets

- CHANGELOG.md
- lib/cocoapods/command/repo/lint.rb
- spec/functional/command/repo/lint_spec.rb
Solves #4142.
When the example command `pod repo lint artsy.podspec` runs, it will print the following message:
```
% poddev repo lint artsy.podspec
Linting spec repo `artsy.podspec`
[!] Unable to find a source named: `artsy.podspec`
```
I did not add another raise check, instead rely on the checks performed in `Source` class. Also used `SourceManager`'s methods to remove duplicate code.
> Improve repo lint error messaging

- CHANGELOG.md
- lib/cocoapods/project.rb
- spec/unit/project_spec.rb
Fixes #2597 
When a resource pattern like `**/*.{storyboard,strings}` is specified in a Pod that gets installed as a framework, files in `*.lproj` folders will now be grouped together by file name and base path in a `PBXVariantGroup`.
path = `<basepath>/<language>.lproj/<filename>.<extension>`
In the following
- `basepath` means the path of the parent directory of the .lproj directory that a localized file is in.
- `filename` means the name of the file without the extension
This is needed, so that Xcode recognizes them as localized versions of the the same file. It had already been possible to use a `**/*.lproj` pattern to copy localized `.strings` files. However with storyboards this does not work as Xcode (when building a framework) doesn't compile them when the `.lproj` folder is …
> Fix handling of localized files in Pods installed as frameworks

- CHANGELOG.md
- lib/cocoapods/command/lib.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/validator.rb
- spec/functional/command/lib_spec.rb
- spec/functional/command/repo/push_spec.rb
- spec/unit/validator_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/2095 in a circuitous manner.
Closes https://github.com/CocoaPods/CocoaPods/issues/2134.
> [Validator] Validate that apps can import the Pod

- lib/cocoapods/generator/copy_resources_script.rb
This solves #4388
However, I'm not sure if this also works for os x targets because I'm adding deployment target using `IPHONEOS_DEPLOYMENT_TARGET` environment variable.
PS: Travis will fail for integration tests. I will send a PR updating integration specs repo also.
> Add deployment target option for ibtool command in copy resources script

- CHANGELOG.md
- lib/cocoapods/resolver.rb
- spec/unit/resolver_spec.rb
This solves #4430.
Currently, when there is no existing specification inside any of the spec repos with given requirements, user would get the following error:
```
[!] Unable to satisfy the following requirements:
- `Lib (= 4.0.0)` required by `Podfile`
```
Now, user will get sth like this:
```
[!] Unable to find a specification for the following requirement:
'Lib', '= 4.0.0'
```
I think this is enough for user to understand that their repo either not up-to-date or there is really no such specification with given dependency.
I actually wanted to use `Molinillo::NoSuchDependencyError` rather manually adding another message, but it's message does not contain name of the dependency, just it's version. 
I'm open to better management suggestions.
> Improve message when there is no spec in repos for a given dependency

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/config.rb
- lib/cocoapods/sources_manager.rb
- spec/functional/command/repo/update_spec.rb
- spec/spec_helper/pre_flight.rb
- spec/unit/config_spec.rb
- spec/unit/sources_manager_spec.rb
Detailed discussion can be found here: CocoaPods/cocoapods-search#8 
- Previous implementation was having the drawback of traversing and performing `gsub` on all index strings for each pod specification.
- New implementation stores words as keys and list of pods containing corresponding word inside their specification as the values for corresponding hash keys. Therefore, while searching for a query, we only need to check if query is matched with any key in index hash, if so, we will add corresponding list of spec names to a Set object. Resulted Set object gives us the search result. Using this policy, sources manager can perform a faster search operation.
> Changes search index format to fasten `pod search --full` command.

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
Closes CocoaPods/cocoapods-search#12.
Calculates ordering score according to following criteria with evaluating in the written order.
- # of found queries in pod name (in cases for multi word queries)
- Pre-match length of the first matched query word.
- Index of of the first matched query word.
- Downcase name of the pod.
> Improve sorting algorithm for `pod search`

- CHANGELOG.md
- lib/cocoapods/sandbox/file_accessor.rb
- spec/unit/sandbox/file_accessor_spec.rb
We use `.def` files for sources in one of our projects and pods do not pick them up as source files.
`.def` is just a generic extension for files we process using the preprocessor, it’s C/C++ source code.
I know its a bit unique of usage but it seems harmless to track this extension also.
> Track .def files as sources

- lib/cocoapods/user_interface.rb
Related to CocoaPods/cocoapods-search#17. Removes newline included while printing pod information in order to make coloring work in a pager.
> Remove newline causing color problem when printing to a pager

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
This prevents crashes which can happen when `pod install` command is run from inside subdirectories of Pods directory.
> Prevent installer to be run from inside sandbox directory

- lib/cocoapods/installer/target_installer/pod_target_installer.rb
- spec/unit/installer/target_installer/pod_target_installer_spec.rb
#4267 preserves the directory structure inside the Pod's header_mappings_dir, if one is specified in the podspec.
This led to problems with the pod target's umbrella header, since the (now nested) path of the included header files needs to be taken into account when generating the import statements.
I would classify this rather as a bugfix than an enhancement. Should I create a Changelog entry for this, even though the Bug has not been released yet?
> Use correct path for import in umbrella header when preserving header_mappings_dir

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
Shows an error message in Xcode like the following:
```
Resource "RESOURCE_PATH" not found. Run 'pod install' to update the copy resources script.
```
> Ask user to run 'pod install' when a resource to copy not found

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/sandbox/file_accessor.rb
- spec/unit/sandbox/file_accessor_spec.rb
My initial pull request was wrong at https://github.com/CocoaPods/CocoaPods/pull/4490 and they are meant to be treated as header files instead of source files.
Correct xcodeproj PR https://github.com/CocoaPods/Xcodeproj/pull/338
Apologies for this.
> Undo tracking of .def files as sources

- CHANGELOG.md
- lib/cocoapods/generator/module_map.rb
- lib/cocoapods/installer/file_references_installer.rb
- lib/cocoapods/installer/target_installer/pod_target_installer.rb
- spec/unit/generator/module_map_spec.rb
Closes #4420 .
\c @neonichu @mtitolo
> [FileReferencesInstaller] Dont create build headers for frameworks

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/resolver.rb
- lib/cocoapods/sources_manager.rb
- spec/fixtures/spec-repos/test_repo/CrossRepoDependent/1.0/CrossRepoDependent.podspec
- spec/functional/command/outdated_spec.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/resolver_spec.rb
- spec/unit/sources_manager_spec.rb
This adds the ability to add a `:source` flag to pod dependencies in a Podfile. This behavior mirrors in [Gemfiles](http://bundler.io/gemfile.html), allowing a dependency to be specified as such:
`pod 'JSONKit', '1.4', :source => 'http://github.com/MyOrg/Specs.git'`
Depends on https://github.com/CocoaPods/Core/pull/278
> Add ability to specify source with each dependency

- CHANGELOG.md
- lib/cocoapods/project.rb
- spec/unit/installer_spec.rb
- spec/unit/project_spec.rb
- spec/unit/validator_spec.rb
> Fix Swift code completion for Development Pods

- CHANGELOG.md
- lib/cocoapods/installer/target_installer.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/4521.
The aforementioned issue was due to the fact that the products group file references didn't have unique paths / names, and therefore the deterministic UUID generator was unable to distinguish them. This PR fixes that by ensuring that the PBXFileReference keeps its normal path.
\c @mrackwitz
> [TargetInstaller] Ensure installed targets still have unique paths

- lib/cocoapods/generator/copy_resources_script.rb
Closes #4548.
Problem was putting ${PODS_ROOT} as a prefix while checking resource existence. It now at first generates the full path of the source,  and then uses that everywhere. This seems more convenient to me.
No CHANGELOG needed.
If changes are OK, I will update integration specs and merge this.
\c @segiddins @orta
> Fix resource existence check for resources with absolute paths

- lib/cocoapods/command/spec/create.rb
- spec/functional/command/spec_spec.rb
Changes to make `pod spec create` produce *podspecs* with `s.version.to_s` as the git tag when possible
```ruby
s.source = { :git => 'https://github.com/Ashton-W/CRToast.git', :tag => s.version.to_s }
```
If there are no tags or the tags contain extra characters (eg: `v1.4`) a string with the tag is used (current behaviour).
> `pod spec create` to use `s.version.to_s` as the git tag when possible

- lib/cocoapods/validator.rb
Before:
```[!] Contentful did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it) and All results apply only to public specs, but you can use `--private` to ignore them if linting the specification for a private pod..```
After:
```[!] Contentful did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it) and all results apply only to public specs, but you can use `--private` to ignore them if linting the specification for a private pod.```
> Fix validator message

- CHANGELOG.md
- lib/cocoapods/command/repo/push.rb
When pushing a spec to the specs repo, the commit message cannot be customized. It would be useful to add the ability to add a custom commit message.
If the user adds the `--message` flag, the default editor is opened, allowing the user to enter a custom commit message that is used when the spec is pushed to the specs repository.
> [Repo Command] Add Ability to Add Custom Commit Message When Pushing Spec

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer/target_installer/pod_target_installer.rb
Closes #4501.
Resource bundles generated by CocoaPods were not having Info.plist files, which was weirdly causing asset catalogs not to be compiled.
Adding Info.plist solves compiling issues for asset catalog files inside resource bundles.
Thanks to @samdmarshall for insight!
> Create Info.plist files for resource bundles

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/target_installer/pod_target_installer.rb
- lib/cocoapods/sandbox/headers_store.rb
- lib/cocoapods/target/pod_target.rb
- lib/cocoapods/validator.rb
- spec/functional/command/repo/push_spec.rb
- spec/unit/installer/target_installer/pod_target_installer_spec.rb
- spec/unit/sandbox/headers_store_spec.rb
- spec/unit/validator_spec.rb
closes #4552.
This is really really gross, but more correct. Would appreciate suggestions on how to refactor it.
> [PodTarget] Ensure the deployment target is high enough for frameworks

- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
By using the `-scheme` it defaults to `Debug` versus using the `-target` that the old linter had.
/cc @segiddins
> Use release configuration with new linter

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Since those are full paths, uniquing the list ensures we only consider each framework once for the check, no matter if it is linked against multiple targets.
Fixes #4550
> Unique the list of vendored frameworks.

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/project.rb
- spec/unit/project_spec.rb
Closes #4143.
Closes #4148.
\c @mrackwitz
> [Project] Change config defines to be prefixed

- lib/cocoapods/installer.rb
> Make de-integration wording less verbose.

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator/xcconfig_integrator_spec.rb
Issue here is the scenario where a project gets added to a new workspace temporarily and has its pods built in a new directory. In that case, the location of the newly generated config file may differ from the existing one, but the config is actually identical. So when the config files are the same, it seems reasonable to silence the ominous "CocoaPods may not work at all" message since it definitely works.
If there's a different or better way to handle this edge case, that'd be great too — I'm not experienced with Ruby so I easily could have missed something else.
> Don't warn about setting base config when existing is identical to new one

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
> [Analyzer] Fetch :podspec dependencies when the spec is missing

- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
**Issue**
`pod` suggested to prefix `gem install` with `sudo` even though I'm using user-local `rbenv`.
`sudo` shouldn't be suggested if not needed to avoid `chown` pain later.
**Solution**
Extracted `needs_sudo` into own method `needs_sudo?`
Wrote a test for each outcome of `needs_sudo?`
P.S. Would be nice if you could add an empty Master section in CHANGELOG after releases to not make contributors guess what to do here without causing conflicts.
> [SourcesManager] Fix wrong sudo recommendation 🌈

- CHANGELOG.md
- lib/cocoapods/installer/file_references_installer.rb
- spec/unit/installer/file_references_installer_spec.rb
- spec/unit/installer/target_installer/pod_target_installer_spec.rb
https://github.com/CocoaPods/CocoaPods/issues/4762
Root of the issue was that the resources were being added to the xcodeproj in all-lowercase, and when the target installer went to look for items using properly-cased paths they didn't match, so it didn't add them to the targets.
> Fix bug where lproj directories aren't added to project

- lib/cocoapods/command/init.rb
- lib/cocoapods/command/inter_process_communication.rb
- lib/cocoapods/command/repo/add.rb
- lib/cocoapods/command/repo/lint.rb
- lib/cocoapods/command/repo/update.rb
- lib/cocoapods/command/spec/cat.rb
- lib/cocoapods/command/spec/edit.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/command/spec/which.rb
I noticed inconsistent help messages while using `pod repo --help` so I went through and fixed the summaries in `command`. Short summaries without periods were more prevalent so I adjusted the rest of them.
```sh
» pod repo --help                                                                                                                 
Usage:
$ pod repo [COMMAND]
Manage spec-repositories
Commands:
+ add       Add a spec repo.
+ lint      Validates all specs in a repo.
> list      List repos
+ push      Push new specifications to a spec-repo
+ remove    Remove a spec repo
+ update    Update a spec repo.
Options:
--silent    Show nothing
--verbose   Show more debugging information
--no-ansi   Show output without ANSI codes
--help      Show help banner of specified command
> Audit CLI help for period consistency

- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
The list of dependencies on `PodTarget` contains already all transitive dependencies, that means recursively calling the method for any of its elements won't catch additional targets and just wastes some cycles.
> [XCConfig] Don't recurse for transitive dependencies

- lib/cocoapods/command/project.rb
I skipped references to `xcodeproj` in strings, so I missed these occurrences. I double checked all remaining occurrences and it seems like these were the only ones which had to be changed.
> [Command Project] xcodeproj was renamed to project

- CHANGELOG.md
- lib/cocoapods/executable.rb
- lib/cocoapods/installer/pod_source_preparer.rb
- spec/unit/installer/pod_source_installer_spec.rb
This gives non-trivial podspecs one way to adopt the breaking changes of 1.0 while staying backwards-compatibility with 0.39. This isn't suitable when two versions of CocoaPods are used alongside as the `prepare_command` is run once on the cached sources. We could mitigate this by making the cache version-specific.
> Propagate the CocoaPods version to the prepare_command

- CHANGELOG.md
- lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
- spec/unit/installer/target_installer/aggregate_target_installer_spec.rb
While #4146 fixed one problem described in #4872, it brought up another one. The paths in the `CopyResourcesScript` passed to the `install_resource` function for resource bundles are wrong.
> Fix resource bundle paths for improved deduplication

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
This adds an emoji in front of every Script Build Phase added by CocoaPods to the user project.
Aside the fact that emojis are awesome and should be everywhere, this also has the practical application of quickly & visually identify which phases are CP and which are from Xcode (or others).
---
~~This PR is still WIP as the integration specs should be rebuild with the new phase names before merging.~~
However, I wanted to open it early so that we can **discuss a very serious matter: which standard Unicode emoji best describe CocoaPods-related stuff?** (is :package: a good fit or should we use another one?)
---
> Add emoji in CocoaPods Build Phases

- CHANGELOG.md
- lib/cocoapods/executable.rb
(Also a tiny perf boost when `PATH` is heavily duplicated)
> [Executable] Handle when $PATH is not set

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/sandbox/file_accessor.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/4968.
Relies on https://github.com/CocoaPods/Core/compare/seg-allow-inheriting-root-only?expand=1
> [FileAccessor] Access root-only values from the spec consumer

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/command/outdated.rb
- lib/cocoapods/executable.rb
- lib/cocoapods/resolver.rb
- lib/cocoapods/sources_manager.rb
- spec/functional/command/repo/update_spec.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/sources_manager_spec.rb
- spec/unit/validator_spec.rb
Depends on https://github.com/CocoaPods/Core/pull/313
It also currently points at my fork of Core for the purpose of running the tests on CI.
> Refactor SourcesManager to use Source/MasterSource

- CHANGELOG.md
- lib/cocoapods/command/repo/add.rb
- lib/cocoapods/command/setup.rb
- lib/cocoapods/sources_manager.rb
- spec/functional/command/repo/add_spec.rb
- spec/functional/command/setup_spec.rb
- spec/unit/sources_manager_spec.rb
Depends upon https://github.com/CocoaPods/CocoaPods/pull/5014.
Closes #5016.
\c @DanielTomlinson @orta @alloy
> Disallow shallow clones of specs repos

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
Fixes #5022. Xcode overwrites this variable for UI test apps, but not the previously used `CONFIGURATION_BUILD_DIR`. While `USES_XCTRUNNER` is not documented as effector of this variable (:tada:), the [build settings reference](https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW88) confirms that this is the variable to rely on.
>Run Script build phases that operate on product files of the target that defines them should use the value of this build setting.
Just to be sure to conform closer to the documentation, use also `BUILT_PRODUCTS_DIR` instead of `CONFIGURATION_BUILD_DIR` for the origin, because:
>But Run Script build phases that operate on product …
> [EmbedFrameworksScript] Rely on TARGET_BUILD_DIR to locate destination

- CHANGELOG.md
- lib/cocoapods/validator.rb
Closes #4936.
Hard to test because the current validator specs all use JSONKit, which doesn't have enough source files to reproduce the issues.
> [Validator] Validate that header files are in source_files

- CHANGELOG.md
- lib/cocoapods/command.rb
- lib/cocoapods/command/install.rb
- lib/cocoapods/command/inter_process_communication.rb
- lib/cocoapods/command/options/project_directory.rb
- lib/cocoapods/command/options/repo_update.rb
- lib/cocoapods/command/outdated.rb
- lib/cocoapods/command/project.rb
- lib/cocoapods/command/update.rb
- lib/cocoapods/config.rb
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/validator.rb
- spec/functional/command/install_spec.rb
- spec/functional/command/outdated_spec.rb
- spec/functional/command/project_spec.rb
- spec/functional/command/repo/list_spec.rb
- spec/functional/command/spec_spec.rb
- spec/functional/command/update_spec.rb
- spec/spec_helper/pre_flight.rb
- spec/spec_helper/temporary_repos.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer_spec.rb
Fixes #5004.
Will requires updates in because of the removal of `Config.skip_repo_update`:
> [Command::Project] No repo update by default on install

- CHANGELOG.md
- lib/cocoapods/sandbox/path_list.rb
- spec/unit/sandbox/path_list_spec.rb
`Dir.glob` result on case sensitive file system may be different from the result on case insensitive file system. This would cause unintentional diffs on `-umbrella.h` files depending on the config of file system in which `pod install` is done, when `Pods` directory is in the repository.
1. `pod install` on case insensitive file system → files are sorted case insensitively
2. `git commit && git push`
3. `pod install` on case sensitive file system → files are sorted case sensitively
4. Diffs may appear on `-umbrella.h` files
This pull request is to fix this issue by sorting `Dir.glob` result explicitly.
> Sort Dir.glob result in PathList case insensitively

- CHANGELOG.md
- lib/cocoapods/generator/info_plist_file.rb
Closes #4897.
I believe the integration spec failure here will act as sufficient test coverage for this.
> [Generator::Plist] Ensure a CFBundleVersion is set for resource bundles

- CHANGELOG.md
- examples/Vendored Framework Example/Example Pods/VendoredFrameworkExample.podspec
- examples/Vendored Framework Example/Examples.xcworkspace/contents.xcworkspacedata
- examples/Vendored Framework Example/Podfile
- examples/Vendored Framework Example/Vendored Framework Example.xcodeproj/project.pbxproj
- examples/Vendored Framework Example/Vendored Framework Example.xcodeproj/xcshareddata/xcschemes/Vendored Framework Example.xcscheme
- examples/Vendored Framework Example/Vendored Framework Example/AppDelegate.swift
- examples/Vendored Framework Example/Vendored Framework Example/Assets.xcassets/AppIcon.appiconset/Contents.json
- examples/Vendored Framework Example/Vendored Framework Example/Base.lproj/LaunchScreen.storyboard
- examples/Vendored Framework Example/Vendored Framework Example/Base.lproj/Main.storyboard
- examples/Vendored Framework Example/Vendored Framework Example/Info.plist
- examples/Vendored Framework Example/Vendored Framework Example/ViewController.swift
- lib/cocoapods/installer/file_references_installer.rb
- spec/unit/installer/file_references_installer_spec.rb
:rainbow:
Currently when including a vendored_framework in your podspec, its headers will be linked into the Pods/Headers/Public directory. This directory is added to the HEADER_SEARCH_PATH of any pod target that depends on it. Which will lead to a "Include of non-modular header inside framework module" error, because Xcode doesn't like it when header files are both available through header search paths and framework search paths (https://forums.developer.apple.com/thread/23554#81066).
This pull request fixes this issue. It is basically doing for vendored frameworks what already has been done for the build headers in PR #4476.
It is also likely fixes #4805.
> Fix non-modular header errors for vendored frameworks.

- CHANGELOG.md
- lib/cocoapods/command/repo/update.rb
- lib/cocoapods/sources_manager.rb
Who said a constant should be constant?
This is evil, but I think its necessary to ease the pain for third-party transition to CocoaPods 1.0. We will remove this hack very very soon, I promise.
\c @alloy @mrackwitz
> [SourcesManager] Provide a deprecation path for access to Pod::SourcesManager

- CHANGELOG.md
- lib/cocoapods/command/init.rb
- spec/functional/command/init_spec.rb
From 
``` ruby
target "Thing" do
end
target "ThingTests" do
end
```
to 
``` ruby
target "Thing" do
target "ThingTests" do
inherit! :search_paths
end
end
```
Current tests were already covering that apps were generating Podfiles that generated the same kind of  project, wasn't sure whether to add some plaintext checks, but it seemed that because no tests were doing it so far. Thus we were relying on the integrations working, which it does.
> Add support for CP1.0 style target inheritence in `pod init`

- CHANGELOG.md
- bin/pod
Closes #5013 
Just prints a different docstring now if we find --no-ansi in ARGV. I tried just printing the colour codes conditionally but it didn't seem to work in my local terminal. I'm sure there is a more "ruby" way to do this 😛
> Make the utf-8 warning message respect --no-ansi

- CHANGELOG.md
The URL was copy-pasted and nobody updated the suffix with the pull request id
> Fix URL in changelog pointing to a wrong pull request

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/installation_options.rb
- spec/unit/installer/installation_options_spec.rb
- spec/unit/installer_spec.rb
This allows for opting out of sharing schemes for development pods.
By default, the current behavior is kept -- all dev pods have their
schemes shared. By setting the option to `nil` or `false`, no schemes
are shared. Otherwise, an array can be passed, and only dev pod names that
match elements of that array will have their schemes shared.
@neonichu @orta how do we feel about providing this as an option?
> [InstallationOptions] Add #share_schemes_for_development_pods

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/5282
Tested on a project with several dependencies with XIBs and an example project for a library with XIBs
Depends on https://github.com/CocoaPods/cocoapods-integration-specs/pull/69
> [CopyResourcesScript] Add --target-device to ibtool invocation for XIBs #5282

- lib/cocoapods/installer/analyzer/target_inspector.rb
Fixes an informative message that appears when the project can't be found.
This is what was seeing before:
<pre>[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:
xcodeproj 'path/to/Project.xcodeproj'
[...]
[!] xcodeproj was renamed to `project`. Please use that from now on.</pre>
> Update an info message for 1.x: Change xcodeproj → project

- CHANGELOG.md
- lib/cocoapods/config.rb
- spec/unit/config_spec.rb
Some characters like "ü" where being represented as `["u", "̈"]` in ruby < 2.3.0 and it caused errors down the line.
I tried using `String#unicode_normalize` but turns out it's only available since ruby 2.2.0, so I'm using ActiveSupport normalization.
I don't know how this kinds of workarounds need to be documented? In the future if CocoaPods moves to ruby >= 2.3.0 this normalization wouldn't be needed anymore.
Fixes #5294
> [Config] Normalize installation_root to ensure same character encoding

- lib/cocoapods/validator.rb
Before: `The pattern includes header files that are not listedin source_files`
After: `The pattern includes header files that are not listed in source_files`
> [Validator] Adds space to fix typo in output in Validator

- lib/cocoapods/command/repo/push.rb
`super` should be first in the case that the help flag is passed in.
https://github.com/CocoaPods/CLAide/blob/master/lib/claide/command.rb#L543-L550
> [Repo Push] Help validation

- CHANGELOG.md
- examples/AFNetworking Example/AFNetworking Mac Example.xcodeproj/project.pbxproj
- examples/AFNetworking Example/AFNetworking iOS Example.xcodeproj/project.pbxproj
- examples/Alamofire Example/iOS Example.xcodeproj/project.pbxproj
- examples/HeaderMappingsDir Example/HeaderMappingsDir Example.xcodeproj/project.pbxproj
- examples/Resource Bundle Example/Resource Bundle Example.xcodeproj/project.pbxproj
- examples/TestInclusions/TestInclusions.xcodeproj/project.pbxproj
- examples/Vendored Framework Example/Vendored Framework Example.xcodeproj/project.pbxproj
- examples/watchOS Example/watchOSsample.xcodeproj/project.pbxproj
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
Some tools not handling emojis properly might alter the Build Phase names, making it change the 📦 emoji into some <Uxxx> sequence instead.
This patch intend to workaround that issue those tools generate, so that users of such tools have a less painful experience with CocoaPods until that Unicode issue is fixed at its source in AppCode et al.
--- 
This PR is **open for discussion** as the debate is still not finished about if we should accept workarounds like that… to fix bugs that are in fact in other softwares like AppCode and not CocoaPods issues per se.
_(Specs and CHANGELOG will be added only if we agree on this workaround and consider merging)_
> Patch to workaround the Build Phases name matching with emojis

- Dangerfile
Adds an example entry for the CHANGELOG entry when one isn't provided in a PR, this PR should initially fail with an example of what it looks like.
> Add a note to include a CHANGELOG entry in a PR #trivial

- Gemfile
This can be set to true on release branches, so that only versions of the gems which were released and pushed to RubyGems are considered.
/c @segiddins
> [Gemfile] Add flag to skip unreleased versions

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
This PR adds the ability to inhibit swift warnings for pod targets. This is related to [issue 5290](https://github.com/CocoaPods/CocoaPods/issues/5290).
Even without my changes, many unit tests fail locally. Why is that?
> [XCConfigHelper] Add the ability to inhibit swift warnings

- Rakefile
Fixes #5458:
- check_submodules task verifies submodules are initialized by checking the output of `git submodule status` (as far as I can tell, there aren't ways of doing this that rely on an exit code that aren't more complex)
- spec task depends on this task
> Added rake task to check submodules

- Dangerfile
Danger was crashing because `pr` was undefined, looks like this was a typo for `pr_title`
> use `pr_title` instead of `pr.title` in Dangerfile

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/downloader.rb
- lib/cocoapods/downloader/cache.rb
- spec/unit/downloader_spec.rb
This adds the posibility of caches hits for git branch dependencies.
Previously, since pods didn't know the commit the branch points it
always did a full clone of the repo. Using `ls-remote` we can check the
commit the branch points to and reuse cached version of the pods if
available.
Related to https://github.com/CocoaPods/CocoaPods/issues/5376
> [Cache] Use `git ls-remote` to skip full clones for branch dependencies

- CHANGELOG.md
- lib/cocoapods/command/repo/push.rb
- spec/functional/command/repo/push_spec.rb
🌈
We use a private repository for podspecs and found that when we changed to 1.0.1 cocoapods we had issues with Ruby DSLs that were old.
Following the trunk, we decided to convert our DSL to JSON format when pushing to our repository.
We thought that others could use the same thing.
> [repo/push] --use-json to convert podspecs to JSON format when pushing

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
Fixes #5558 
Depends on CocoaPods/Xcodeproj#390 to actually work in practice.
> Set 'Allow app extension API only' for Messages extensions

- CHANGELOG.md
- lib/cocoapods/command/repo/push.rb
- spec/functional/command/repo/push_spec.rb
🌈
This should be useful to developers using CI environments to publish to private repositories.  
Currently you have to have a repo added locally in order to push to it using `pod repo add PrivateRepo http://private.com/repo.git`, however executing this more than once will cause an error that would need to be ignored or more complicated setup.
You still need the machine to have access rights to push to that private repositories, but this alleviates a struggle for deploying.
(also I know this will likely conflict with https://github.com/CocoaPods/CocoaPods/pull/5568 when merged, but should be minor updates to fix.)
> [repo/push] allow URLs for pushing to private repos

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/pod_variant.rb
- lib/cocoapods/installer/analyzer/target_inspector.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/analyzer/pod_variant_spec.rb
- spec/unit/installer/analyzer/target_inspector_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Depends on https://github.com/CocoaPods/Core/pull/342
Closes https://github.com/CocoaPods/CocoaPods/issues/5521
> [Installer] Use user defined swift version

- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
Fixes a bug on master where active_support doesn't get loaded for `try` during pod install.
https://github.com/CocoaPods/CocoaPods/issues/5599#issuecomment-230892216
I don't think this needs a changelog entry because it's something that's only broken in master?
> Require active_support in xcconfig_helper

- CHANGELOG.md
- Gemfile.lock
- cocoapods.gemspec
Version 5 of `activesupport` requires Ruby version >= 2.2.2 which breaks fresh installations using system Ruby, which is still 2.0, even on macOS 10.12.
Supersedes CocoaPods/Xcodeproj#393
It makes more sense to do this in CP directly, because almost nobody will need to use it with `activesupport` 5 whereas other consumers of `xcodeproj` can still choose the newer version freely.
> Avoid use of `activesupport` version 5

- lib/cocoapods/installer/xcode/pods_project_generator.rb
The specifier is definitely self-explanatory in what it does, but should be explicit about how it specifies: to achieve bogus-ness.
Regarding CocoaPods/CocoaPods#5528.
Via https://twitter.com/NeoNacho/status/753959283797192705
CC @neonichu 😄🌈
> Comment on bogus-ness of `PROVISIONING_PROFILE_SPECIFIER` for `PodsProjectGenerator`.

- CHANGELOG.md
- lib/cocoapods/installer/analyzer/pod_variant_set.rb
- spec/unit/installer/analyzer/pod_variant_set_spec.rb
supersedes https://github.com/CocoaPods/Core/pull/344
actually closes https://github.com/CocoaPods/CocoaPods/issues/5491
> Hash scope suffixes if they are over 50 characters

- lib/cocoapods/command/init.rb
- spec/functional/command/init_spec.rb
Resolves #5438.
* Clarify that commenting/uncommenting applies to the _next_ line.
* Fix a couple minor typos (it's -> its).
> Fix #5438 - Make comments more clear

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Set empty codesigning identifiers for the `appletvos` and `watchos` platforms so that they will correctly build with Xcode 8 betas.
closes https://github.com/CocoaPods/CocoaPods/issues/5686
depends on https://github.com/CocoaPods/cocoapods-integration-specs/pull/75
> [Installer] Set codesigning identity for watchos/tvos

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/target/aggregate_target_spec.rb
Fixes #5594 
During analysis, we collect information on the product types of the host targets for the embedded targets. Then we use that to help determine if `requires_host_target?` is true or false. The addition here is that it's now false when the host target is a messages application because this type of target does not have a user-modifiable (in the Xcode 8 UI) target dependency list/build phase.
> Added support for message extensions embedded in messages applications

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
Fixes #5687
If all of the targets that require host targets in the Podfile are frameworks, you get a warning like this:
```
[!] The Podfile contains framework targets, for which the Podfile does not contain host targets (where these frameworks would be installed).
If this project is for doing framework development, you can ignore this message or add a test target that embeds these frameworks to make this message go away. Otherwise, please add the frameworks' host targets to the Podfile.
```
If there are more than just framework target types, the `Informative` has been updated like this:
```
[!] Unable to find host target(s) for MyAppExtension. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target, in which to be embedded. These …
```
> Improved messages when missing host targets in the Podfile. Improved framework-only dev support.

- .gitmodules
- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
It looks like we should be setting this new flag in Xcode 8:
- This new flag has made #4203 crop up again.
- According to research done in #5598, this deprecates the old `EMBEDDED_CONTENT_CONTAINS_SWIFT` flag.
This shouldn't be merged until the following is done:
> Set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES when appropriate

- CHANGELOG.md
- lib/cocoapods/installer/analyzer/target_inspector.rb
- spec/unit/installer/analyzer/target_inspector_spec.rb
Fixes #5737 and #5700 
`PodVariant`s are unique by, among other things, their `TargetDefinition`'s swift version. Previously this would be `nil` if only defined at the project level. This would lead to multiple `PodVariant` instances for the same `PodTarget` incorrectly, and later on this leads to the `Errno::EEXIST` errors from incorrectly trying to create the same support files directories for the same `PodTarget`s.
> Use the project-level swift version when not defined at the target-level

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
The new swift build settings are a bit confusing, and my coworkers and I were able to reproduce what we initially thought was the same issues as #5700 and #5737. It turned out to be slightly different. We don't validate that the swift version of the embedded target matches that of its host. This change adds that validation.
> Verify embedded target platform/swift matches its host

- CHANGELOG.md
Capitalized “Messages” to make clear that it is a product name reference (Mac/iOS Messages.app), and added a verb to clarify that the fix pertains to the end use of CocoaPods as opposed to its integration with something else.
> Improved clarity of title for #5726 summary entry.

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/fixtures/SampleProject/SampleProject.xcodeproj/project.pbxproj
This fixes #5783.
You could have your embedded target be embedded in multiple hosts, but only have CocoaPods help with integrating into one of those hosts. This fixes a bug I introduced in #5747, where the analyzer would assume it has the target definitions for all of an embedded target's hosts.
There is no new spec here, but updating the SampleProject fixture to embed a framework target in a 2nd target exposed the bug and failed the "copy a framework's pod target, when the framework is in a sub project" spec with a backtrace similar to that found in #5783. This PR fixes the spec.
> Make analyzer skip the embedded target -> host compatibility check for hosts not defined in the Podfile

- CHANGELOG.md
- lib/cocoapods/command/lib/create.rb
- spec/functional/command/lib/create_spec.rb
The new pod-template isn't backwards compatible with older versions of CocoaPods due to linking to a framework, https://github.com/CocoaPods/pod-template/pull/187 - this gives it the ability to let people know that.
> [Create] Pass the Pod::version as a ENV var for the configure script to read

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/command/repo/push.rb
- lib/cocoapods/sources_manager.rb
- lib/cocoapods/validator.rb
- spec/unit/sources_manager_spec.rb
- spec/unit/validator_spec.rb
Removes uses of `Dir.chdir` for this flow. It prefers using `git -C` and passing the full path to App.xcworkspace for validation. This fixes #5805
> Fixed pod repo push validation and push issues related to Dir.chdir

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Will default to SWIFT_VERSION = 2.3, but will check for a `.swift-version` file and use the version specified there if present.
> Fix linting on Xcode 8

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
We have a large project and our `pod install` time keeps increasing the more targets and pods we add.
Based on an old profile we did (http://danielribeiro.github.io/braintree_ios/ProfileForCallStackPrinter.html) it seems that during installation a lot of time is spent for checking if a target can be built or if it uses swift.
This small change speeds up our `pod install` by a lot (from 1m 40s to about 1m and 3s).
@segiddins the only concern is if that value should be invalidated at any point. For example, is there a chance the `prepare_command` of a pod generate sources that this change will miss?
> Cache result of uses_swift and should_build

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/target/aggregate_target_spec.rb
This fixes #5860. It looks like I was wrong in assuming that messages applications can't have frameworks embedded in them. I'm not sure how a user would do this though, since last I checked you can't modify the messages app's Target Dependencies build phase via the Xcode 8 UI.
After this change, messages extensions will be treated like any other extension type.
Waiting to merge this, until I get further confirmation from @isair
> Remove special casing for messages apps

- CHANGELOG.md
- lib/cocoapods/sandbox/path_list.rb
* Used a simple `String.slice` to create relative paths instead of `path.relative_path_from(root)`. Since we already know that all files must exist under `root` (because we globbed `absolute_paths` from `root`), we can just remove the first `root.to_s.length + 1` characters from an `absolute_path` to get a `relative_path`.
* Partition `dirs` and `files` first since we already get an array of absolute paths back from `Pathname.glob`, removing unnecessary string concat: `File.directory?(root + path)`
* Used `lazy` arrays to reduce array iteration.
I [profiled my code before the change](https://github.com/CocoaPods/CocoaPods/files/477973/call-stack.zip).
I [profiled my new code again](https://github.com/CocoaPods/CocoaPods/files/478512/call-stack2.html.zip), and `read_file_system` …
> [path_list.rb] Improve performance of read_file_system

- CHANGELOG.md
- cocoapods.gemspec
- lib/cocoapods/command/install.rb
- spec/functional/command/install_spec.rb
Previously it would only look at the issues if the error occurred inside a Podfile, or as a part of an informational error that we've created. The problem is, most of our errors right now are occurring outside of that scope. 
So this expands the scope to all of `pod install`. Only when it comes from Ruby, so it should hit a lot of the `Errno::EEXIST - File exists` kind of issues for example. 
Also fixes a minor spacing issue in the gemspec.
> Expand the usage of the GH Inspector to all of pod install

- CHANGELOG.md
- lib/cocoapods/command/install.rb
- spec/functional/command/install_spec.rb
Undoes #5950 - as it was running the inspector twice.
> Remove the superfluous call to gh inspector introduced in #5950

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
This should fix the issues people were reporting in #5888. I guess this is the part to fix for #5860.
Verified locally that the embed frameworks phase was added, and Xcode runs it.
> Added messages application to the list of targets that should have embed frameworks build phases

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
We re-run the profiler against our project and noticed two more big improvements in `pod install` times.
If you wanted to see how long a project with 10+ targets and 130 pods takes to integrate I've attached the generated log here. You might be able to pick other areas of improvements but we noticed again that `pod_target` could be caching some of its results again. 
I do not believe caching these could cause any harm or throw a `pod_target` out of sync.
[profile.zip](https://github.com/CocoaPods/CocoaPods/files/488807/profile.zip) (it might take a bit of time to render in Chrome :))
This dropped our `pod install` time from 1m 8s to about 48seconds.
> Cache result of include_in_build_config and inhibit_warnings

- CHANGELOG.md
- Rakefile
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
In most cases, I just switched to passing full paths. For the `realpath` function, I'm 99% we don't need it. In its script, it's used for `PODS_ROOT`, which is always a full path, and `RESOURCE_PATH`, which is checked early on and also set to a full path (relative to `PODS_ROOT`) if it's not one.
> Remove uses of shell cd

- spec/unit/installer/analyzer_spec.rb
The test suggests that the fixture is a non-git repo when in reality it is not. Seemingly, the `.git` file in there references a relative path, but newer versions of git seem to make it absolute when cloning the
fixtures. This results in the copied repo being treated as a git repo and the test failing. The fix just removes `.git` after copying, making the fixture an actual non-git repo :)
> Fix "does not update non-git repo" test

- CHANGELOG.md
- lib/cocoapods/command/lib/lint.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Default remains as `2.3`. `.swift-version` file is still supported to prevent users from needing to always pass the flag. The flag takes precedence over the file.
For future people viewing this PR:
`pod lib lint --swift-version=3.0`
or:
```
echo "3.0" > .swift-version
pod lib lint
```
`pod spec lint --swift-version=3.0`
or:
```
echo "3.0" > .swift-version
pod spec lint
```
> Allow passing --swift-version to pod spec/lib lint

- CHANGELOG.md
- lib/cocoapods/generator/header.rb
- lib/cocoapods/generator/prefix_header.rb
- spec/unit/generator/header_spec.rb
closes #5291 
This completes the pull request here (https://github.com/CocoaPods/CocoaPods/pull/5408) by fixing the tests.
Integration tests fail, though the DIFF looks correct. I am uncertain how to fix those but I think I've seen CocoaPods maintainers update these. Let me know!
> Wrap generated import headers using __OBJC__ for C only pods

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/target/aggregate_target_spec.rb
This PR adds XPC services to the list of project types where frameworks must be embedded in a host target.
References https://github.com/CocoaPods/Xcodeproj/pull/428
> Use host target for frameworks of XPC services

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Allow our trunk plugin's uploader to correctly understand whether or not swift was used, and which version was chosen for https://github.com/CocoaPods/cocoapods-trunk/pull/77
> Adds support in the validator for expressing what version of Swift was used

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
- spec/integration.rb
[Fix for issue 6052](https://github.com/CocoaPods/CocoaPods/issues/6052)
TARGETED_DEVICE_FAMILY will be 3) for tvOS.
Without this line we get the following error when running the '[CP] Copy Pods Resources' build phase on a tvOS framework target:
```
***-tvOS.storyboard: error: tvOS storyboards do not support target device type "mac".
```
I first tried replacing the `target-device` with `appletv` or `tvos` but then realized the correct device_target is in fact 'tv'
To make the tests pass the PR https://github.com/CocoaPods/cocoapods-integration-specs/pull/84 will have to be merged first.
> [CopyResourcesScript] add target_device 'tv' for tvOS

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
We were trying to read the `SWIFT_VERSION` that we generate for pod targets by mistake.
This fixes #6067
> Read the correct SWIFT_VERSION when generating target XCConfigs

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
This is the previous behavior for how we handled `EMBEDDED_CONTENT_CONTAINS_SWIFT`. I can't remember why I explicitly set the new one to NO. It's possible that it was related to an early Xcode beta issue, or I explicitly set it because that's what Xcode does when you apply the recommended build setting changes when updating to Xcode 8.
This fixes #6064.
> Don't explicitly set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to NO

- CHANGELOG.md
- lib/cocoapods/generator/header.rb
- spec/unit/generator/header_spec.rb
- spec/unit/generator/prefix_header_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Fixes #6024 
e.g.
```objc
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif
```
> Redefine FOUNDATION_EXPORT for C-only pods in umbrella header

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
closes #5375, #5409
Podspecs can now safely depend on this build setting whether they are consumed locally or not to adjust various settings such as `HEADER_SEARCH_PATHS`.
/cc @mrackwitz @chrisballinger 
/cc @jcanizales this fixes your issue and hack in https://github.com/grpc/grpc/blob/master/src/objective-c/examples/Sample/Podfile#L30-L48 if you have time can you try this change and see if it works for you? It certainly works for us.
> Generate a PODS_TARGET_SRCROOT build setting for every pod target

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
0d889c8 seems to have undone the escaped quotes, making them just regular bash quotes. This breaks app paths that have spaces in them.
This patch re-escapes the backslashes that escape the quotes in the generated bash (wow, that's a mouthful).
This tracks the fix for issue #6121
> Re-escaped backslashes in embed_frameworks generator

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
If Xcode target name contains whitespaces Create Symlinks to Header Folders build phase fails on Archiving macOS app.
Podfile to reproduce:
```ruby
target 'Test Project Name' do
use_frameworks!
pod 'Realm'
end
```
Error message on Archiving:
```
ln: Name/BuildProductsPath/Release/Realm/Realm.framework/Headers: No such file or directory
ln: Name/BuildProductsPath/Release/Realm/Realm.framework/PrivateHeaders: No such file or directory
```
Where
```
CONFIGURATION_BUILD_DIR="/Users/do/Library/Developer/Xcode/DerivedData/Test_Project_Name-fqaocpznfgakqffqdcohsxgjtdhz/Build/Intermediates/ArchiveIntermediates/Test Project Name/BuildProductsPath/Release/Realm"
```
> Escape spaces in CONFIGURATION_BUILD_DIR when creating header folders symlink

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
`pod spec lint` and `pod trunk push` are both failing for me with the following error:
```
CodeSign /tmp/xcode/DerivedData/App-ecacodmhenqbjqcvnllhxtofynly/Build/Products/Release/Siesta/Siesta.framework/Versions/A
cd /var/folders/ct/_03srt6h8xj44m00r6bfmd400000gn/T/CocoaPods/Lint/Pods
export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
Signing Identity:     "-"
/usr/bin/codesign --force --sign - --timestamp=none /tmp/xcode/DerivedData/App-ecacodmhenqbjqcvnllhxtofynly/Build/Products/Release/Siesta/Siesta.framework/Versions/A
/tmp/xcode/DerivedData/App-ecacodmhenqbjqcvnllhxtofynly/Build/Products/Release/Siesta/Siesta.framework/Versions/A: code object is not signed at all
In subcomponent: …
```
> Fix for lint codesign failure on macOS projects

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
🌈
This small change fixes an issue with `{target}-frameworks.sh`, wherein spaces in the target cause a `No such file or directory` error. The fix is simple: wrap `code_sign_if_enabled` in quotes. Works in my local env and hope it works in yours too :+1:
Fixes and closes CocoaPods/CocoaPods#6153.
> [Embed] Fix codesigning issues when targets have spaces

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
Fixes #6123 
I fixed `copy_embedded_target_pod_targets_to_host` to properly handle embedded targets that live in another project. I don't think this has worked properly on master. From what I can gather, the way that I originally wrote the test convinced me that this was working. My best guess is that the version of this that I had people asking about this test (and worked) changed during the PR and didn't end up being exactly what made it into master. This fixes the test (verified it failed before), and then it fixes `copy_embedded_target_pod_targets_to_host`.
> Fix cross-project framework dependencies

- lib/cocoapods/command/update.rb
this doesn't need a changelog entry as the feature hasn't shipped yet.
> [Command::Update] Update docs for --sources

- CHANGELOG.md
- lib/cocoapods/installer/analyzer/target_inspector.rb
- spec/unit/installer/analyzer/target_inspector_spec.rb
closes #6191 
/cc @justinseanmartin @benasher44 
Output looks like:
```
There may only be up to 1 unique SWIFT_VERSION per target. Found target(s) with multiple Swift versions:
Target: Swift 2.3
Target2: Swift 3.0
```
> Output Swift targets when multiple versions of Swift are detected.

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
This fixes #6173. Xcode should warn you about these issues, so trying to maintain code that replicates this at `pod install` time seems like less of a great idea now. `use_frameworks!` issues are still ones that would be fixed with your CP setup though, so that error will stay.
> Removed extension integration errors about mismatched Swift version / platform

- CHANGELOG.md
- lib/cocoapods/command/repo/add.rb
- lib/cocoapods/command/setup.rb
Git added a `--progress` option in 1.7.0 (earliest tag containing
https://github.com/git/git/commit/5a518ad4679c91f0d0afd38fcc3cbf04e8699c46).
This adds an option to Repo::Add to pass this to git, and makes
Setup pass it by default.
closes https://github.com/CocoaPods/CocoaPods/pull/5297
> [Repo::Add] Add --progress option to show git progress

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
closes #5499 
/cc @hborders @DanToml
> Use ${SRCROOT} rather than ${PODS_ROOT} in the generated manifest lock

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
This fixes a few things:
* Search paths will now properly be added even for targets with vendored static frameworks or libraries (regression from https://github.com/CocoaPods/CocoaPods/pull/5514)
* Just like static frameworks, static libraries will now **not** be linked to targets that use `inherit! search_paths` (from https://github.com/CocoaPods/CocoaPods/issues/6065#issuecomment-276815528)
* Fixes an issue where if a target with `inherit! search_paths` explicitly defines a pod that brings in a static framework or library will not have its `other_ldflags` properly wired up, now it will.
* Also fixes an issue where transitive static dependencies would still get linked when they should not be.
/cc @plu @benasher44 @DanToml @segiddins
> Fix integration with vendored static frameworks and libraries

- CHANGELOG.md
- lib/cocoapods/sandbox/file_accessor.rb
- spec/unit/sandbox/file_accessor_spec.rb
This caches the results of MachO.open(...).dylib?
For large projects with hundreds of dependencies, this becomes quite an expensive operation.
> Cache results of dynamic_binary?

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer/target_inspector.rb
- spec/unit/installer/analyzer/target_inspector_spec.rb
- spec/unit/installer_spec.rb
closes #6465
Not in love with this fix but this is an edge case overall. These things must be true in order to crash:
- The user has specified a pod at the top level, not within a specific target.
- The invisible 'Pods' target has no platform set so it accepts all pods including transitive deps.
- The platform for the users target in the podfile is automatically inferred or is set explicitly to a version that does not support a pod, possibly due to the pod being with a subspec.
With this change the user will now be warned that the platform was automatically inferred and also provide an informative message that the pod could not be installed.
Cases to repro:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'Lock', '~> 1.28'
target 'MyOSXApp' do
platform :osx, …
```
> Do not crash when attempting to install pod with no supported targets

- CHANGELOG.md
- Gemfile.lock
It was locked to 3.1.1 before, which appears to have been removed from rubygems.org. This updates it to 3.1.2. The diff looks like mostly travis and readme changes in their repo: https://github.com/kigster/colored2/compare/v3.1.1...v3.1.2.
> Updated colored2 gem

- CHANGELOG.md
- lib/cocoapods/installer/installation_options.rb
- lib/cocoapods/resolver.rb
- lib/cocoapods/resolver/lazy_specification.rb
- spec/unit/installer/installation_options_spec.rb
We have 100+ pods where we publish both as sources and as binary. Sometimes these warnings can become extremely long during `pod install`. 
Resolving this issue also requires to re-enter these pods in the `Podfile` and provide an explicit `:source` to silence this warning. This in turn forces the pods to be linked to a target even though they do not necessarily have to.
The best (long term solution) is to provide:
```ruby
source 'https://github.com/CocoaPods/Specs' do
pod ...
pod ...
end
```
But this option here is a good balance to prevent the warning from happening. Please note the default still is to warn so this shouldn't affect anyone.
Usage:
```ruby
install! 'cocoapods', warn_for_multiple_pod_sources: false
```
> Provide installation option to disable multiple pod sources warnings

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
@segiddins this regressed from https://github.com/CocoaPods/CocoaPods/issues/5670. When linting pre-built pods then there is no xcscheme generated to share.
Caught in an internal project of ours and verified this fixes it. Also added a test.
> Only share pod target xcscheme if present during validation.

- CHANGELOG.md
- lib/cocoapods/command/install.rb
- lib/cocoapods/resolver.rb
- spec/unit/resolver_spec.rb
Hi,
As part of #6033, this returns a different exit code when spec not found (i.e. master repo out-dated).
I couldn't find any other examples in the project of exit codes, so I'm not sure if we have any convention to follow on this, do you have any hint?
I have few other questions:
Should we document exit codes somewhere?
Is having a NoSpecFound class the right approach, if so where is the right place? Or is good enough to just set @exit_status?
> Return different exit status (31) when spec not found

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
This fixes #6259. This adds xcdatamodeld files to the sources build phases, so that Xcode-generated headers (categories that add nice accessors for the models) can be built in time to be used in the pod. This is not enabled for resource bundles, since these kinds of models don't seem to build properly (error) in any build phase for resource bundles.
> Added special handling for xcdatamodeld resources

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/resolver.rb
- spec/unit/resolver_spec.rb
Hi,
As part of #6033, this improves the error message when specs not found (i.e. source repo out-dated), and there is also a small fix in the tests.
Another thought, I think it would be nice to hide the message about "try `pod install --repo-update`" if the error is raised while executing that command, since it means that user have updated the repos but the error is probably one of the other two (mistyped or no source repo).
Should I change the analyser init to pass if it's called within a repo update? Or do you have any other ideas on how I can access that property?
> [Resolver] Improve error message when specs not found

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/fixtures/SampleProject/Sample Lib/Sample Lib.xcodeproj/project.pbxproj
- spec/fixtures/SampleProject/SampleProject.xcodeproj/project.pbxproj
- spec/unit/installer/analyzer_spec.rb
- spec/unit/target/aggregate_target_spec.rb
This fixes #5830 and #6306. The scenario this fixes is when you're installing pods into a static library and an app, and the static library is a sub project of the app project.
I have a local test project that I'll push to github shortly, but I have this working locally in the test project. I just want to make sure there aren't any further changes that need to be made for dynamic libraries before I push it (so far it seems like those just work).
Other minor changes:
- Renamed Sample Framework to SampleFramework in the specs fixtures, since the former isn't a valid C99 target name.
- Updated the Sample Lib project to include its SampleLib static lib subproject target as a dependency
> Make analyzer consider static libs as dependent targets

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
> Fix generating LD_RUNPATH_SEARCH_PATHS without use_frameworks! but consuming a vendored dynamic artifact. 

- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
Fixed specs for the updated build settings in the latest Xcodeproj update. (CocoaPods/Xcodeproj#468)
Travis CI got broken by 5d471d6e1a9290b8d3c74cdc726c3493673c33d9
(Job log: https://travis-ci.org/CocoaPods/CocoaPods/jobs/217236031)
> [Spec] Fix for updated build settings

- Gemfile.lock
- cocoapods.gemspec
Hi, author of ruby-macho here.
ruby-macho 1.0 and above bring substantial performance improvements over pre-1.0 versions.
The methods that CocoaPods uses also haven't changed, so there's no compatibility concern.
Best,
William Woodruff
> [Gemspec] Bump ruby-macho to '~ 1.1'

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
- spec/unit/generator/embed_frameworks_script_spec.rb
Part of #1698 
This adds an `install_dsym` command to the shell script but only for vendored frameworks. Xcode automatically does the right thing if the pod is not a vendored framework but it's built from source.
/cc @alloy @benasher44 @segiddins
> Copy dSYM for vendored frameworks

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/project.rb
This will make sure that pod defined values for `SWIFT_ACTIVE_COMPILATION_CONDITIONS[debug]` are correctly inherited. This got broken with the release of Xcodeproj 1.4.3, where Apple's default `DEBUG` value overwrote any values. 
Adding `$(inherited)` to both `pod_xcconfig.rb` and `pod_target_installer.rb` seems essential for the `DEBUG` value not to override everything. Removing it from either one removes `$(inherited)` in the end result. 
Fixes #6625
> Inherit pod defined values for SWIFT_ACTIVE_COMPILATION_CONDITIONS

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/generator/embed_frameworks_script.rb
We often do incremental builds, and have noticed that the pods resources are synced without cleaning the destination. Often this is fine, but in our use case, it's important that only the current set of files are present.
`--delete                delete extraneous files from dest dirs`
Looks scary maybe, but should be exactly the same as doing a clean build, which is what your CI is hopefully doing anyway.
> Delete extraneous files in rsync destination

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
Fixes #6673.
In 1.2.1, I added support for static library targets in your Podfile, similar to how it works for integrating framework targets. However, I forgot the piece that ensures that working on a static lib-only project still works (i.e. `pod install` works). Now, `pod install` generates the same warning for static lib-only projects as it does for frameworks-only projects.
> Fix pod install error when working on a static lib project

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
This fixes #6154.
It avoids creating or updating the default master specs repo while executing `pod lib lint` if there aren't any dependency.
> Avoid unneeded master specs cloning for pod lib lint

- .github/stale.yml
This was a typo, and anything we tag as an enhancement is probably something
we should manually triage.
> [Probot] Fix enchancement pinner

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/xcode/target_validator.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer/xcode/target_validator_spec.rb
The previous check does not make sense when consuming pods that do not have any Swift sources in them.
We have a local project I tried this on and it worked just fine.
Existing specs pass too and updated one.
> Only check for valid Swift version for pod targets that use Swift

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Updates the check for the .swift-version file to only perform this check if the targets include swift sources. 
Addresses #6742
>  Updates how .swift-version file is validated to prevent it from being needed in Objective-C pods

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
For every binary static library pod target we have we noticed `$(inherited)` is added.
*Before*
```
$(inherited) myLib1/myLib1 $(inherited) myLib2/myLib2
```
*After*
```
$(inherited) myLib1/myLib1 myLib2/myLib2
```
This is now fixed.
> Stop adding `$(inherited)` for every static library linked

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
As of CP 1.3.0.beta.1 this method would add 7-10 seconds to out pod install time.
This adds a cache to the result but also prevents a number of calls to this method if they are not needed by short circuiting earlier.
There are no tests for this PR because the logic is the same. I hot patched CocoaPods for us and the `pod install` now remains the same.
> Use a cache when figuring out if a pod target is test only

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
closes https://github.com/CocoaPods/CocoaPods/issues/6774
This might require integration specs update.
> `VALID_ARCHS` does not include the right archs to strip for a framework so use `ARCHS` instead

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/generator/embed_frameworks_script_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/target/aggregate_target_spec.rb
This adds tests and cleans up a bit the method for returning all framework input and output paths. It was getting hard to follow but I think now its much better.
> Simplify logic around framework input and output paths

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
predates https://github.com/CocoaPods/CocoaPods/pull/6828
If a pre-built binary pod provides test specs then its dependencies were not being added.
The same goes for resource bundles which are now handled as well.
This is required to complete shipping tests specs for 1.3.0.
> Ensure resource bundle and test dependencies are set for test native targets

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/project.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
- spec/unit/project_spec.rb
Closes #4719
This will leave source files and directories at the same level as "Supporting Files" and "Resources", which may or may not have been the desired effect.
Depends on https://github.com/CocoaPods/cocoapods-integration-specs/pull/116
> Truncate shared parent folders in Development Pods to the nearest ancestor

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/generator/embed_frameworks_script.rb
🌈
We started recently seeing two Embed Frameworks scripts failing with something along the following lines:
> rsync: stat "...DERIVED_DATA.../InternalFramework.framework.dSYM/Contents/Resources/DWARF/.InternalFramework.1cYxXV" failed: No such file or directory (2)
When I look a little higher in one of the two script phase logs, I find this:
> deleting InternalFramework.framework.dSYM/Contents/Resources/DWARF/.InternalFramework.1cYxXV
It turns out that there is a remote chance of a collision when two targets both integrate the same library dependency and happen to overlap in timing of then the rsync's for those libraries are being performed. 
We just moved an extra dependency into our app this morning which apparently started hitting this condition surprisingly often (~25% of the time). …
> Protect rsync tmp files from being deleted if two targets sync at the same time

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- lib/cocoapods/sandbox.rb
- spec/unit/installer_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/3991 and completes/supersedes https://github.com/CocoaPods/CocoaPods/pull/6496
This is a huge performance boost for projects that frequently perform `pod install` and have to re-built because Xcode "thinks" the `.xcconfig` files or `.pch` or any other file for that matter is "dirty" and forces a re build.
We should not wait for Xcode to do the right thing and instead we should work around it to speed up all of the iOS ecosystem.
I tried this in a medium sized project of 50+ pods and after `pod install` the build succeeded almost instantly (including the caching of input/output paths for the shell scripts!).
I *highly* recommend we land this and I will update it based on feedback.
> Do not re-write generated files that have not changed

- spec/unit/external_sources/podspec_source_spec.rb
This test was passing when online due to the actual request being a 404, but
it was not being stubbed by webmock because we neer enabled it
> [PodspecSource] Enable webmock in network test

- CHANGELOG.md
- lib/cocoapods/installer/xcode/target_validator.rb
- spec/unit/installer/xcode/target_validator_spec.rb
closes #6711
A Pod target could require multiple subspecs, but the product_module_name can
be specified only at the root spec.
> Remove duplicate framework names

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Regressed from https://github.com/CocoaPods/CocoaPods/pull/6576/files#diff-c40545c38369a7fb9be6a8849d065059R32
> Ensure source urls are set when spec has subspecs with dependencies

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/pods_project_integrator/pod_target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
if PodA depends on PodB which brings in a vendored `.a` or `.framework` then the test target fails to link this vendored library or framework.
Further more all input and output paths for the scripts did not take account transitive dependencies.
This PR fixes both of those issues.
> Ensure transitive dependencies are linked to test targets

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- cocoapods.gemspec
- examples/AFNetworking Example/AFNetworking Mac Example.xcodeproj/project.pbxproj
- examples/AFNetworking Example/AFNetworking iOS Example.xcodeproj/project.pbxproj
- lib/cocoapods/resolver.rb
- spec/unit/resolver_spec.rb
This updates the resolver to handle some changes in Molinillo in 0.6, and also transitions CocoaPods to printing out tree-style conflict messages.
> Update Molinillo to 0.6

- Gemfile.lock
- cocoapods.gemspec
trivial bump, 0.6.1 has a slightly improved algorithm that fixes a 0.6.0 regression
> [Gemspec] Bump Molinillo to `~> 0.6.1`

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- lib/cocoapods/installer/xcode/target_validator.rb
- lib/cocoapods/target.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
- spec/unit/installer/xcode/target_validator_spec.rb
Address #6772 
https://github.com/CocoaPods/Core/pull/386 adds the static_framework podspec attribute.
This PR uses that attribute to build a source pod into a static library framework. All dependents and dependencies should interact with the source pod just as if it were a vendored_framework static library framework CocoaPod.
> Add support for source static library frameworks

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
While working on migrating Firebase to static frameworks, I discovered that I didn't set up Private Header support correctly for static frameworks.  Here it is.
> Add Private Header support to static frameworks

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
The xcconfig merge boolean checking wasn't tight enough and causing two _GCC_PREPROCESSOR_DEFINITIONS_ that both had a substring "NO" to cause it to be treated as a boolean and failing to do the merge after generating the warning. 
See the new unit test for an example.
> Fix xcconfig boolean merging

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
When multiple build targets in a workspace have dependencies on different subspecs of another pod, builds can fail if the subset build has already been done and the framework search path occurs first on the command line.
This PR fixes the issue by removing the redundant subset subspecs from FRAMEWORK_SEARCH_PATHS. See the fixed issue #6967 for more details and a reproducible example.
> Filter out subset dependent targets from FRAMEWORK_SEARCH_PATHS

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
- Include source static framework library dependencies in aggregate target builds
- Set -framework option for dependent targets in aggregate target builds when there are source static frameworks
I suspect that the -framework option change should be made more broadly and that -framework should be set in concert with updating the FRAMEWORK_SEARCH_PATH, but I'm making the conservative change of only impacting projects that include source static frameworks.
In addition to the unit tests, these changes have been tested with [Firebase](https://github.com/firebase/firebase-ios-sdk/tree/pb-future).
> Fix OTHER_LDFLAGS for projects including source static frameworks

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
🌈
Resource bundles can be processed multiple times across different pod targets with the same spec activated, but different subspec dependencies.
Example:
Spec/Subspec1 has a resource bundle SubspecResources
Spec/Subspec2 has a dependency on Spec/Subspec1
Target1 depends on Spec/Subspec1
Target2 depends on Spec/Subspec2 (which activates Spec/Subspec1 as a dependency)
Both Target1 & Target2 try to integrate SubspecResources
Tested with and without the change and verified that the count of `FooResources.bundle` was 2 without the fix. This causes warnings to appear when using deterministic UUIDs for duplicate references in a valid scenario.
> Ensure a unique ID is generated for each resource bundle

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
For targets that  _inherit! :search_paths_, propagate HEADER_SEARCH_PATHS from _user_target_xcconfig_, in addition to propagating the FRAMEWORK_SEARCH_PATHS.
This fixes #6891 and https://github.com/firebase/firebase-ios-sdk/issues/58
> Propagate HEADER_SEARCH_PATHS settings from search paths

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
🌈
It turns out that we need to only sign iOS XCTest bundles for them to be launched within the simulator, but not OSX ones being run on the local machine. I've verified now that both iOS and OSX test bundles appear to work correctly in the same conditions.
This regression was introduced by #7013.
> Don't codesign :osx test targets

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
Closes #6979
I was only able to test with my own project which reproduced the issue, but am unsure about the originally submitted bug.
I was comparing the entire path as a string instead of the components, which was what was originally intended. I added a test case for it to (hopefully) prevent a future regression.
> Fix common paths sometimes calculating incorrectly

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer_spec.rb
Closes #5306
Noticed this issue still open so thought I'd take a stab at it. I am interested if this is still a desired change, as it could possibly break some projects that were relying on master being included automatically
> Do not force include master spec repo if plugin sources are provided

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/pod_variant.rb
- spec/unit/installer/analyzer/pod_variant_set_spec.rb
- spec/unit/installer/analyzer/pod_variant_spec.rb
- spec/unit/installer/analyzer_spec.rb
Given the following scenario:
```ruby
target 'MyApp'
pod 'PodA', :testspecs => ['Tests']
end
target 'MyApp2'
pod 'PodA'
end
```
This generates two variants of `PodA` one called `PodA` and one more called `PodA.root` but with the exact same sources. This is because testspecs were taken into consideration for the uniqueness of a `pod_variant.rb` within `analyzer.rb`
This is no longer the case. The number of test specs asked should not matter for the generation of a pod variant. Pod variants should vary across platform, subspecs and whether they require frameworks or not.
Tase case and change depends on https://github.com/CocoaPods/cocoapods-test-specs/pull/1
> Deduplicate test specs correctly from pod variants and targets

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
- spec/unit/target/pod_target_spec.rb
This is consistent with everything else that uses variables by cocoapods but also fixes an issue where sometimes Xcode stomps the input paths due to the lack of `{}` around the env variable.
> Wrap `$PODS_CONFIGURATION_BUILD_DIR` and `$PODS_BUILD_DIR` with curlies

- CHANGELOG.md
- lib/cocoapods/target.rb
- spec/fixtures/matryoshka/matryoshka.podspec
- spec/unit/installer/xcode/target_validator_spec.rb
podspecs with subspecs that included the `static_framework` attribute were generating transitive errors even though they would build correctly.
This PR fixes that issue by checking the static_framework attribute from the outermost spec instead of the subspec itself.
The issue was reported at https://github.com/CocoaPods/CocoaPods/pull/6811#issuecomment-331628583.
> Build subspecs in static frameworks without error

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
See also https://github.com/CocoaPods/Core/pull/406.
Prevent pch file generation with the skip_pch podspec attribute.
Address #1691 and #1746. More context at https://stackoverflow.com/questions/44401464/is-there-a-way-to-disable-the-default-pch-file-in-cocoapods
> Add support for preventing pch file generation

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
closes #7081, #7047, #7084 
When `pods_project_generator.rb` calls for `prepare` and initializes a new `project.rb` we set the `SYMROOT` automatically to all build configurations. However, at that time the user specified configs have not been set and miss this setting.
We now re-apply the `SYMROOT` setting after we've added all build configurations (including the user ones).
> Ensure `SYMROOT` is properly set for all user configurations

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
I followed https://www.justinweiss.com/articles/4-simple-memoization-patterns-in-ruby-and-one-gem/ for memoizing with parameters which does not seem to work.
I didn't want to spend enough time so I went back to a more "standard" way. 
No need for specs since this is already covered and the existing tests still pass.
> Fix framework and resources paths caching

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/pod_target_spec.rb
Fixes two issues.
1) A podspec without any sources would not even add a target even if it had a script phase or not. Now this is fixed.
2) A pod target integrator was not being created unless the pod target had test specs in it. This is a bug since we still need to integrate targets that have script phases.
Both issues fixed.
> Build pod targets with script phases and integrate them properly

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
`validator.rb` sets `CODE_SIGN_IDENTITY` to nothing when lint occurs. This matches this case and fixes issues with code signing app hosts or macOS bundles.
> Do not set a `CODE_SIGN_IDENTITY` for macOS app hosts or xctest bundles

- CHANGELOG.md
- lib/cocoapods/generator/app_target_helper.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
closes #7121, fixes regression from https://github.com/CocoaPods/CocoaPods/pull/6971 in CocoaPods 1.4.0.beta.1
/cc @thomasvl The validator will only output this message if the user has not provided a swift version via a parameter or via a `.swift-version` file. 
This is how it looks now:
```
-> CannonPodder (1.0.5)
- WARN  | [iOS] swift_version: The validator for Swift projects used Swift 3.0 by default 
because no Swift version was specified. If you want to use a different version of Swift during 
validation, then either use the `--swift-version` parameter or use a `.swift-version` 
file to set the version of Swift to use for your Pod. For example to use Swift 2.3, run: 
`echo "2.3" > .swift-version`
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
```
> Better warning message for which Swift version was used during validation

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
Fixes #7117 
This PR fixes/implements two issues:
1. When I implemented static frameworks, I made the incorrect assumption that static_frameworks don't need to worry about build dependencies because they don't link. That's not the case when a static_framework depends upon a Swift CocoaPod where it needs its bridging header to be built. This is fixed by the conditional change in `lib/cocoapods/installer/xcode/pods_project_generator.rb`.
2. CocoaPods did not support importing modules from vendored frameworks. While this is annoying for Objective C, it's a show stopper for a Swift CocoaPod depending on a vendored framework.  The vendored framework modules were not being added to FRAMEWORK_SEARCH_PATHS for pod builds that depended upon them. I added a call in …
> Fix static_framework Swift pod deps and pod access to dep vendored modules

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Supersedes https://github.com/CocoaPods/CocoaPods/pull/7109
On Xcode 9 ^^^
> Update default Swift version to 3.2 for validation

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Fix #7140
To access public classes from Swift-built static frameworks, the .swiftmodule must be included into the constructed framework. This PR adds a copy command (modified to be silent when there is no swiftmodule) to the Setup Static Framework build phase.
> Copy .swiftmodule to enable access to Swift static frameworks

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Fix #7158 
Unlike in development and release builds, in archive builds ${TARGET_BUILD_DIR} is different from ${BUILT_PRODUCTS_DIR}.
This PR insures that static framework headers get included in ${BUILT_PRODUCTS_DIR} in an archive build.
> Fix archiving apps with static frameworks

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
After upgrading to 1.4.0.beta.2 we noticed a race condition regarding dSYM architecture stripping. This is because multiple targets can execute the "Embed Pods Framework" script phase in parallel and strip the same dSYM file which can yield to a race and error.
This prevents that by moving the file into the intermediates folder of the scoped target, stripping it and then moving it to the final destination.
> Prevent multiple script phases from stripping vendored dSYM

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7170
Test native targets actually build and link multiple dependencies. If any of these dependencies require Swift, we should be setting the test native target language to Swift.
> Set language to Swift for test native targets if any dependencies use Swift

- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/7176
> Prevent passing empty string to git when running pod repo update --silent

- CHANGELOG.md
- lib/cocoapods/installer.rb
Given a pod that supports multiple platforms the warning message would appear twice like this:
```
[!] CannonPodder has added 1 script phase. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.
[!] CannonPodder has added 1 script phase. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.
```
This change groups the message into a single message:
```
[!] CannonPodder has added 2 script phases. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.
```
> Do not display script phases warnings multiple times per platform

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Fix #4496 and https://github.com/grpc/grpc/issues/12081
For static library pods, Public and Private headers are copied to  `${PODS_ROOT}/Headers/Public/[pod]/` and  `${PODS_ROOT}/Headers/Private/[pod]/` and the dependency search paths set appropriately.
The headers were also being set in an Xcode build phase and marked as `Public` or `Private`. This redundancy is usually harmless since the headers would already be found at previous path. However, if there are multiple same-named at different paths, build warnings will be generated, since the Xcode build phase flattens the path.
This PR addresses that by making all static library pod headers `Project`.
More analysis at #4496 and I've verified this fixes https://github.com/grpc/grpc/issues/12081
> Static library headers should all be Project

- CHANGELOG.md
- lib/cocoapods/command/outdated.rb
- spec/functional/command/outdated_spec.rb
This adds color to the output of `pod outdated` to make it easier to read. 
The version numbers are highlighted in one of the following colors:
* **green** if the latest available update is compatible with the specified version in the Podfile
* **yellow** if there is an update available and allowed by the specified version in the Podfile, but the latest available update is *not* compatible
* **red** if the update is not compatible with the version specified in the Podfile.
Here is an example how that would look like:
> Add color indication to output of "pod outdated"

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
This resolves [#6936](https://github.com/CocoaPods/CocoaPods/issues/6936) by listing all the bundles being copied as output paths, per suggestion from @bjhomer.
@bjhomer's suggestion is [here](https://github.com/CocoaPods/CocoaPods/issues/6936#issuecomment-341922431).
> Add copied resources' paths to "Copy Pods Resources" output file list 

- CHANGELOG.md
- lib/cocoapods/validator.rb
/cc @emuller
Under normal circumstances (non lint/validator) the swift version is set for test native targets because the native target of the user often has the Swift version set but during validation the target definition and targets are generated.
To test use CocoaPods 1.4.0.beta.2 on https://github.com/square/Valet project on branch `emuller+dnkoutso/test_specs`. This came up when we were adding support for test specs into that project.
> Set `SWIFT_VERSION` to test native targets during validation

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
_Copy resource_ and _embed frameworks_ scripts of a test target now contain all the target's configurations instead of just the **Debug** one. 
This resolves #7012
> Create scripts for every test target's configuration

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Related to https://github.com/CocoaPods/CocoaPods/pull/7249, fixes https://github.com/CocoaPods/CocoaPods/issues/7238
I'll add tests, once I get the ok that this is the right location and the right approach. For now I used the `error` method to fail the validation. I believe that it's the right thing to do, there is no good excuse to transfer executable over non-encrypted protocols, however I do understand that this might throw off some SDK providers, and them being overwhelmed when they quickly need to push an update.
You all have more context around what the users are like, and if they have a way to work around this, just let me know what you're deciding on :+1:
> Show warning when SDK provider tries to push a version with an unencrypted HTTP source

- CHANGELOG.md
- lib/cocoapods/installer/xcode/target_validator.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/xcode/target_validator_spec.rb
If a pod specifies `swift_version` we should not error out when it is integrated with 2 different targets that have a different Swift version.
> Allow installation of a pod with its own Swift version on multiple targets

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/project.rb
- spec/unit/project_spec.rb
This will set the syntax to ruby only when the file extension is `.podspec`, not `.podspec.json` or `.json`
Refer to #7093
> Set development pods' podspecs syntax to Ruby when appropriate

- CHANGELOG.md
- lib/cocoapods/installer/pod_source_installer.rb
- spec/unit/installer/pod_source_installer_spec.rb
This PR addresses the first half of #7238, related to #7250 
Via https://github.com/CocoaPods/CocoaPods/pull/7249
> Show warning when Pod source uses unencrypted HTTP

- CHANGELOG.md
- lib/cocoapods/resolver.rb
- spec/unit/resolver_spec.rb
This resolves a (potential) ordering bug due to pre-releases.
In #possibility_versions_for_root_name, we check whether dependencies on a pod are pre-release or external source, and if so allow pre-releases. It is crucial, therefore, that any external source dependencies have been addressed before any transitive source without the external source, so that pre-releases are (properly) allowed.
> [Resolver] Sort external source dependencies first

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
Previously we only logged the target name if the target missing a host
wasn't a framework target. Logging it for framework targets as well can
be useful for debugging Podfile configuration issues.
> Log target names missing host for libraries

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- lib/cocoapods/sandbox/headers_store.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/sandbox/headers_store_spec.rb
- spec/unit/target/pod_target_spec.rb
This is meant to go for 1.5.0. Pod targets will not have access to the full of header search paths in their generated xcconfig, instead only the header search paths for their dependent targets.
This also correctly handles header search paths for test xcconfigs.
> Set direct and transitive dependency header search paths for pod targets

- CHANGELOG.md
- lib/cocoapods/validator.rb
closes #7336 
If `--skip-import-validation` is used we never invoke the `App` scheme since it will avoid linking the pod and during this case we choose the pods scheme during validation in order to just build it.
However, if the pod has no sources then there is no scheme to invoke which is the edge case fixed here.
> Do not attempt compilation for pods with no sources and skipping import validation

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
Fixes a case in which a pod input/output path was added but then it does not get removed if the input/output paths are now empty.
This can also occur if someone uses `use_frameworks!` and switches out to static libs.
> Always update input/output paths even if they are empty

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/analysis_result.rb
- lib/cocoapods/resolver.rb
- lib/cocoapods/resolver/lazy_specification.rb
- lib/cocoapods/user_interface/error_report.rb
- spec/functional/command/update_spec.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer_spec.rb
Needs some polish & docs & CHANGELOG, but I think this is a good start!
Depends upon https://github.com/CocoaPods/Core/pull/421
This way, we can let users know when a pod has changed sources (and inspecting the lockfile will tell you which source every spec is coming from!)
> Store spec repos in the Lockfile

- CHANGELOG.md
- lib/cocoapods/installer/xcode/target_validator.rb
- spec/fixtures/static-matryoshka/matryoshka.podspec
- spec/unit/installer/xcode/target_validator_spec.rb
Generate an error for transitive dependencies from dynamic libraries to static frameworks.
Close #7352
> Better static frameworks transitive dependency error checking

- CHANGELOG.md
- lib/cocoapods/generator/acknowledgements.rb
- lib/cocoapods/sandbox/file_accessor.rb
- spec/unit/sandbox/file_accessor_spec.rb
Closes #7377 
@dnkoutso I double checked the other files and it seems the license file is the only one with the problem, due to the way it checks the Podspec and falls back to a glob pattern
> Warn instead of throwing an exception when dev pod's license file is missing

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/integration.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
This changes the project integrator to only add build phases to the
user's project if there are resources of frameworks that will be copied
in that phase.
> Only add resources and frameworks build phase when needed

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/sandbox.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
Trivial changes, hopefully they'll cut down on some spurious CI failures around null bytes in `Pathname.new`
> [Sandbox] Clean up usage of #local?

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/generator/embed_frameworks_script.rb
This adds `set -u` to both the frameworks and resources copy shell
scripts. This means that if the scripts attempt to reference any
variable that is undefined, they will fail.
> Add set -u to frameworks and resources copy scripts

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb
- lib/cocoapods/resolver.rb
This PR preserves the `external_source` attribute on dependencies generated by the locking dependency analyzer, which ensures the resolver won't complain about pre-release versions for "locked" development pods.
cc @justinseanmartin
> Preserve external sources on locked dependencies in the resolver

- CHANGELOG.md
- lib/cocoapods/command/outdated.rb
- spec/functional/command/outdated_spec.rb
This is an improvement for colorblind users who can not differentiate between green and yellow.
Refs #7372 
As discussed in #7372 there might be a more comprehensive solution in the future. 
🌈
> Change colorscheme of `pod outdated` from red-yellow-green to red-blue-green

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/sandbox.rb
- lib/cocoapods/sandbox/headers_store.rb
- lib/cocoapods/target/pod_target.rb
- spec/integration.rb
- spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
- spec/unit/sandbox/headers_store_spec.rb
- spec/unit/target/pod_target_spec.rb
- Assuming `PodA`, `PodB` and `PodC` in a project.
- Assuming `PodA` depends only on `PodB` but **not** on `PodC`
Header search paths for `PodA`:
_before_ (<= 1.4, a.k.a today)
```
${PODS_ROOT}/Headers/Private
${PODS_ROOT}/Headers/Public
${PODS_ROOT}/Headers/Private/PodA
${PODS_ROOT}/Headers/Public/PodA
${PODS_ROOT}/Headers/Public/PodB
${PODS_ROOT}/Headers/Public/PodC
```
Notice that root `Public` folder but also that `PodC` is included in the pod's header search paths despite the fact that `PodA` does not depend on `PodC`.
_after_ (> 1.5)
```
${PODS_ROOT}/Headers/Private/PodA
${PODS_ROOT}/Headers/Public/PodA
${PODS_ROOT}/Headers/Public/PodA/PodA
${PODS_ROOT}/Headers/Public/PodB
${PODS_ROOT}/Headers/Public/PodB/PodB
```
Notice that `PodC` is correctly not included (due to …
> Add support for modular header search paths, include "legacy" support

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/hooks_manager_spec.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
This way, vendored frameworks integrated into static library aggregate targets can, e.g., use module maps.
> Use FRAMEWORK_SEARCH_PATHS to discover headers of vendored frameworks

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/target/pod_target_spec.rb
Turns out that https://github.com/CocoaPods/CocoaPods/pull/7116 and https://github.com/CocoaPods/CocoaPods/pull/7412 together are breaking legacy header search paths.
The first change removed all header search paths for dependent targets *but* kept the root `Public` folder which allowed things to continue to work.
However, with #7412 we removed the `Public` root folder and this will cause crashes to entire world.
This PR fixes this.
> Fix legacy header search paths

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/sandbox/path_list.rb
This PR dramatically improves `pod install` performance for pod specs using exact file path lists for file attributes rather than glob patterns.
- `FileReferencesInstaller` was reading file system from scratch using `read_file_system` multiple times for a `PathList` object if multiple file accessors are using that same `PathList` object. This is a common case for development pods having several subspecs which are independently added into a `Podfile`.
Now, file system will be read only once for each `PathList` object in `refresh_file_accessors` method.
- When `PathList.relative_glob` method runs, all string objects in `patterns` argument are regarded as glob patterns and `File.fnmatch` runs for each `(path_list_file, pattern)` pairs, which has complexity O(m*n). 
Now, we calculate the set …
> Improve `pod install` performance for pods with exact file paths rather than glob patterns

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Depends on https://github.com/CocoaPods/Core/pull/434
Sample output for when a source changes:
```
Fetching podspec for `CannonPodder` from `/Users/dimitris/Development/ios/cannonpodder/CannonPodder.podspec`
Downloading dependencies
Using CannonPodder (1.0.6)
Installing SamplePod 2.0.0 (source changed to `some-other-repo`)
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
```
> Display a message when a pods source has changed during installation

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
It's a bit tough to prepare an example project for this, as you need a project with valid code signing settings to reproduce this, but I'm happy to send one if you need it.
CocoaPods 1.3.1 sets the value of `PROVISIONING_PROFILE_SPECIFIER` to `NO_SIGNING/` which breaks the archiving action on Xcode 9 (but also believe it happens in the latest versions of Xcode 8, as some users reported below) using CODE_SIGN_IDENTITY environment variable.
This is how my build settings look like, automatic code signing is disabled.
```
//Config.release.xcconfig
#include "Pods/Target Support Files/Pods-Piggy/Pods-Piggy.release.xcconfig"
DEVELOPMENT_TEAM = TEAM_ID
PRODUCT_BUNDLE_IDENTIFIER = com.company.app
PROVISIONING_PROFILE_SPECIFIER = My Provisioning profile
```
Some logs running the following command: …
> Remove bogus PROVISIONING_PROFILE_SPECIFIER value from Pods project

- CHANGELOG.md
- lib/cocoapods/sandbox/path_list.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/sandbox/path_list_spec.rb
Currently, symlinks are not followed when creating the absolute path in PathList.glob. This means that when an actually absolute path is compared with the symlinked path, it might not compare as equal even it if should. This changes that so that glob actually returns the absolute path (following symlinks).
Fixes #7463.
FYI - I ran spec in CocoaPods and fixed the errors that caused, but since I was not able to build in Rainforest (I opened a couple bugs and a thread in the mailing list about that), I am not able to run rake spec there as the development guidelines ask. I'd be open to doing that if I can get some guidance on how to actually get the rainforest to work.
> Actually return absolute paths from glob

- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/sandbox/headers_store.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
- spec/unit/sandbox/headers_store_spec.rb
- spec/unit/target/pod_target_spec.rb
Needs update on integration specs
> Revert part of legacy header search path changes to include root 'Public' and 'Private' folders again

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
When using `resources` DSL (note: *not* `resource_bundle`) then all `.xcassets` end up within `Assets.car` file.
This was causing re-builds of a project with many resources like the one in https://github.com/CocoaPods/CocoaPods/issues/7511 to re-compile very slow.
This makes re-compilation instant.
> Fix script phase output path for `.xcasset` resources

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7507
This regressed from one of the commits in 1.5.0, it is working in 1.4.0.
> Fix `PRODUCT_MODULE_NAME` for test generated targets

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
closes #7003 supersedes https://github.com/CocoaPods/CocoaPods/pull/7020
> Prevent `xcassets` compilation from stomping over the apps `xcassets`

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/project.rb
- lib/cocoapods/sandbox/path_list.rb
- spec/unit/project_spec.rb
- spec/unit/sandbox/path_list_spec.rb
Fixes a regression introduced in https://github.com/CocoaPods/CocoaPods/pull/7470.
> It turns out this has caused a regression for one of our pods -- it has a vendored_library , libThing.a, that is a symlink to just Thing. With this change, CocoaPods is no longer keeping libThing.a around, so linking is failing.
cc @rmtmckenzie
> [PathList] Wait to resolve symlinks until checking header ACL

- CHANGELOG.md
- lib/cocoapods/command/update.rb
- spec/functional/command/update_spec.rb
This PR introduces `--exclude-pods` option to `pod update` command.
It allows to skip the update operation for specific pods.
E.g.: `pod update --exclude-pods=Alamofire` will update all installed pods from the lockfile except Alamofire.
When `--exclude-pods` option is used with non installed pods, an Informative error will be raised.
Resolves #7334
> Allows to skip update operation for specific pods

- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
They're unnecessary (since they wont ever point to a swiftmodule file), and make us hit `ARG_MAX` faster
> Remove SWIFT_INCLUDE_PATHS for dependent targets with no swift

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
Same result, no need for a new test since its already covered. Just re-using the same method for consistency.
> Fix to use common method for resource bundle Info.plist file generation

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
When passed the --verbose flag, `xcodebuild`'s output will be streamed instead of being held until it's done
closes #7040
> Update validator to stream output as xcodebuild runs

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- lib/cocoapods/target.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
closes #7213 
closes #7307
Support static frameworks with a mix of Objective C and Swift
It turns out that solving this problem simplifies the static framework implementation.  Instead of building a static library and moving files around to create a static framework, we now build a standard Xcode framework, but just force its library to be static - so Xcode will do all the file organization work.
I've verified that this fixes the mixed language examples from #7213, #7307 and #7413.
> Mixed language static frameworks

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/target/pod_target_spec.rb
1. Generate info plist file for test spec target to create valid test bundle, allowing tests to load bundle resources fixes https://github.com/CocoaPods/CocoaPods/issues/7506
2. Clear product module name to inherit Xcode default value, which is `$(PRODUCT_NAME:c99extidentifier)`, see https://github.com/CocoaPods/CocoaPods/pull/7510#discussion_r174983832. This always creates valid identifier different from the parent spec module name. 
closes https://github.com/CocoaPods/CocoaPods/issues/7506
> fix pod lib lint errors for pod with test_spec

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
This stops us pointing to a module map that does not exist, since we don't generate module maps for test specs.
> Fix Swift static libary test specs

- CHANGELOG.md
- lib/cocoapods/generator/module_map.rb
- spec/unit/generator/module_map_spec.rb
Found this during investigating https://github.com/CocoaPods/CocoaPods/issues/7546
> Escape double quotes for module map contents

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
Allows Swift static libraries to be used in targets whose search paths are inherited
> [PodsProjectGenerator] Add target dependencies when inheriting search paths

- CHANGELOG.md
- lib/cocoapods/resolver.rb
Calling "pod install" on our project (with over 100 podspec dependencies) was very slow - profiling showed dependency resolver to be the bottleneck, with the dependency cache returning hundreds of millions specs at the end.
The issue was that dependency nodes returned from `valid_dependencies_for_target_from_node` had thousands of duplicates, resulting in exponential dependency resolution times for each additional target.
This ensures we remove duplicates when returning target appropriate nodes from `valid_dependencies_for_target_from_node`, reducing our pod install times by a factor of 2x.
> [Resolver] Fix performance issue with exponential growth of dependency nodes cache

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
Fix static framework dependent target double linking without use_frameworks
Close #7592 
While related to #7155, #7592 and this fix only impact static_frameworks being used from Podfiles without use_frameworks!
> Fix static framework dependent target double linking 

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
When profiling slow `podinstall` times for our project, almost a third of the time was being spent in `set_target_dependencies`, with hundreds of calls to the expensive `add_dependent_targets_to_native_target` function. Debugging showed that function gets called multiple times for the same native target, which in the end results in no new dependencies getting added - but slow product name resolution meant slow execution of this task (note over 5M calls made c99ext_identifier - for a project with about 100 pods and 60 targets).
This fix, or rather a work around, adds a cache to short-circuit and return if we've already handled adding dependencies for a given target. This speeds up `podinstall` for us by 25% (same gain observed when applied on top of #7541).
Now, it's likely this is not the …
> [Pods Project Generator] Improve performance by removing redundant processing for native target dependencies

- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
`project` should eventually be removed from being managed by the `sandbox`... This makes it easier to create `TargetInstaller` instances without depending for something to have setup the `project` attribute into the `sandbox` magically.
Helps to avoid figuring out at what point things happen...
> Pass project into target installer instead of deriving it

- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
- spec/unit/installer/analyzer/sandbox_analyzer_spec.rb
This was added for backwards compatibility for versions < 0.18, which introduced the manifest.lock file
> Remove :lockfile attribute from SandboxAnalyzer

- Gemfile.lock
- lib/cocoapods/external_sources/abstract_external_source.rb
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb
- lib/cocoapods/installer/analyzer/pod_variant.rb
- lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- lib/cocoapods/resolver.rb
- lib/cocoapods/sandbox.rb
- lib/cocoapods/sandbox/headers_store.rb
- spec/functional/command/repo/push_spec.rb
- spec/spec_helper.rb
- spec/spec_helper/pre_flight.rb
- spec/unit/external_sources/abstract_external_source_spec.rb
- spec/unit/external_sources/downloader_source_spec.rb
- spec/unit/external_sources/path_source_spec.rb
- spec/unit/external_sources/podspec_source_spec.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer/xcode/target_validator_spec.rb
- spec/unit/installer_spec.rb
- spec/unit/resolver_spec.rb
- spec/unit/sandbox_spec.rb
- spec/unit/validator_spec.rb
- [Analyzer] Speed up #filter_pod_targets_for_target_definition
- [Resolver] Speed up #resolver_specs_by_target
This brings the time down from 90s to 4s for us, by reducing the amount of times we perform graph traversal from something like O(x^n^n) to O(log n)
- [Sandbox] Allow storing specs directly
This also allows up to only create the `Local Podspecs` dir once
- Clean up specs to make failures more obvious
- [Sandbox] Cache “Local Podspec” specs
- [SandboxAnalyzer] Don’t treat a pod as added if it’s local
- [PodVariant] Avoid allocating arrays in #hash
- [LockingDependencyAnalyzer] Only add a dependency string to the graph once
This saves almost 2 seconds on our project
- [Analyzer] Avoid checking checksums for the same pod multiple times
- [Analyzer] Don’t analyze multiple times
- …
> Yes, improving performance again

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
Close #7591 
Vendored framework headers get found via FRAMEWORK_SEARCH_PATHS when use_modular_headers! is on. 
For static libraries without use_modular_headers!, the same symbolically linked header is available both from FRAMEWORK_SEARCH_PATHS and HEADER_SEARCH_PATHS.
> Always generate FRAMEWORK_SEARCH_PATHS for vendored_frameworks

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
- spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
When cocoapods is searching for specs subsets, it does not take into account the fact that some targets might be duplicated. If this is the case, this has the results of removing a dependency entirely and the build to not find the framework at all.
This was introduced by https://github.com/CocoaPods/CocoaPods/issues/6967
I have checked that the example project related to this issue is still working with this change.
> Prevent duplicated targets from being stripped out from the framework search paths

- lib/cocoapods/installer/pod_source_installer.rb
- spec/unit/installer/pod_source_installer_spec.rb
Nothing is using it, maybe something did in the past but there is no reason to expose this attribute and hold on to it.
> Remove unused #specific_source attribute

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
Fixes #7590 
Tested locally with the sample projects from #7590 , #7003 , #7511 , app icons still show.
I'm also making a PR for cocoapods-integration-specs.
> Fix assetcatalog_generated_info.plist path in copy resources phase

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/target/pod_target_spec.rb
Make modular header private header access consistent with frameworks and static libraries
Closes #7596
> Make modular header private header access consistent

- lib/cocoapods/installer/xcode/pods_project_generator.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
A regression discovered by https://github.com/CocoaPods/CocoaPods/issues/7648
This is because we now add a `PBXAggregateTarget` placeholder into targets that do not require building.
Does not actually fix #7648 though.
/cc @artmz
> Do not crash in pods project generation when adding framework file references to stub targets

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
- spec/unit/installer_spec.rb
- spec/unit/target/pod_target_spec.rb
This is in preparation of getting each test spec to actually create a test bundle target (one-to-one map) instead of grouping them together by supported test types.
This PR can go by itself since it only changes the way we store dependencies but has no effect on how the integration works today.
It will help with figuring out which pods to to use for each test bundle that gets created instead of linking them all blindly.
> Track test dependent targets per test spec instead of flat list

- lib/cocoapods/generator/copy_resources_script.rb
Fixes #7654 
Needs cocoapods-integration-specs update.
Overwriting assetcatalog_generated_info.plist is useless and will mess up apps with launch images.
Tested with the other related issues
> Change generated asset catalog plist name

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
The actual `.sh` script generated does the right thing but the input and output paths for a test target will include input and output paths from other test targets. 
This can cause cases of recompilation for test targets that have dependencies to other pods that also have test specs and resources or frameworks.
> Do not include test dependencies input and output paths

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/aggregate_target.rb
- lib/cocoapods/target/pod_target.rb
- spec/spec_helper.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer/post_install_hooks_context_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator/xcconfig_integrator_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer/user_project_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
- spec/unit/installer_spec.rb
- spec/unit/library_spec.rb
- spec/unit/target/aggregate_target_spec.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
- spec/unit/target/pod_target_spec.rb
For performance, since the analyzer has the dependency cache
> Move computing pod targets by config to the analyzer

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
If a user project does not contain 'Release' or 'Debug' then generating build settings should not crash.
> Do not crash when creating build settings for a missing user build configuration

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
This is unset for some test target configurations.
> Allow EXPANDED_CODE_SIGN_IDENTITY to be unset

- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
This fixes missing symbol errors at link time
This mirrors the treatment vendored static libraries get
> Link vendored static libraries into dynamic frameworks

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
- spec/unit/target/pod_target_spec.rb
In 1.6.0 we now add a `PBXAggregateTarget` for pod targets that should not be built. This means we can integrate script phases to them instead of forcing a pod target to be actually built (`should_build?` to return `true`).
closes https://github.com/CocoaPods/CocoaPods/issues/7746
This is how it looks after this change:
> Do not build pod target if it contains script phases

- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
This is again a small step towards getting one-to-one test spec support. We now model all resource bundles created as a hash for each of the test spec that were created for.
This changes the underlying model but does not change the current integration at all (all test specs -> a single bundle target)
> Split test resource bundles installed by each test spec

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
- spec/unit/installer/xcode/pods_project_generator/target_installation_result_spec.rb
As of 1.5.2 (and will be in 1.6.0) vendored pods (`should_build?` returns `false`) will not integrate their test specs. Some bigger changes are required to accomplish this.
This fixes an edge case in which a pod target must be integrated because it has script phases but it should not be built. The code assumes that a test target has been created for the test specs.
This fixes this edge case.
Found as part of https://github.com/CocoaPods/CocoaPods/issues/7394
> Do not try to integrate uncreated test native targets

- CHANGELOG.md
- lib/cocoapods/installer/analyzer/target_inspector.rb
- spec/unit/installer/analyzer/target_inspector_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7731
> Attempt to parse `SWIFT_VERSION` from xcconfig during target inspection

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
In case that:
1. static library is enabled
2. modular header is enabled
3. header_dir is specified in PodSpec
the project fails to build since the umbrella header's import paths are wrong - it does not take header_dir into account so far which is still fine with Embedded Frameworks since it force flatten the header directories but not with Static libraries
Example projects which causes this issue: [ReactNative](https://github.com/facebook/react-native/blob/master/React.podspec) / [Lottie](https://github.com/airbnb/lottie-ios/blob/master/lottie-ios.podspec)
Example Podfile:
```ruby
...
use_modular_headers!
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'Core',
'CxxBridge',
'DevSupport',
'RCTText',
'RCTNetwork',
'RCTWebSocket',
'RCTAnimation',
]
...
```
> Fix a bug that umbrella  header import fails in a specific case

- CHANGELOG.md
- lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
Done by using Pod::Version instead of Gem::Version, which in 2.7.7 stop allowing initializing a version with `nil`
Closes #7765.
> Fix compatibility with RubyGems v2.7.7

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Fixes #7530
@dnkoutso We may also be able to mark #3032 and #7486 as done, unless they should stay open for future DSL to be added
Podspecs utilizing this may need to set `s.resources = 'PATH_TO_INFO_PLIST.plist'` so that the file is not discarded during install
> Fix `INFOPLIST_FILE` being overridden when set in `pod_target_xcconfig`

- CHANGELOG.md
- lib/cocoapods/command/lib/lint.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/external_sources/abstract_external_source.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Closes #7783
Supports setting multiple platforms by passing a comma-separated list, ex. `ios,osx`
> Add `--platforms` parameter to `pod spec lint` and `pod lib lint`

- CHANGELOG.md
- lib/cocoapods/downloader/cache.rb
I had an issue in a project I work with a private pod that caused the method `copy_and_clean` to throw an error. The issue was in our directory structure, we had a path too long and this made the line `FileUtils.cp_r(source, destination)` to produce an error related to this path. 
The major problem was that after this, another error was produced, this time by the call inside `ensure` to `remove_entry` of `in_tmpdir` showing me that the directory inside the temp folder was not removed because the directory wasn't empty. Since the main purpose seams to be to ensure the removal of this directory I think a forced `remove_entry` is a better choice, this way any error produced inside the block called by the `in_tmpdir` method will not avoid the removal of the directory. 
I think this is not a …
> Adding force true option to the remove_entry call from FileUtils

- Gemfile.lock
- cocoapods.gemspec
macOS 10.14 introduces (or at least begins to use) two new load commands, so ruby-macho has been updated accordingly.
The 1.3 release will contain an option to ignore new load commands in the future, but 1.2 is just a stopgap.
> [Gemspec] Bump ruby-macho to '~> 1.2'

- lib/cocoapods/command/spec/create.rb
- spec/functional/command/spec_spec.rb
The [official docs](https://guides.cocoapods.org/syntax/podspec.html) uses `spec` instead of `s`, so why not make it consistent?
> Make the generated Podfile consistent with the docs

- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
Given:
```ruby
target 'StaticLibrary'
pod 'Something' # which includes resource bundles
end
```
CocoaPods integrates the `Copy Pods Resources` script phase  into user static library targets unnecessarily, including the input and output paths which could cause unnecessary and confusing diffs.
This change mirrors what we do for `add_embed_frameworks_script_phase` which is only integrated and added for targets that make sense.
> Do not add copy resources script phase for static library user targets

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Every generated `Info.plist` file from CocoaPods points to `CURRENT_PROJECT_VERSION` variable for the value of `CFBundleVersion`.
For test specs that require an app host this value is not set because it is generated by CocoaPods. This fixes it by setting the value for generated app host targets.
See https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/info_plist_file.rb#L103
> Set `CURRENT_PROJECT_VERSION` for generated app host targets

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7814
closes https://github.com/CocoaPods/CocoaPods/issues/7587
@CodingMarkus I spent a bit more time on this and figured out why I could not repro. I did have a universal framework but:
```bash
if [[ "$(file "$binary")" == *"dynamically linked shared library"* ]]; then
strip_invalid_archs "$binary"
fi
```
This check was failing and so no stripping was happening at all, even though I had applied your fix within `strip_invalid_archs`.
That is because the result of `"$(file "$binary")"` returned `"/path/to/framework/binary : symbolic link to Versions/Current/framework"` and so it was never executing.
The fix was to properly figure out the final location of the binary was and propagate it through like you recommended but at an earlier …
> Properly follow symlinks within macOS universal frameworks

- CHANGELOG.md
- lib/cocoapods/generator/app_target_helper.rb
- lib/cocoapods/validator.rb
- spec/unit/generator/app_target_helper_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7738
If the pod being linted does not use Swift but any of its dependencies do, then a dummy Swift file is added to the 'App' in order to ensure Swift will be linked.
> Validator adds a Swift file if any of the pod targets use Swift

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- lib/cocoapods/target/aggregate_target.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
- spec/unit/target/aggregate_target_spec.rb
- spec/unit/target/pod_target_spec.rb
One more step closer to https://github.com/CocoaPods/CocoaPods/issues/7573
I believe there is one more PR left to complete this feature.
This basically allows to scope out resource and framework paths by each podspec. It does not change any logic. It will help by assigning different input and output paths for each test bundle that will be created.
> Allow scoping framework and resource paths by specs

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
This is a master only issue.
In 1.6.0 we changed it so targets that `should_build?` return `false` will now integrate a PBXAggregateTarget and return early.
By returning early we no longer create an xcconfig for these targets (which 1.5.3 used to do) which means none of the other variables such as `PODS_TARGET_SRCROOT` are available. If this target includes a script phase then it will not be able to reference this env variable or other `PODS_*` variables
This change fixes this regression and ensures an `xcconfig` is created for these targets.
> Fix PBXAggregateTargets to include an xcconfig

- lib/cocoapods/sandbox/path_list.rb
Cache absolute paths when globbing instead of repeatedly joining against the path_list root
In the test project I'm using to benchmark, this reduced the number calls to `Pathname#join` (which itself calls `Pathname.new`) from ~56k to ~11k, which also eliminates the allocation of ~40k Pathname instances.
> Cache absolute paths when globbing

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- lib/cocoapods/target.rb
This means we wont be overwriting the underlying file, so `pod install` wont cause full recompiles
> [PodTargetInstaller] Symlink static lib custom modulemaps into the Headers directory

- spec/unit/target/aggregate_target_spec.rb
These tests would fail if depth of the directories of the developer's machine didn't match that of CI.
Closes #7874
> Fix aggregate_target_spec sometimes failing

- spec/unit/installer/analyzer_spec.rb
These tests appear to have been disabled since they were written [5 years ago](https://github.com/CocoaPods/CocoaPods/commit/4a37f7ee7d18c9f3e6b41d848b4ebed14fcf263b#diff-41c1653a4992205902446fc79c4380afR123). The functionality appears to be covered by other tests, might as well remove them.
> Remove outdated tests that were never enabled

- lib/cocoapods/generator/acknowledgements/markdown.rb
- lib/cocoapods/generator/acknowledgements/plist.rb
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/generator/dummy_source.rb
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
Currently `update_changed_file` writes the new file to disk, checks if they are the same with `FileUtils#identical?` (which then loads both files into memory) and then moves the new file over if the contents have changed.
By avoiding reloading the file that we just wrote back into memory, we can save a large amount of memory allocation. Since garbage collection accounts for a major portion of `pod install` times, this should hopefully help.
Tested using the `memory_profiler` gem
(note: this was tested on a test project meant to stress CocoaPods, and may not be representative of the average project that utilizes CocoaPods)
Total allocated: 12547967800 bytes (**11.69 GB**)
Total retained:  14801813 bytes  (**14.8 MB**)
Total allocated: 6329712267 bytes (12363884 objects) (**5.9 GB**)
Total …
> Reduce memory allocation in TargetInstaller#update_changed_file

- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
Since a recent commit made Generators call #generate when the target path exists, we were accidentally re-computing each and every build setting every time. This was incredibly expensive, so instead we will update the specs to #dup build settings in #before, and ensure that copying a BuildSettings object does not bring along the memoized state
> [BuildSettings] Remove #__clear__

- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/target/pod_target.rb
- spec/spec_helper.rb
- spec/spec_helper/mock_source.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
- spec/unit/resolver_spec.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
Let the build system natively handle transitive dependencies
This will help keep the pods project as compact as possible, and also allow the build system to have an easier time when traversing the build graph
> Only add target dependencies for direct dependencies

- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb
- lib/cocoapods/target/pod_target.rb
- spec/fixtures/watermelon-lib/WatermelonLib.podspec
- spec/unit/installer/xcode/pods_project_generator/app_host_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
- spec/unit/target/pod_target_spec.rb
`pod_target_installer.rb` is becoming too big and since we are using only one app host per test type it does not make sense to keep it within `pod_target_installer`. We also had to debounce to prevent adding an app host many times.
> Extract app host out of pod target installation

- CHANGELOG.md
- lib/cocoapods/command/init.rb
- lib/cocoapods/command/repo/add.rb
- lib/cocoapods/command/repo/list.rb
- lib/cocoapods/command/repo/push.rb
- lib/cocoapods/command/repo/remove.rb
- lib/cocoapods/command/repo/update.rb
- lib/cocoapods/command/setup.rb
- lib/cocoapods/config.rb
- lib/cocoapods/sources_manager.rb
- spec/unit/config_spec.rb
Currently if you want to change the folders used by Cocoapods you have to set 3 separate envvars.
This is completely non-obvious and not really very helpful. It wasn't until I search though the code that I worked out why setting `CP_HOME_DIR` apparently did nothing.
I have also updated the help messages to use these global variables, as before they would be misleading in an environment where the dirs have been changed.
This has the potential for being a breaking changing for some people, but given that `CP_HOME_DIR` isn't documented anywhere, its probably not very widely used. I would expect that 99% of people using `CP_HOME_DIR` are also setting `CP_REPOS_DIR` and `CP_TEMPLATES_DIR`, and so they would be unaffected by this change.
Also, 🌈
> Use CP_HOME_DIR as the base for all default directories

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings_spec.rb
-ObjC was not getting generated for apps linking static frameworks that were accessing podspec's other than via spec repo's. 
This PR makes the static framework linking behavior consistent with static libraries.
More details and an example at https://github.com/firebase/firebase-ios-sdk/issues/1341
> Generate -ObjC in OTHER_LDFLAGS for apps with static frameworks

- CHANGELOG.md
- lib/cocoapods/command/install.rb
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer/specs_state.rb
- spec/unit/installer_spec.rb
It errors if there are any changes to the podfile or the lockfile, similiar to `bundle install --deployment`.
It would be useful to have for CI.
> Add a deployment mode for installs

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Fixes a bug introduced in #7932 
Architectures were being set for placeholder aggregate targets (ex. pre-built vendored frameworks) and introduced an Xcode warning with a Fix-It.
> Don't set architectures for placeholder aggregate targets

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
- spec/unit/target/aggregate_target_spec.rb
Follow up to #7181 - if we aren't going to add the scripts to the user project, don't generate the files at all and don't write them to disk.
cc @keith
> Don't generate scripts if they will not be added to the user project

- CHANGELOG.md
- lib/cocoapods/command/lib/lint.rb
- lib/cocoapods/command/repo/push.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/validator.rb
- spec/functional/command/repo/push_spec.rb
- spec/unit/validator_spec.rb
Progress towards #7683 
Still need to add the flag to `pod trunk`
> Add --use-modular-headers to lint and push commands

- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/installer/analyzer_spec.rb
This also fixes a regression introduced in https://github.com/CocoaPods/CocoaPods/pull/7673/files#diff-1dbd9ba0c7631def44be07aa66e00e45R76.
It appears that now aggregate targets use `pod_targets_for_build_configuration`  but the `analyzer.rb` actually updates `pod_targets` array after it appends a few pod targets used by embedded aggregate targets.
We were never updating the list of `pod_targets_for_build_configuration` correctly.
With this change the bug was fixed and every property in `aggregate_target.rb` is now an `attr_reader`.
> Make `aggregate_target` completely immutable

- Gemfile.lock
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
requires https://github.com/CocoaPods/Xcodeproj/pull/593/files
Fixes a case where placeholder targets do not have `SDKROOT` set and therefore allow users to build for "macOS" even though all of the pods they consume are for iOS only and vice versa.
> Ensure platform and deployment target is set for placeholder targets

- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/installer/analyzer_spec.rb
Don’t copy embedded targets to the host when the host already inherits search paths from the embedded target’s aggregate target
Fixes a regression introduced in https://github.com/CocoaPods/CocoaPods/pull/7978
> Don't embed inherited search paths dependencies

- lib/cocoapods/target/aggregate_target.rb
- spec/unit/target/aggregate_target_spec.rb
Ensure aggregate targets that merge embedded targets pod targets retain their search paths inheritance
Fixes a regression introduced by https://github.com/CocoaPods/CocoaPods/pull/7992 since there were no tests covering this scenario
> [AggregateTarget] Fix search paths inheritance

- lib/cocoapods/generator/acknowledgements/plist.rb
- spec/unit/generator/acknowledgements/plist_spec.rb
First, I don't know why it cause a issue. CocoaPods could not call the `plist` method and cause the plist file to not be generated. I try to put some logs in the `plist` method and output nothing. And the log in `generate` method is normal.
I check everything, but could not find the reason. I try to rename the `plist` name to other name, everything is OK. It maybe the method name conflicts with local var name ( I am not sure.)
> fix a same name issue under different ruby

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/8031
> Clear out `MACH_O_TYPE` for unit test bundles that use static frameworks.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/validator_spec.rb
Validate that all generated `PBXNativeTarget`s contain source files to build,
so specs (including test specs) with no source files won't fail at runtime
due to the lack of a generated executable.
> Validate all generated native targets have source files

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
Fixes #7606 
This will remove `CODE_SIGNING_REQUIRED`, `CODE_SIGNING_ALLOWED` config from Pods' Project which suppress code signing for all situation.
Now even dummy codesigning (with com.apple.security.get-task-allow entitlement) required when attach to process on simulator (Changes from Xcode 9.3), and this enforces linked frameworks codesigned too.
But those config suppress codesign which failed to launch from simulator specifically `@IBDesignable` classes (which lookup from: `$TARGET_BUILD_DIR`)
```
Did find:
@{Linked Binary}: required code signature missing for @{Linking Binary}
```
> Remove codesign suppression

- CHANGELOG.md
- lib/cocoapods/installer/installation_options.rb
- lib/cocoapods/installer/user_project_integrator.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- spec/unit/installer/installation_options_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/8073
We cannot do anything about this until Apple resolves the issue with Xcode 10, dynamic frameworks and script phases not being re-run due to a change in the folder. 
In the meantime we provide users the option to disable input/output paths so the script phase will always run. 
For those who opt in to use this option, it mean slower but correct incremental builds.
> Provide an installation option to disable usage of input/output paths.

- .gitmodules
- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
🌈
- Replace usage of the `-iquote` compiler flag by `-isystem` when searching for framework headers. This will silence compilation warning in the Pods' headers files.
> "Header files found in directories added to the search path with the `-isystem` and `-idirafter` command-line options are treated as system headers for the purposes of diagnostics"
> "All warnings [...] are suppressed while GCC is processing a system header"
[https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html](https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html)
- Update unit tests to reflect the above change.
Integrations tests are updated in https://github.com/CocoaPods/cocoapods-integration-specs/pull/94.
This fixes #5589.
When I tested locally with `bundle exec rake spec:all`, it failed on the Alamofire example, …
> [Generator] Replace -iquote by -isystem for frameworks in xcconfig

- Gemfile.lock
- cocoapods.gemspec
See https://github.com/Homebrew/ruby-macho/pull/113 and https://github.com/Homebrew/ruby-macho/pull/114.
> [Gemspec] Bump ruby-macho to '~> 2.1'

- CHANGELOG.md
- lib/cocoapods/installer/pod_source_installer.rb
- spec/unit/installer/pod_source_installer_spec.rb
> Don't generate unencrypted source warnings for localhost

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator_result.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
- spec/unit/installer_spec.rb
Functions in this class now rely less on the assumption that a project object will be created by the time the function is ran and requires a `project` parameter to be passed into itself. Since the `generate!` function is responsible for actually creating the Pods project file, we return it wrapped inside a `PodsProjectGeneratorResult` object alongside the `target_installation_results` that is also returned from `generate!`.
> Small refactoring of pod project generator.

- bin/pod
Fixes #8209 
- To avoid env variable `PROFILE` which can be commonly use in CI environment.
- `COCOAPODS_PROFILE` could be a good alternative
> Fix PROFILE to COCOAPODS_PROFILE to avoid commonly used the env variable 

- lib/cocoapods/target/pod_target.rb
This prevents `UI.warn` from being called multiple times therefore spamming users when they hit that case.
> Properly cache value for `inhibit_warnings?` method

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator.rb
Introduced with the introduction of app specs:
https://github.com/CocoaPods/CocoaPods/pull/8158
> Don't have libraries add app targets to their scheme for building.

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/installation_options.rb
- lib/cocoapods/installer/user_project_integrator.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- lib/cocoapods/podfile.rb
- lib/cocoapods/resolver.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
- spec/unit/installer/xcode/target_validator_spec.rb
- spec/unit/installer_spec.rb
* Remove dependency on InstallationOptions for several classes that only used one value from them:
- `Installer::UserProjectIntegrator`
- `Installer::UserProjectIntegrator::TargetIntegrator`
- `Installer::Xcode::PodsProjectGenerator::PodTargetIntegrator`
* Add `InstallationOptions` to `Podfile`, since they are defined in the Podfile DSL. (Would love feedback on this part - not sure if this is the right way to go, but right now it does feel a bit odd that the InstallationOptions come from the Podfile but are not associated with it)
* Make `PodProjectGenerator#write` a pure class function
* Cleanup some things along the way
> [InstallationOptions] Reduce reliance on access to InstallationOptions

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
Make symbolic links to module maps and umbrella files relative instead of absolute. See #8174.
Without this change, its much harder to share a workspace that includes a pods project because everyone has to check out files to the same root folder. Otherwise the absolute symbolic paths are invalid and you get compile errors.
This was tested with Xcode 10 with a project that uses both Swift and ObjectiveC static libraries.
> Use Relative Symbolic links

- CHANGELOG.md
- lib/cocoapods/command.rb
- lib/cocoapods/executable.rb
- lib/cocoapods/sandbox/headers_store.rb
- spec/unit/executable_spec.rb
This should address issues such as #8055 and #8077.
For this to work, a developer would need to install git and curl and make sure they are available in the PATH.
> Windows support - ensure pod install/update will succeed.

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/xcode.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb
- spec/unit/installer/xcode/pods_project_generator_spec.rb
- spec/unit/installer_spec.rb
This extracts writing and cleaning up a `Project` out of `PodsProjectGenerator` and into its own object called `PodsProjectWriter`.
> Extract project writing into a new object.

- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb
The object `ProjectGenerator` is now repsonsible for creating a new `Pod::Project` and preparing it's structure from the build configurations, platforms, and pod targets.
> Extract project creation and preparation into new object

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/post_install_hooks_context.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/sandbox.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/post_install_hooks_context_spec.rb
- spec/unit/installer/user_project_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/app_host_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
- spec/unit/sandbox_spec.rb
Removes reference to the pods project on `Sandbox`. Projects should now be injected everywhere as an arg.
> Kill sandbox.project

- lib/cocoapods/target/build_settings.rb
Since specs can only overlap for the same pod, grouping by pod name can mean we can ignore many (most?) of the pod targets when taking combinations
> [BuildSettings] Speed up computing the set of maximal pod targets

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
The compatibility hack only needs to happen for libraries, since Xcode will Do The Right Thing™️ for anything packaged as a framework
This fixes a regression introduced a couple of days ago, I think?
> [PodTargetInstaller] Allow swift static frameworks to have custom module maps

- CHANGELOG.md
- lib/cocoapods/generator/app_target_helper.rb
- lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
- spec/unit/generator/app_target_helper_spec.rb
Fixes #8285. This PR modifies the template for launch storyboards to be compatible with iOS 8 by not including safe area insets.
If we want to keep the current state, it looks like we could pass the deployment target to the method that uses this, so I could create an alternative version that works for iOS 8 targets, keeping this version for iOS 9 targets.
> Use maximally-compatible launch storyboard for iOS 8 compatibility.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
The new Xcode 10 build system spits out a warning about missing Info.plist files for static frameworks like:
`    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'FirebaseCore')`
Even though Info.plist files should not be needed since static frameworks are fully linked into apps before bundling, they should be harmless to include.
Reported at https://github.com/firebase/firebase-ios-sdk/issues/1846
> Generate Info.plist files for static frameworks

- Gemfile.lock
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb
- spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
- spec/unit/installer/xcode/single_pods_project_generator_spec.rb
Instead of calling `predictabilize` on each individual project, we will pass in the list of generated projects such that UUIDs are unique across all projects instead of unique per individual xcode project.
> Update call to generate deterministic UUIDs.

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
The entire word is an acronym, so "HTTPS" is correct.  "HTTPs" would be plural HTTP, which isn't the intended use here.
> Fix HTTPs -> HTTPS in warning message

- CHANGELOG.md
- lib/cocoapods/command/repo.rb
- lib/cocoapods/command/repo/add_cdn.rb
- lib/cocoapods/command/repo/list.rb
- spec/functional/command/repo/add_cdn_spec.rb
As discussed in #8268, I am submitting an initial draft of the CDN source implementation.
Please note that at this point, the implementation is purely additive, and does not interfere with traditional spec repo retrieval.
There's a corresponding [PR in Core](https://github.com/CocoaPods/Core/pull/469) that needs to be merged first.
The tests on travis will fail because of Core integration, but I've hacked together [another branch](https://travis-ci.org/igor-makarov/CocoaPods/builds/455397872) to show that everything passes. As soon as the [Core PR](https://github.com/CocoaPods/Core/pull/469) is merged, the tests here will pass as well.
> Add CDN repo Source to allow retrieving specs from a web URL

- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
Currently, if you specify in your Podfile `source 'https://github.com/artsy/Specs.git'`, it would clone the spec repo for you.  
This PR adds the same convenience for CDNSource when specified as `source 'https://cdn.jsdelivr.net/cocoa/'`.
The way the new code determines whether the URL is git or not, is by examining whether it ends with `.git`. 
I've added tests for the new case and also another for master repo add.
> Podfile: Add a CDNSource automatically if it's not present, just like git Source

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/sandbox_dir_cleaner.rb
- lib/cocoapods/installer/sandbox_header_paths_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/sandbox.rb
- lib/cocoapods/sandbox/headers_store.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/sandbox_dir_cleaner_spec.rb
- spec/unit/installer/sandbox_header_paths_installer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
- spec/unit/installer_spec.rb
- spec/unit/target/pod_target_spec.rb
Inside stage sandbox we now add all the respective header search paths to the sandbox `HeaderStore` and each pod target's `HeaderStore`. This sets up the work for incremental pod installation because we would like to analyze each pod target's build settings to determine if it has changed; however, we previously only added the header search paths during installation which is too late in the pipline.
Instead of removing the entire Headers and Target Support Files directory in the Sandbox for every installation, we now only remove the headers and target support files that are stale.
integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/197
> Creates a stage sandbox and sandbox dir cleaner step.

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
It turns out that at least with Xcode 10 `showEnvVarsInLog` never gets set to '1' when it gets set. It is just deleted.
This fixes a case in which Xcode 10 re-writes certain script phases and causes a dirty `.xcodeproj`.
See more detail here https://github.com/CocoaPods/Xcodeproj/pull/652#issue-243849364
> Set `showEnvVarsInLog` for script phases only when its disabled.

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
Saw this briefly and figured it would be faster with `partition` than iterating twice for `select`and `reject`.
> Use `partition` when filtering resource file references

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
This reverts commit b5ee60aa5b64d0697a481f0a4df9bc53c8e7f45f.
The fix for https://github.com/CocoaPods/CocoaPods/issues/8337 is actually not to include `inherit! :search_paths` for the UI test bundles.
UI test bundles work differently and run within the context of a _Runner.app_. Linking dependencies into the UI test bundle should be safe and not cause duplicate symbols because it does not run within the app being tested.
I tried the above into the sample app in https://github.com/CocoaPods/CocoaPods/issues/8337 and confirmed it worked. 
*Note*: _unit_ test bundles _should_ have `inherit! :search_paths` that is because they run within the app they are testing which should be integrating all frameworks and linked libraries instead.
> Revert "Fix runpath_search_paths for inherit search_path targets"

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
Merge pull request #8314 from CocoaPods/segiddins/remove-linker-flas-from-pod-targets
This cherry-picks https://github.com/CocoaPods/CocoaPods/pull/8314 into `1-6-stable` branch to release 1.6.0 for CocoaPods.
Will need one more after which is https://github.com/CocoaPods/CocoaPods/pull/8334
> [CherryPick] Remove unnecessary linker flags from pod targets

- CHANGELOG.md
- lib/cocoapods/project.rb
- spec/unit/project_spec.rb
This fixes an issue that prevents new groups from being placed in the correct directory if all source files are in a nested folder.
For example, if all source code is in `MyLib/Source` directory, then new files or folders should be added within the `Source` folder instead of the `MyLib` folder. For development pods which do not have a common nested directory, the behavior will remain the same.
> Set the path of development pod groups to the top-most shared directory

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
> Ensure sources specified with the `:source` option are always updated if `--repo-update` is specified

- lib/cocoapods/installer.rb
- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- lib/cocoapods/sandbox.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
In addition to checking each target's cache key to determine if it's dirty, we should also check the state of its sandbox to protect against a possible case where the user modifies the sandbox and moves or deletes directories.
This change also moves `SandboxDirCleaner` before updating the project cache and Podfile.lock.
> Update project cache analyzer.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/project.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
- spec/unit/project_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/8496
This PR changes the behavior to set the path of the Pod group to the Pod root, rather than the most common path. This removes a lot of ambiguity between groups that CocoaPods creates and groups created by the existence of a directory.
The downside to removing the common path handling is that folders such as `Source` or `Classes` will show up in Xcode. This seems reasonable to me because it reflects the actual structure on disk.
> Fix incorrect path for Resources group in development pods

- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
Pod targets that are marked as dirty by different steps of the analyzer are concatenated into the full list of pod targets to generate without being deduped.
An easy example of this is simply adding a target. I've added a spec to cover this case.
> Dedup pod targets to be generated from the cache analyzer.

- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Incorrectly using `merge` instead of `merge!`, so this hash was never mutating and thus `#share_development_pod_schemes` was not getting called on any projects and their development pods.
> Fix project by target hash used for #share_development_pod_schemes.

- CHANGELOG.md
- lib/cocoapods/generator/app_target_helper.rb
Supersedes https://github.com/CocoaPods/CocoaPods/pull/8499
> Add annotations of unused test host delegate method arguments

- .github/RFC_TEMPLATE.md
Adds an issue template for submitting RFCs.
Heavily inspired by:
* [Swift Evolution](https://github.com/apple/swift-evolution/blob/master/proposal-templates/0000-swift-template.md)
* [Rust RFCs](https://github.com/rust-lang/rfcs/blob/master/0000-template.md)
Previous examples:
* #8191 Multiple Swift Version Support
* #8253 Incremental Pod Installation (Phase 1)
* #7577 Support for launch arguments and environment variables in test spec schemes
> [Github] Add RFC Issue template

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/target/framework_paths.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/generator/embed_frameworks_script_spec.rb
Vendored frameworks might have bcsymbolmap files next to them so should copy them  https://github.com/CocoaPods/CocoaPods/issues/8461
> Copies the bcsymbolmap files of a vendored framework

- Gemfile.lock
- cocoapods.gemspec
Fixes #8529.
(cherry picked from commit 8df83884bf7054611d7c584f1432aed813725197)
> Cherry-pick ruby-macho bump into 1-6-stable

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
🌈 😃 
`local var = something` does not work in bash. Xcode build will fail with an error like
```
/Users/florian/Projects/Flighty_LLC/flighty-ios/Pods/Target Support Files/Pods-Flighty/Pods-Flighty-frameworks.sh: line 114: local: `=': not a valid identifier
/Users/florian/Projects/Flighty_LLC/flighty-ios/Pods/Target Support Files/Pods-Flighty/Pods-Flighty-frameworks.sh: line 114: local: `/Users/florian/Projects/Flighty_LLC/flighty-ios/Pods/Mapbox-iOS-SDK/dynamic/F8207D73-7248-3A6B-8A81-8EE831BAC4E6.bcsymbolmap': not a valid identifier
Command PhaseScriptExecution failed with a nonzero exit code
```
Only happens if the vendored binary framework includes a `.bcsymbolmap` file I think.
It has to be `local var=something`.
---
I don't know if I did the correct thing (I hope so 😃), seems the …
> Do not use spaces around variable assignment in generated embed framework script

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
As discussed in https://github.com/CocoaPods/CocoaPods/issues/8552
Requires https://github.com/CocoaPods/cocoapods-integration-specs/pull/220 to be merged first.
> Fix destination path for bcsymbolmap files

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
This was wrongly assumed it will be deprecated but with Multiple Swift Versions in 1.7.0 it is not.
> Do not warn that `--swift-version` parameter is deprecated.

- CHANGELOG.md
- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
@igor-makarov Here's one spec. I'll add a couple more later. This should ideally fail the tests.
closes #8572
> Generate all sibling pod targets that share the same xcode project. 

- CHANGELOG.md
- lib/cocoapods/project.rb
Have noticed some collisions happening using 4. For some numbers:
Given 400 projects, there was a ~27% chance that every project's first 4 digits was unique.
Given 400 projects, there is a ~99.5% chance that every project's first 6 digits is unique.
Given 1000 projects, there is a ~97% chance that every project's first 6 digits is unique.
> Bump UUID prefix count from 4 to 6.

- lib/cocoapods/installer.rb
- lib/cocoapods/version_metadata.rb
Instead of using the `gem_version` method, this creates a new abstraction which can make it possible to bump this value if a certain commit requires the need to flush the cache without affecting the `gem_version` value.
> Decouple project cache version from gem version.

- CHANGELOG.md
- lib/cocoapods/command/update.rb
- spec/functional/command/update_spec.rb
fix issue #8565
project directory  option will be invalidated if we use `config.lockfile` in initialize method, because 
`config.installation_root` is set at the end of initialize method.
I think it is more properly to move the code that handles `--sources` and `--project-directory` to run method.
> Fix crash when exec pod update with --sources and --project-directory

- CHANGELOG.md
- lib/cocoapods/installer/project_cache/target_cache_key.rb
- spec/unit/installer/project_cache/target_cache_key_specs.rb
closes https://github.com/CocoaPods/CocoaPods/issues/8657
* Writing to the yaml file sorts entries by downcase, so reading from the cache and then from a `PodTarget` instance would always produce a "dirty" target since the array orders would be different.
* Apply sort_by operator on files in the target cache key.
> Order SPECS key by sorting according to downcase

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Xcodeproj generates new projects with a default Icon called AppIcon [here](https://github.com/CocoaPods/Xcodeproj/blob/0ec1f7f1a80ab2be8dfa60864fbac54206e25e93/lib/xcodeproj/constants.rb#L307).
So when executing `pod lib lint`, the generated Xcodeproj has a set AppIcon and then picked up by the [copy_resources_script.rb](https://github.com/CocoaPods/CocoaPods/blob/b52a70d50f9e31a247794feac25ec9b4effbd13f/lib/cocoapods/generator/copy_resources_script.rb#L226).
This change deletes the ASSETCATALOG_COMPILER_APPICON_NAME key in the build settings when linting.
I did not add a check inside copy_resources_script.rb because checking all the image assets might take too long on large projects and might hide misconfigurations on normal projects.
Fixes: 
#7617
Todo:
> Fix for AppIcon on Lib Lint

- lib/cocoapods/config.rb
Also provides a slight performance boost, since we wont be unnecessarily computing & normalizing the current working directory when it wont be used.
No functional change
> [Config] Simplify memoizing the installation root

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer_spec.rb
- spec/unit/target/pod_target_spec.rb
Closes #8695 
I initially had a workaround in `SandboxDirCleaner` to make sure the directory remained, but it makes more sense for this to be reflected in the value of `headers_sandbox`
For a pod with a different module name, a module map is symlinked to `Pods/Public/[module_name]/[module_name].modulemap`. However, since `headers_sandbox` is set to `Pods/Public/[pod_name]`, this directory was not kept when cleaning the sandbox.
The point at which the directory would be marked as one to keep is in the `else` block here: https://github.com/CocoaPods/CocoaPods/blob/6bd7b5bb2bafe4d78f38bda09b81f7a6bffc407e/lib/cocoapods/installer/sandbox_dir_cleaner.rb#L50-L54
> Fix a bug that caused the headers dir for pods containing a custom module map to be deleted

- .github/ISSUE_TEMPLATE.md
- [AppStore requires Xcode 10.1+ when building for iOS.](https://help.apple.com/xcode/mac/current/#/devf16aefe3b)
- And [CocoaPods 1.6.0 is the earliest version with guaranteed support for Xcode 10.1](https://github.com/CocoaPods/CocoaPods/pull/8203): using an older version would require specific environment conditions, like some `gem update fourflusher`, and we don't need to do extra support for that, so it's time to move forward and mention CocoaPods 1.6.0 instead of 1.1.0.
I'm aware that tvOS and macOS targets don't need Xcode 10.1 yet, but it's not worth mentioning in the issue template.
> Update ISSUE_TEMPLATE.md for Xcode 10.1

- CHANGELOG.md
- lib/cocoapods/resolver.rb
- lib/cocoapods/resolver/lazy_specification.rb
`.uniq`ing the requirements reduces state space, and pruning before going through all source reduces object allocation.
Further, freezing `@ podfile_requirements_by_root_name` means the list of requirements for a pod can't keep on growing every time it's searched for
> [Resolver] Speed up w/ many requirements

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/podfile_validator.rb
- lib/cocoapods/installer/xcode/target_validator.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer/podfile_validator_spec.rb
This is useful in 2 cases:
1) When using CocoaPods to manage unlinked dependencies, such as a linter
2) When using CocoaPods to manage apps & tests, via app specs and test specs. This way, you don't need to create a "dummy" target in your user project to link the app specs dependencies against. This also has a performance benefit, since you won't need to generate any of the metadata needed for an aggregate target.
> Allow abstract-only target definitions to be installed

- CHANGELOG.md
- lib/cocoapods/installer/xcode/multi_pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_dependency_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
- lib/cocoapods/project.rb
- lib/cocoapods/version_metadata.rb
- spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
- spec/unit/project_spec.rb
Previously `Pods.xcodeproj` held all pod subprojects under a `Dependencies` grouping. This change restructures the grouping for just `Pods.xcodeproj` to share a similar format as a single project generation by putting local pod projects under the `Development Pods` group and remote pods under the `Pods` group. Pod subprojects do not share this format and put all subproject dependencies under the `Dependencies` group.
> Refactor MultiXcode proj structure

- lib/cocoapods/external_sources/path_source.rb
- lib/cocoapods/installer.rb
Copied from changes in Bundler 3
Before:
```
Installing...
Fetching podspec for `Blueprint` from `../../Frameworks/Blueprint/Blueprint.podspec`
Using Blueprint (1.0.0.LOCAL)
Pod installation complete! There are 2 dependencies from the Podfile and 1 total pod installed.
```
After:
```
Installing...
Pod installation complete! There are 2 dependencies from the Podfile and 1 total pod installed.
```
This makes a _huge_ difference when you have hundreds of local dependencies, and makes it much more likely that `pod install` output is concise and contains mostly actionable information.
I'm opening this PR up as sort of a request for comment, this obviously is a change in UX, but it's one I'd very much like to see. Let me know what you think!
> [RFC] Default to making installations quieter

- .gitignore
- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
- spec/functional/command/repo/update_spec.rb
🌈
Resolves #7317 
There is an issue when running CI servers that build more than one instance of a project at a time where if two `pod repo update` commands are issued in quick succession, the build will fail because the updates are attempting to simultaneously modify the git repositories.
To solve this problem, I've added logic to create a `Spec_Lock` file in the spec repo directory and then lock that file until the git updates are complete. This causes successive repo commands to execute one at a time.
This is my time using ruby and contributing to CocoaPods so please let me know if there are best practices I missed or any other issues. In particular, I'm not sure that I wrote the unit test correctly however, I did test it with and without my changes and it worked properly.
> Resolved an issue that could cause spec repo updates to fail on CI servers

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/installer/analyzer_spec.rb
Set default build configurations for app / test specs when installing with `integrate_targets: false`, ensuring the `Embed Frameworks` and  `Copy Resources` scripts will copy the necessary biuld artifacts.
> [Analyzer] Set default user build configurations when not integrating targets

- lib/cocoapods/installer/analyzer.rb
Instead of whether targets are being integrated
Its now possible for targets to be integrated in general, but specific pods not to be integrated. Support thar by branching on the precense of inpsections
When not integrating, there will be no inspections so well continue to take the correct branch
> [Analyzer] Check whether there are target inspections

- CHANGELOG.md
- lib/cocoapods/generator/info_plist_file.rb
- lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
- spec/unit/generator/info_plist_file_spec.rb
Allow insecure loads in requires_app_host's Info.plist so that tests that depend http loading will pass.
This is necessary for the GULNetworkTests in GoogleUtilities.podspec to pass when using test_spec's. See https://github.com/firebase/firebase-ios-sdk/pull/2908
More context in https://stackoverflow.com/a/31807139/556617
If this is an acceptable solution, I'll follow up with the Changelog and integration test updates.
> Allow insecure loads in requires_app_host's Info.plist

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator/xcconfig_integrator_spec.rb
Optional include statements are possible in .xcconfig files:
`#include? "/Target Support Files/Pods-SampleProject/Pods-SampleProject.debug.xcconfig"`
However, this currently generates a warning:
```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `SampleProject` to `Target Support Files/Pods-SampleProject/Pods-SampleProject.debug.xcconfig` or include the `Target Support Files/Pods-SampleProject/Pods-SampleProject.debug.xcconfig` in your build configuration (`SampleProject.xcconfig`).
```
The warning is inaccurate, because the integration does succeed. Adding an optional question mark to the regex pattern should …
> Prevent warning with optional #include

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer_spec.rb
- spec/unit/target/pod_target_spec.rb
Fix #8765
#8706 introduced a bug building pods with the `header_dir` attribute as static libraries. This is a minimal fix for that issue.
> Fix 1.7.0.rc.1 static library regression for header_dir attribute

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/fixtures/watermelon-lib/WatermelonLib.podspec
Fix #8173
test_spec resources are already copied in `Copy Bundle Resources`. Don't copy them in `Copy Pods Resources`.
> Don't add resources to a 2nd pod target build phase

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
Using a framework within an extension results in cocoapods linking the framework to the main app target. If the framework is static this should not happen if the framework is only used within the extension.
I added a unit test `does not copy extension pod targets to host target, when use_frameworks! but contained pod is static` to test the behaviour and changed the code accordingly.
I'm uncertain if the test is written appropriately and if the place for the fix is sufficient. Feedback is very welcome :)
> 🌈 Fix embedding static frameworks in extensions while using `use_frameworks!`  

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/target/pod_target_spec.rb
Resources need to be added for test specs in library builds since libraries are excluded from the resource copy part of `add_files_to_build_phases`.
This fixes a regression introduced in #8782
> 1.7.0.rc.2 regression - library test spec resources

- CHANGELOG.md
- lib/cocoapods/installer/sandbox_dir_cleaner.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/sandbox_dir_cleaner_spec.rb
- spec/unit/target/pod_target_spec.rb
Closes #8836
Original implementation in #8706 was a bit heavy handed - we can get the same bug fix by adjusting the behavior of the sandbox cleaner.
> Fix a regression in static library header dir paths

- lib/cocoapods/version_metadata.rb
This will cause the cache to be ignore when those consuming CocoaPods via a git dependency in their Gemfile update to a different commit within the same version series
> Include the commit of CocoaPods in the cache version (when available)

- CHANGELOG.md
- lib/cocoapods/installer/target_uuid_generator.rb
- lib/cocoapods/version_metadata.rb
- spec/unit/installer/target_uuid_generator_spec.rb
In addition to `PBXNativeTarget` UUIDs being referenced via `remoteGlobalIDString` from other projects, so can the `PBXFileReference` that points to the binaries under the `Products` group. If these UUIDs are not deterministic, then during incremental installation, the UUID for the file reference that pointed to the binary can be changed, resulting in parent project crashing because its `remoteGlobalIDString` might end up pointing to a different object entirely.
> Stabilize Product Reference UUIDs.

- CHANGELOG.md
- lib/cocoapods/resolver.rb
- spec/unit/resolver_spec.rb
See #8761 for more details where the current error message may be
misleading, such as a local Pod and Podfile.lock newer than the
specs master repo.
> [Resolver] suggest `pod repo update` on conflict

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
🌈 If a storyboard or xib is included in a pod via `resource_bundles` and the bundle does not have the same name as the pod, the app can crash with an error like this:
```
2019-06-07 17:28:34.730781+0100 ResourceBundleIssue[78655:8535426] Unknown class _TtC20WordPressUIResources24FancyAlertViewController in Interface Builder file.
Could not cast value of type 'UIViewController' (0x110579a10) to 'WordPressUI.FancyAlertViewController' (0x103b95f38).
2019-06-07 17:28:34.732146+0100 ResourceBundleIssue[78655:8535426] Could not cast value of type 'UIViewController' (0x110579a10) to 'WordPressUI.FancyAlertViewController' (0x103b95f38).
```
This is because by default storyboards have this option checked for custom classes:
Currently, the workaround is either to name the resource bundle the same …
> [PodTargetInstaller] Set Default Module for Storyboards in resource bundle targets

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/8764
During `lint`, pod authors can pass the Swift version their pod should be compiled with. However, this setting does not apply to dependencies which is fine generally. There is also no currently a way to define the `supports_swift_version` DSL since the target is completely generated and we have no way to determine the constraints unless they get passed in somehow.
This change will effectively _try_ to set the Swift version for dependencies _only if_ the original pod author has declared that they support it which should be safe to do so, otherwise we fall back to what we always did.
/cc @cnoon
> Attempt to use Swift version for dependencies during lint.

- examples/Vendored Framework Example/Podfile
Fixes the long build times because `Vendored Framework Example` didn't use CDN source so it reverted to cloning git trunk.
> fix CDN build delay

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/pod_target_spec.rb
Also adds tests for `PodTarget#inhibit_warnings?` method.
The real change is this diff in the warning message:
```diff
-The pod `BananaLib` is linked to different targets (`Pods-App1` and `Pods-App2`)...
+The pod `BananaLib` is linked to different targets (`App1` and `App2`)...
```
> Fix target definition display name for inhibit warnings message.

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/8940
This was a regression in 1.7.2 in which we never honored the `swift_version` set by the dependency spec and always defaulted to target definition Swift version.
The reason it was not caught in the prior PR it was because the test was changed also and got a false positive.
> Honor the Swift version set by a dependency pod during lint.

- lib/cocoapods/target/pod_target.rb
In https://github.com/CocoaPods/CocoaPods/pull/8963 Travis did not run causing a false positive on the build which was merged.
This fixes the failing test and CI.
> Fix failing test

- .travis.yml
Because of the terrifying size of the master spec repo, everything involving submodules had to handled in an unusual way. 
Now that it's gone, we can go back to the standard way Travis handles submodules.
> Go back to automatic submodule handling on CI

- Gemfile
- Gemfile.lock
When running the full spec suite, it is impossible to interrupt it because [Bacon](https://github.com/leahneukirchen/bacon) doesn't handle `Interrupt` gracefully.
This issue was fixed in the Bacon repo, however, no releases of Bacon were made since 2012.
This PR moves to use the `HEAD` version of Bacon so that local testing can be less painful.
> Use `HEAD` of Bacon for graceful `Interrupt` handling

- Gemfile
- Gemfile.lock
Our release process must be updated to reflect that but so far it does not and we've been lucky that `CocoaPods/1-7-stable` was successfully compiling `Core/master`. This is no longer the case so this PR manually does the right thing. Those two gems (CocoaPods and Core) move in lockstep so each time we cut a stable branch for CocoaPods we must point to the stable branch of Core, e.g. `CocoaPods/1-7-stable` must point to `Core/1-7-stable`.
> Use `1-7-stable` of Core gem

- .travis.yml
- Dangerfile
- Rakefile
This PR fixes the following issues I encountered with Danger:
1. It was not integrated in the `Rakefile` but rather has its own Travis script line.
2. The regex for triggering on `xit` and similar keywords in spec files was incorrect.
> Danger fixes

- CHANGELOG.md
- lib/cocoapods/command/init.rb
- lib/cocoapods/target/aggregate_target.rb
- lib/cocoapods/validator.rb
- spec/functional/command/init_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/8868
If a unit test target is part of a target that does not support embedding then the test target itself must embed the frameworks in order for it to run successfully. Otherwise, in common cases the app target will embed the frameworks and the unit test target loads them from there.
For UI test targets we _always_ embed because the test bundle gets wrapped in a _different_ app and not the app that is being tested.
> Fix inheriting search paths for test targets in `init` command.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/project_cache/project_cache_version.rb
- lib/cocoapods/installer/project_cache/project_installation_cache.rb
- lib/cocoapods/installer/project_cache/project_metadata_cache.rb
- lib/cocoapods/sandbox.rb
A fix here is that the `Manifest.lock` file is used as an input file for the `Check Pods Manifest Lock` script phase. Each time `pod install` runs this file is re-written causing the script phase to run again.
> Do not re-write sandbox files if they have not changed.

- CHANGELOG.md
- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
This fixes a bug during incremental installation where if an aggregate target is removed, we will not generate `Pods.xcodeproj` since the `AggregateTarget` instance doesn't exist and thus will produce a nil value in an array thereby making it empty. A result of this getting shipped was because the aggregate target test fixtures weren't setup correctly and shared the same target definition in the cache. Verified that the fixed test fails with the old code.
> Fix regenerating all aggregate targets if one is removed.

- CHANGELOG.md
- lib/cocoapods/user_interface/error_report.rb
- spec/unit/user_interface/error_report_spec.rb
When users submit issues, they are requested to run `pod repo env`.  
`CDNSource` should show up on that list.
> Make CDNSource show up in `pod repo env`

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
- lib/cocoapods/target/pod_target.rb
- spec/fixtures/watermelon-lib/UITests/WatermelonUITests.m
- spec/fixtures/watermelon-lib/WatermelonLib.podspec
- spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/single_pods_project_generator_spec.rb
- spec/unit/target/pod_target_spec.rb
requires: https://github.com/CocoaPods/Core/pull/562
This PR enables CP to generate a UI test bundle target when a test specification is defined as follows:
```ruby
s.test_spec 'UITests' |tests|
test.test_type = :ui
test.requires_app_host = true
end
```
Resolves #9001.
> Add support for UI test targets

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/9013
It will probably be for 1.7.5 release and will add a milestone.
Passing those flags in Xcode 11 Beta 4 fails to compile.
> Do not pass inhibit warnings compiler flags for Swift source files.

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/pod_target_spec.rb
This was a bug when `app_specs` were introduced.
> Only return library itself as a framework path for library specs.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/installation_options.rb
- spec/unit/installer/installation_options_spec.rb
- spec/unit/installer_spec.rb
This new option `just_download` skips the Pods.xcodeproj generation
**How to use**
In the Podfile add:
```
install! 'cocoapods', just_download: true
```
Fix: #8683
> Added option to only download Dependencies

- CHANGELOG.md
- lib/cocoapods/command/repo/push.rb
The current implementation of "repo push" can only push changes to a master branch. If the developer is using a private spec repository, a different branch could be needed.
> [repo push] Use current repo branch

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- lib/cocoapods/installer/project_cache/project_installation_cache.rb
- lib/cocoapods/installer/project_cache/project_metadata_cache.rb
- lib/cocoapods/installer/project_cache/target_cache_key.rb
- lib/cocoapods/installer/project_cache/target_metadata.rb
- lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_dependency_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
- lib/cocoapods/native_target_extension.rb
- lib/cocoapods/project.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
- spec/unit/installer/project_cache/target_cache_key_spec.rb
- spec/unit/native_target_extension_spec.rb
- spec/unit/project_spec.rb
All paths stored for the cache are now relative to the `sandbox.root`.
This way if a project is generated with incremental installation and is shared to someone else it will continue to work and the cache won't change.
See https://github.com/CocoaPods/CocoaPods/issues/8319#issuecomment-513093481
> Store relative project and file paths in the incremental cache.

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/project.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/target/pod_target_spec.rb
Even though subspecs _can_ define `deployment_target` we always pick the _max_ between library specs. That is because subspecs do not generate their own target in Xcode and are always merged into a single library target (framework or static library) so we need to pick something and we pick the _max_.
However, app specs and test specs _do_ generate an Xcode target for each (1-to-1), therefore we can honor the deployment target that is set for them. If it's not set then we pickup the one from the parent.
This PR does that.
> Use correct deployment target for test specs and app specs.

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
Depends on https://github.com/CocoaPods/Core/pull/568
> Allow overriding custom xcconfig entries set for compiling a library when specifying an app or test spec

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/sources_manager.rb
- spec/unit/installer/analyzer_spec.rb
Fixes #9015. 
This PR addresses the fact that current full-text search capabilities of CocoaPods rely on having the full text of all podspecs offline. For a CDN source, such as the Trunk, this isn't possible.
Instead, `CDNSource` uses the same Algolia index API that cocoapods.org uses.  
The configuration (API key, etc) is retrieved from the CDN server, to decouple configuration from the code.
This PR requires to be merged together with:
* [Core#569](https://github.com/CocoaPods/Core/pull/569) - most of the code!
* [Specs#14422](https://github.com/CocoaPods/Specs/pull/14422) - for the config.
Note: there's a commit that points to a fork of Core, marked `[DNM]`. It should be removed after Core PR is merged.
> Allow Algolia search for CDNSource

- lib/cocoapods/installer/analyzer/target_inspector.rb
- spec/unit/installer/analyzer/target_inspector_spec.rb
This was inspired by https://github.com/CocoaPods/CocoaPods/issues/9057 and helps consumers diagnose their problem easier.
> Print project name when a target cannot be found.

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/cocoapods/validator.rb
Using change from CocoaPods/Core#571 to address Issue CocoaPods/CocoaPods#9049
> Fix social media validation for Twitter

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
We already do this when we integrate the user targets, but we don't do it for generated pod targets.
Integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/244
> Do not add CocoaPods script phases to targets that have no paths to embed.

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- lib/cocoapods/target/build_settings.rb
- lib/cocoapods/target/pod_target.rb
- spec/fixtures/pineapple-lib/Classes/Pineapple.h
- spec/fixtures/pineapple-lib/PineappleLib.podspec
- spec/fixtures/pineapple-lib/Tests/PineappleTests.swift
- spec/fixtures/pineapple-lib/UITests/PineappleUITests.m
- spec/fixtures/watermelon-lib/WatermelonLib.podspec
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
- spec/unit/target/pod_target_spec.rb
Test specs that define a custom (non generated) app host _do not need_ to embed the frameworks or resources into their bundles because their app host will do it for them.
This reduces the size of the app bundle created since there is no duplicated framework or resource bundles present in both the test bundle _and_ the app host.
Generated app hosts (`requires_app_host = true`) _do not_ get integrated (i.e no CocoaPods script phases are created for them) therefore the unit test bundle itself will do the embedding instead. That is because users cannot customize the generated app hosts and cannot specify any dependencies or resource bundles for them.
Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/245
> Only embed frameworks and resource to app host if test spec is embedded into it.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
Fix warning generated by xcode when using a resource bundle generated by CocoaPods for a WatchOS target.
Fixes:
#9075
> Fix resource bundle warning

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/9110
Today one cannot build an app spec for device due to code signing settings being broken.
I still ultimately want to re-do the target build settings but not for the 1.8.x beta.
cc @watt
> Fix iOS app spec code signing.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
The custom "Copy Headers" phase added to preserve header mappings within a `.framework` are executed _after_ `Compile Sources`. This is generally fine but there is a case in which it can fail if the module itself imports its own header at an expected location. The header would not be copied by then causing a build failure.
This change moves these custom script phases to _always_ execute before `Compile Sources` so all headers are in the right spot before compilation.
> Move custom `Copy Headers` script phase for header mappings before `Compile Sources`.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- lib/cocoapods/installer/project_cache/project_installation_cache.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
Plugins can possibly dirty a target during installation without the core cocoapods logic knowing. If the podfile list of plugins and its inputs change, we will regenerate all pod targets.
> Support plugins for incremental installation 

- CHANGELOG.md
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/pod_target_spec.rb
Deployment target for non library spec is explicitly used if one is specified, otherwise the code used to use the one from the parent spec. However, is it not guaranteed that the parent spec has a deployment target specified.
The `analyzer` sets a default deployment target if that is the case on the `PodTarget` itself. This PR ensures we use that if the deployment target for a non library spec is `nil`.
> Correctly set deployment target for non library specs even if the root spec does not specify one.

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/gem_version.rb
No changes for CocoaPods gem. 2 fixes for Core gem in 1.8.1
> Merge `1-8-stable` (1.8.1) into `master`

- CHANGELOG.md
- lib/cocoapods/config.rb
- spec/unit/config_spec.rb
For performance reasons, mounted filesystems may make the assumption that all directories exist at the filesystem root.
This change checks to make sure that the Podfile really is a file and not a directory and prevents the subsequent crash.
> Fix crash when running on mounted filesystems

- lib/cocoapods/sources_manager.rb
This reverts commit 115187f0188f37157f4dd9c89415e9bc716ae32b.
Only affects 1.9.x (current `master`)
See discussion on why for the revert in https://github.com/CocoaPods/CocoaPods/pull/9164#issuecomment-536747408
cc @igor-makarov @igorudovika
> Revert "Check CDN repo URL procedure changed with common one"

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/pod_variant.rb
- lib/cocoapods/installer/analyzer/pod_variant_set.rb
- lib/cocoapods/target/pod_target.rb
- spec/spec_helper.rb
- spec/unit/installer/analyzer/pod_variant_set_spec.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/installer/xcode/target_validator_spec.rb
- spec/unit/target/pod_target_spec.rb
Given:
```ruby
Pod::Spec.new do |s|
s.name         = 'CannonPodder'
s.version      = '1.0.0'
s.swift_versions = ['4.0', '5.0']
end
```
and:
```ruby
target 'SampleApp' do
supports_swift_version '< 5.0'
pod 'CannonPodder'
end
target 'SecondApp' do
supports_swift_version '>= 5.0'
pod 'CannonPodder'
end
```
CocoaPods will now correctly install the above and create two different targets for each app target and its corresponding Swift version.
> Support Swift version variants.

- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/9216
> Do not crash if the repos dir is not setup.

- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/target/pod_target.rb
The bug was that we were passing in the config name instead of the type to a method that was expecting the type, and because we were constructing arrays via splats instead of `concat`, it was silently coercing `nil` to `[]`. Integration specs change shows this is fixed, exception added in dep lookup will mean this cant silently start failing again.
Fixing a regression introduced on master, hence no CHANGELOG.
> Fix app spec frameworks script

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/9288
Integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/255
> Always generate a lockfile even if project integration is disabled.

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator.rb
- spec/unit/installer/user_project_integrator_spec.rb
closes #9237
During incremental installation, if the set of `targets_to_generate` was empty and the workspace was missing, we wouldn't add the user projects to the workspace and be missing.
This changes `user_project_paths_to_integrate` to map over `targets` instead of the subset `targets_to_generate` to ensure all user projects will be added. There is existing logic to make sure that duplicate file references to user projects are removed.
> Add user projects to workspace during incremental install.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb
- spec/unit/installer_spec.rb
This will allow us to make changes to the project and schema without it getting overwritten by the pods_project_writer. #9379
> Move run_podfile_post_install_hooks call to execute right before projects are saved

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/sandbox/path_list.rb
- Uses Dir.glob instead of Find.find for faster content fetch
- Does not recalculate file system content for local pods during installation as they won't be changed by cocoapods itself anytime.
```
bundle exec pod install --clean-install  10.97s user 7.97s system 96% cpu 19.628 total
bundle exec pod install  4.91s user 4.41s system 95% cpu 9.772 total
```
```
bundle exec pod install --clean-install  6.62s user 4.12s system 86% cpu 12.453 total
bundle exec pod install  3.99s user 3.60s system 88% cpu 8.587 total
```
> path list optimizations

- lib/cocoapods/sources_manager.rb
Split from https://github.com/CocoaPods/CocoaPods/pull/9435 by @dnkoutso's request.
Also https://github.com/CocoaPods/Core/pull/610
> Lazy require Typhoeus because its load takes 300ms

- CHANGELOG.md
- lib/cocoapods/generator/copy_resources_script.rb
closes https://github.com/CocoaPods/CocoaPods/issues/9423
integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/263
> Follow symlinks during `find` command execution for xcassets.

- CHANGELOG.md
- lib/cocoapods/generator/prepare_artifacts_script.rb
Closes #9458 
Requires https://github.com/CocoaPods/cocoapods-integration-specs/pull/264
When archiving, the `.framework` slice that was placed in `Prepare Artifacts` was left in the `Products/Applications` directory of the archive because that is what `${TARGET_BUILD_DIR}` is set to when archiving. During a non-install build, the value matches that of `${CONFIGURATION_BUILD_DIR}`
> Fix an issue that caused stale framework artifacts when archiving

- CHANGELOG.md
- lib/cocoapods/installer/project_cache/target_cache_key.rb
- spec/unit/installer/project_cache/target_cache_key_spec.rb
I ran into an issue where having a (local) pod that has resources behaves incorrectly when performing an incremental install:
If a resource file (png, xib, storyboard etc.) is renamed/moved, the containing target gets regenerated. However, the aggregate target does not.
This leads to a state where the generated resource install script contains incorrect resource paths. The script fails silently, causing the build to complete and the app to crash at runtime.
This PR fixes this issue. I've added specs for the case I ran into.
> Fix a bug where an incremental install missed library resources

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- spec/unit/installer/analyzer_spec.rb
> [Analyzer] Ensure CLI dynamic lib warning only occurs when the CLI target uses dynamic linkage for its dependencies

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
- spec/spec_helper.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
See https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes
Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/266
This fixes it for both user targets that have this issue and fixes also for pod targets.
> Apply Xcode 11 `XCTUnwrap` fix to library and framework targets.

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
- lib/cocoapods/installer/xcode/pods_project_generator_result.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/installer/analyzer_spec.rb
- spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/target_installation_result_spec.rb
- spec/unit/installer/xcode/single_pods_project_generator_spec.rb
- spec/unit/target/pod_target_spec.rb
Also resolves an issue that prevented macros from expanding when included in test bundle's scheme settings (ex. using `$PODS_ROOT` within a test spec's `scheme[:environment]`)
Closes #9332
> Hook up test spec test bundles to their respective app host's test action

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/generator/prepare_artifacts_script.rb
- spec/unit/generator/prepare_artifacts_script_spec.rb
Changes:
- Ensure all dSYMs are archived, not only files that match the naming scheme of framework slices
- Correctly handle dSYM files that do not have the extension `.framework.dSYM`
- Ensure dSYMS are stored in the correct directory when archiving
Closes #9530 
Requires https://github.com/CocoaPods/cocoapods-integration-specs/pull/268
> Improve dSYM handling for XCFrameworks

- CHANGELOG.md
- lib/cocoapods/generator/prepare_artifacts_script.rb
${EFFECTIVE_PLATFORM_NAME} will only be set if applicable for the current platform.
Closes #9572
> Fix an issue when including XCFrameworks in macOS apps

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
🤦‍♂ 
Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/276
From Apple:
```
SYSTEM_FRAMEWORK_SEARCH_PATHS = "$(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks"
LIBRARY_SEARCH_PATHS = "$(inherited) $(PLATFORM_DIR)/Developer/usr/lib"
SWIFT_INCLUDE_PATHS = "$(inherited) $(PLATFORM_DIR)/Developer/usr/lib"
```
> Apply correct `SYSTEM_FRAMEWORK_SEARCH_PATHS` for `XCTUnwrap` fix.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb
- spec/unit/installer/xcode/pods_project_generator/project_generator_spec.rb
Also adds tests for `ProjectGenerator` which were non existent (was covered by single/multi pods project generators somewhat)
> Set `Missing Localizability` setting in generated pods projects

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
This PR addresses an issue happening when a pod is set to preserve local paths, e.g. a local pod.
The issue is that some file references weren't actually being preserved. Interface Builder files are a good example, these were getting put into a `Resources` group and this was very inconvenient as it placed them away from the corresponding source file. 
This PR fixes this issue by preserving ALL paths when a pod is set to preserve local paths.
Integration specs - https://github.com/CocoaPods/cocoapods-integration-specs/pull/265
> When preserving pod paths, preserve ALL the paths

- CHANGELOG.md
- lib/cocoapods/installer/sandbox_dir_cleaner.rb
- spec/unit/installer/sandbox_dir_cleaner_spec.rb
This does not happen in the very normal use cases of CocoaPods. It _can_ happen for 3rd party tools like cocoapods-generate that install the user project inside the sandbox directory and it is being picked up and cleaned.
This is good to have anyway as we want to be extra careful of not deleting/cleaning the user projects.
> Do not clean user projects from sandbox.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
I noticed that GoogleUtilities installations included a pch even though its [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/0/8/4/GoogleUtilities/6.5.2/GoogleUtilities.podspec.json#L23) includes  `"prefix_header_file": false`
The fix is to check prefix_header_file on the root podspec. Subspecs do not have separate pch files.
> Honor prefix_header_file=false for subspecs

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/target.rb
- lib/cocoapods/target/aggregate_target.rb
- lib/cocoapods/target/build_settings.rb
- spec/unit/installer/analyzer_spec.rb
As discussed in #9232, this PR checks if the `BUILD_LIBRARY_FOR_DISTRIBUTION` Build Setting evaluates to `YES` in an user target, and in that case it applies this setting to all the dependencies of this target. This is needed to avoid issues with XCFrameworks.
This also checks if `BUILD_LIBRARY_FOR_DISTRIBUTION` is set in a .xcconfig, as proposed for `APPLICATION_EXTENSION_API_ONLY` in #9233.
This is both my first PR and my first time working with Ruby, so I heavily based this PR in the previous work with the `APPLICATION_EXTENSION_API_ONLY` Build Setting. I hope I didn't miss anything critical.
BTW, thank you for your amazing work in CocoaPods!
> [Analyzer] Set BUILD_LIBRARY_FOR_DISTRIBUTION for all dependencies if it's set in the user target

- CHANGELOG.md
- lib/cocoapods/user_interface/error_report.rb
- spec/unit/user_interface/error_report_spec.rb
`pod` crashs on such a message.
```
bundler: failed to load command: pod (/Users/k_kato/work/myproject/vendor/bundle/ruby/2.5.0/bin/pod)
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
/Users/k_kato/work/myproject/vendor/bundle/ruby/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface/error_report.rb:12:in `report'
/Users/k_kato/work/myproject/vendor/bundle/ruby/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:66:in `report_error'
/Users/k_kato/work/myproject/vendor/bundle/ruby/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
/Users/k_kato/work/myproject/vendor/bundle/ruby/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
/Users/k_kato/work/myproject/vendor/bundle/ruby/2.5.0/gems/claide-1.0.3/lib/claide/co …
```
> Don't crash on non UTF-8 error message

- CHANGELOG.md
- lib/cocoapods/generator/app_target_helper.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Fixes adding developer library search paths during pod validation for pods that depend on XCTest.
cc @segiddins @dnkoutso
> Fix adding developer library search paths during pod validation

- .circleci/config.yml
Since 4d21f1c964896a1a1999c0b286d6c03f33a51132, this step no longer has any effect because [CircleCI images using macOS 10.15 (Xcode 11.2) and later no longer have the auto-switching feature enabled](https://circleci.com/docs/2.0/testing-ios/#using-ruby).
> Remove defunct step from CircleCI

- CHANGELOG.md
- lib/cocoapods/generator/copy_xcframework_script.rb
Currently, the XCFramework slice selection uses the whole folder path to select the correct slice.
This works fine when you are building the exact same ARCHS as the one in the slice. But this fails when you build less ARCHS than are in the slice, for example:
Your slice folder name is `ios-armv7_armv7s_arm64_arm64e/CoconutLib.framework`, you `$ARCHS` is `armv7 arm64`. The current code replaces all spaces with underscores, so it becomes `armv7_arm64`, it then tries to find `armv7_arm64` in the folder name, but because `armv7s` is in between, it won't find it.
This PR splits the `ARCHS` on whitespace and then tries to find a slice that contains all separate `ARCHS` in the folder name. This is a continuation of work done in #9569, #9575 and #9720.
Note that this still has an issue that the …
> Fix XCFramework slice selection when having more archs in slice than requested with $ARCHS

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Closes CocoaPods/CocoaPods#9536
Took a shot at resolving the warning.  I tried not setting the `PRODUCT_BUNDLE_IDENTIFIER` build setting when there is a `CFBundleIdentifier` set in the spec's info_plist, however an empty value will still log the warning, since the Empty String doesn't match the value in CFBundleIdentifier.
I did resolve the warning by using the `CFBundleIdentifier`  to set the build setting `PRODUCT_BUNDLE_IDENTIFIER`.  I'm unsure if this is an acceptable alteration of the target, but putting it up for review.  There's also an edge case where the Podspec configures the bundle id with both `pod_target_xcconfig` and `info_plist` and with different values; in this case the value set in `pod_target_xcconfig` will win and there will be the same warning logged.
Added a warning …
> [Pod Target Installer] Add PRODUCT_BUNDLE_IDENTIFIER to build settings when info_plist defines a bundle id

- CHANGELOG.md
- lib/cocoapods/generator/copy_dsyms_script.rb
- lib/cocoapods/generator/embed_frameworks_script.rb
- lib/cocoapods/generator/script_phase_constants.rb
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- lib/cocoapods/xcode/framework_paths.rb
- spec/unit/generator/embed_frameworks_script_spec.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
🌈 Fix for #9419
I moved the .bcsymbolmap copy command out of the Embed Frameworks phase and into the new Copy dSYMs phase that was added in #9547.
I got a good start on this but I'm not sure if I have bandwidth to take it over the finish line. I haven't used submodules before so I'm not sure how to get those changes to show up in this PR. I'm also unsure how to update the "after" folder in the integration test fixtures with a new xcproj file. Happy for a maintainer to clean this up if they are interested.
edit by dnkoutso:
integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/282
> Fix vendored .bcsymbolmap on new build system

- CHANGELOG.md
- lib/cocoapods/command/lib/lint.rb
- lib/cocoapods/command/repo/push.rb
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/validator.rb
- spec/functional/command/repo/push_spec.rb
- spec/unit/validator_spec.rb
Also fix a bad merge in the CHANGELOG.md
> Add --use-static-frameworks lint option

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
@sebastianv1 any pointers where I should look to add a test for this? I couldn't see any covering dependency wiring
> Stop adding app spec dependencies to library target in incremental installation

- CHANGELOG.md
- lib/cocoapods/command/repo/push.rb
- spec/functional/command/repo/push_spec.rb
Related issue #9833
Currently, if the trunk repo has not been set up, pushing a podspec file that depends on some libraries published in the trunk repo will fail: Unable to find a specification.
This PR adds the trunk repo to the default `sources` option value, then the trunk repo will be set up correctly before resolving dependencies when running `pod repo push` command. Like `pod install`, `pod update` or `pod lib lint` does.
I am not familiar with CocoaPods development, and this is my first Ruby code, I hope that there is no big mess. 😄
> Add the trunk repo to the default `sources` for the `repo push` command

- CHANGELOG.md
- lib/cocoapods/command/repo/update.rb
- lib/cocoapods/config.rb
- spec/functional/command/repo/update_spec.rb
- spec/unit/config_spec.rb
Excludes the local spec-repos directory (`~/.cocoapods/repos`, by default) from Time Machine Backups using `tmutil addexclusion`. Resolves #8308.
Alternatively (and ideally), the local spec-repos directory could be placed under the `~/Library/Caches` directory (which is usually excluded by Time Machine as well as many other backup applications). However, that would arguably be a more drastic change.
> Exclude the local spec-repos directory from Time Machine backups

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Resolves #9865 
Based off the logic in cocoapods-core for creating lockfiles.
```ruby
def generate_spec_repos(spec_repos)
Hash[spec_repos.map do |source, specs|
next unless source
next if specs.empty?
key = source.url || source.name
key = Pod::TrunkSource::TRUNK_REPO_NAME if source.name == Pod::TrunkSource::TRUNK_REPO_NAME
value = specs.map { |s| s.root.name }.uniq
[key, YAMLHelper.sorted_array(value)]
end.compact]
end
```
> Prevent "source changed" message for every version change when using trunk

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
integration specs PR: https://github.com/CocoaPods/cocoapods-integration-specs/pull/285
Closes #9140.
This PR changes the logic for using file lists to check the `compatibilityVersion` of the Xcode Project, instead of the `objectVersion`. 
I did notice in my own testing that changing the compatibility version from the Xcode UI did change both values.  It seems to me that only manually updating the Compatibility Version in the pbxproj file would result in a situation where either value doesn't correctly describe whether file lists can be used.
Also, the previous logic enabled file lists whenever the `objectVersion` was >= 50 (Xcode 9.3), but to the best of my knowledge .xcfilelists were introduced in Xcode 10.0 (objectVersion 51).
> [Target Integrator] check compatibilityVersion to decide when to use xcfilelists.

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
An App Clip is a standalone app, therefore frameworks need to be embedded into it.
> Add the App Clip product symbol to the list of products that need embedding

- CHANGELOG.md
- lib/cocoapods/command.rb
- lib/cocoapods/config.rb
- spec/unit/command_spec.rb
Closes #8929
Adds argument flag `--allow-root`  and environment variable `COCOAPODS_ALLOW_ROOT`
> [Command] Allow gem to run as root

- lib/cocoapods/downloader/cache.rb
```
/Users/dnkoutso/Development/ios/cocoapods-mine/lib/cocoapods/downloader/cache.rb:114: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/dnkoutso/Development/ios/cocoapods-mine/lib/cocoapods/downloader/request.rb:61: warning: The called method `slug' is defined here
/Users/dnkoutso/Development/ios/cocoapods-mine/lib/cocoapods/downloader/cache.rb:100: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/dnkoutso/Development/ios/cocoapods-mine/lib/cocoapods/downloader/request.rb:61: warning: The called method `slug' is defined here
```
> Fix a couple more 2.7.0 warnings

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
Fix #9902
integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/287
> Override Xcode 12 default for erroring on quoted imports in umbrellas

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/target.rb
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/target/aggregate_target_spec.rb
I've investigated an issue with pods as static frameworks and discovered the following problem:  
Because the pod target is of framework type, the `Copy Bundle Resources` phase actually gets executed (as opposed to static library). This means that processed resources (XIBs, storyboards etc.) are processed using the appropriate tool. Additionally, Xcode does this processing in parallel.
However, when the integration phase `[CP] Copy Pods Resources` runs, its inputs are the original resource files, like in the case of a static library. This results in the resource processing tools running again, this time serially.  
This results in duplicate work and performance penalty.
This PR solves this by converting the `[CP] Copy Pods Resources` input paths to be the framework output files (`.nib`, …
> When pod target is a static framework, save time by copying compiled resources

- Gemfile.lock
- cocoapods.gemspec
In preparation of 1.10 release and Ruby 2.7 support of Xcodeproj so there are no warnings.
> Bump minimum Xcodeproj version to 1.17.0

- Gemfile.lock
- cocoapods.gemspec
- spec/integration.rb
In preparation of 1.10 release.
Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/288
> Bump minimum version of cocoapods-downloader

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
- spec/integration.rb
Static binaries are currently being embedded into the app, this causes a Mach-O error.
[Apple Documentation](https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-TROUBLESHOOTING_BUNDLE_ERRORS-EMBEDDED_STATIC_LIBRARIES)
Addresses issue: https://github.com/CocoaPods/CocoaPods/issues/9943
> Added static binary check before embedding framework

- CHANGELOG.md
Previous link went to malfunctioning heroku app behind docs.cocoapods.org, this link harvested via cocoapods.org then clicking through to the using section
> Fix broken install link in CHANGELOG

- CHANGELOG.md
- lib/cocoapods/installer/project_cache/project_metadata_cache.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
Unfortunately, much like https://github.com/CocoaPods/CocoaPods/pull/9847 there's no existing test coverage for this area of the code
> Incremental installation works for a test host in a separate (not-regenerated) project

- .rubocop_todo.yml
- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/validator_spec.rb
If a test spec has a different deployment target than the library spec during validation this was not honored by the validator.
> Honor test spec deployment target during validation.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- lib/cocoapods/installer/project_cache/project_installation_cache.rb
- lib/cocoapods/version_metadata.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
Incremental installation does not track any installation options in the cache. Some installation options do affect project generation, so it's safer to force a clean install if any of the podfile options have changed.
> Force a clean install if installation options are changed.

- CHANGELOG.md
- lib/cocoapods/downloader.rb
- lib/cocoapods/downloader/cache.rb
Still doesn't handle concurrent installations with different versions of CocoaPods, but that's a significantly bigger change.
Fixes #10013
> [Cache] Ensure cache integrity on concurrent installations.

- CONTRIBUTING.md
If you run `bundle exec rake spec` in the root of Rainforest repo, you get the following error:
Could not locate Gemfile or .bundle/ directory
> [CONTRIBUTING.md] Fix incorrect documentation.

- CHANGELOG.md
- lib/cocoapods/generator/copy_xcframework_script.rb
This PR resolves #10026.
I don't think those changes are currently unit-testable, as it is needed to run the generated scripts to trigger the faulty behavior.
Lines 103-107 address the first example of #10026,
Line 117 addresses the second example of #10026.
> Fix XCFramework slice selection

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Local pods can change very frequently, leading to potentially hundreds of lines of non-actionable warnings
Since the pod is local, it is likely that the user installing it is the one who has added the script phases, so warning the user will only desensitize them to these warnings, which is counter-productive
> Don't print the script phase warning when installing local pods

- CHANGELOG.md
- examples/multiple test specs Example/InstallMultipleTestSpecs.xcodeproj/xcshareddata/xcschemes/TestLib.xcscheme
- examples/multiple test specs Example/Podfile
- examples/multiple test specs Example/TestLib/TestLib.podspec
- examples/multiple test specs Example/TestLib/TestLib/UnitTests5/Test5.m
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/target/build_settings.rb
- spec/functional/command/repo/list_spec.rb
- spec/functional/command/repo/push_spec.rb
- spec/functional/command/repo/update_spec.rb
- spec/spec_helper/temporary_repos.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
* Allow building app & test spec targets that depend on a library that uses
Swift without requiring an empty Swift file be present.
> Allow app/test targets to not need empty .swift files when their deps use swift

- .github/workflows/Lint.yml
- Rakefile
The obfuscated token is hard-coded into the repo because GitHub's Actions have no option to make a secret available to PRs from forks.  
This token belongs to the bot @CocoaPodsBarista and has no permissions except posting comments.  
The reason it is needed is to inform the PR author of things Danger has suggestions for.
This has been done after discussion with @orta and with reference to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/workflows/CI.yml#L25
I have also tested that Danger works by adding a change to `lib/` and then removing it.
> Danger: Put an obfuscated token right in the Rakefile 😭

- CHANGELOG.md
- lib/cocoapods/generator/copy_xcframework_script.rb
- spec/unit/generator/copy_xcframeworks_script_spec.rb
#10111 - Update XCFramework installation to support Xcode 12 debug symbols placed as siblings of the .framework inside each architecture's directory
Related integration-specs PR: https://github.com/CocoaPods/cocoapods-integration-specs/pull/301
> #10111 - Update XCFramework installation to support Xcode 12 debug symbols

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
- lib/cocoapods/target/build_settings.rb
- spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
- spec/unit/installer/xcode/single_pods_project_generator_spec.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
With the introduction of per-configuration dependencies, we cant add dependencies to 'Link Binary With Libraries' phase in Xcode because Xcode cannot differentiate between adding a dependency for only DEBUG or only RELEASE.
We rely on CocoaPods xcconfig to provide all linker flags and we maintain the part that we add dependencies in the 'Dependencies' phase as we expect them to be built so we can then embed them to targets.
@paulb777 I'd appreciate if you have the time to run this change against your Firebase CI as this code is kinda old...
This is for 1.11.0 so it will be a while before it ships.
Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/302
> Do not add dependencies to 'Link Binary With Libraries' phase.

- CHANGELOG.md
- lib/cocoapods/target.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
- spec/unit/target/aggregate_target_spec.rb
#9441 introduced an optimization for static framework pod targets by copying compiled resources (storyboards, xcdatamodels, etc) instead of the original resources and therefore avoiding duplicate work (once in the framework's `Copy Bundle Resources` phase, and another in the final target's integration phase `[CP] Copy Pods Resources`).
This optimization assumes that each `<name>.xcassets` has a compiled `<name>.car` counterpart, and that you can have many `.car` files in a single bundle.
However, in reality, all `<name>.xcassets` from the same framework are merged and compiled into a single `Assets.car`, meaning that the  `[CP] Copy Pods Resources` integration phase is failing because it's not able to find the compiled resources:
With the failing piece of code being within …
> Fix processing of xcassets resources when pod target is static framework

- CHANGELOG.md
- lib/cocoapods/command/repo/push.rb
- spec/functional/command/repo/push_spec.rb
When there are sources specified, there are some cases where the source repo is not up-to-date. One case for this is that there is a previous spec gets pushed that the current spec pending to be pushed depending on. This option only has effect if sources are specified and it does a `git pull` just like `update_repo` 
Added some spec to ensure the flag and method are set/called when this option is specified.
> Add a new option for updating sources before a podspec push action

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
Xcode 11+ will re-save projects generated by CocoaPods when localizations other than the defaults (en & Base) exist in order to update `knownRegions` on the pods project(s). This is problematic for larger projects that use multi-project generation and have a high number of pods
> Set `knownRegions` on generated projects to include all resource localization regions

- CHANGELOG.md
- lib/cocoapods/target/aggregate_target.rb
- spec/unit/target/aggregate_target_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/10206
> Fix file extension replacement for resource paths when using static frameworks

- Gemfile
- Gemfile.lock
In 1-10-stable molinillo requirements are set to ~> 0.6.6 but we are pointing to master branch in our Gemfile.
this prevents `bundle update` because master of molinillo is now 0.7.0 and it cannot be updated.
for 1-10-stable we are now updating the gemfile requirement and lock it to the 0.6.6 tag release.
> Update molinillo requirements

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/pre_integrate_hooks_context.rb
- spec/unit/installer_spec.rb
Add support for a pre-integrate hook that will allow plugins to make changes to downloaded pods before the integration into projects.
This is useful for a plugin such as a cocoapods-patch that allows users to create patch files for pod dependencies.. whose changes might include a file deletion (which needs to happen before the integration to not cause problems).
Core PR: https://github.com/CocoaPods/Core/pull/643
> Add pre-integrate hook

- spec/integration.rb
This allows us to verify scheme changes in the integration specs
> Include contents of generated projects in the integration specs

- CHANGELOG.md
- lib/cocoapods/config.rb
- lib/cocoapods/sandbox/path_list.rb
Although https://github.com/CocoaPods/Core/pull/671 looks no issue on upgrading to ActiveSupport 6
But CocoaPods has compatibility issue with AS 6.1, 
See https://github.com/rails/rails/pull/34202
This PR fix it
> Improve compatibility with as6

- CHANGELOG.md
- lib/cocoapods/validator.rb
Fix #10291
Because on the recent Twitter changes, this change allows podspecs to still validate with Twitter URLs without needing to add `--allow-warnings`.
> Change URL validation failure to a note

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/command/spec/lint.rb
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
`typhoeus` is the only blocking that prevent CocoaPods running on M1 natively
`cdn_url?` is the only place that using `typhoeus` so I just rewrite it with Ruby's `OpenURI`
WebMock dependency was updated in the `Gemfile.lock` to support testing natively bundled `OpenURI` on newer Ruby versions.
> Rewrite the only place dependent on `typhoeus`

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/functional/command/lib/list_spec.rb
- spec/functional/command/spec_spec.rb
- spec/unit/validator_spec.rb
#9760 introduced the `--configuration` flag and used it for `xcodebuild build`.  Also adopt for `xcodebuild analyze` for `pod lib lint --analyze` and `pod spec lint --analyze`
Fixes https://github.com/CocoaPods/CocoaPods/issues/10476
> Respect `--configuration` option when analyzing via `pod lib lint --analyze`

- .rubocop_todo.yml
- CHANGELOG.md
- examples/HeaderMappingsDir Example/HeaderMappingsDir Example.xcodeproj/project.pbxproj
- examples/HeaderMappingsDir Example/HeaderMappingsDir Example/AppDelegate.swift
- examples/HeaderMappingsDir Example/HeaderMappingsDirPod/HeaderMappingsDirPod.podspec
- examples/HeaderMappingsDir Example/Podfile
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Catalyst uses the macOS-style versioned framework layout, so it needs the same workaround for header_mappings_dir as macOS frameworks do. We don't know at install time if a pod will be used with Catalyst, so I made it always add the build step for iOS targets and adjusted the script to do nothing if it's running on a non-versioned framework.
I updated the things added in https://github.com/CocoaPods/CocoaPods/pull/5352 to also test the equivalent thing for iOS, but there doesn't appear to be any existing tests which verify that the end result can actually be archived. I manually tested it on both the example project and on Realm, but is there anything further I should do here test-wise?
> Fix Archive failures when using header_mappings_dir and Catalyst

- CHANGELOG.md
- lib/cocoapods/command/spec.rb
- lib/cocoapods/command/spec/cat.rb
- lib/cocoapods/command/spec/which.rb
- spec/functional/command/spec_spec.rb
This PR adds a new option to `pod spec cat` and `pod spec which` if someone might not need the latest pod spec but the one for a specific version.
> Add version option to pod spec cat and pod spec which

- CHANGELOG.md
- lib/cocoapods/sandbox/file_accessor.rb
- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings_spec.rb
Fix #10459 - a better file_accessor solution that undoes the build_settings.rb changes from #10234
Integration test companion is https://github.com/CocoaPods/cocoapods-integration-specs/pull/312
> Fix missing -ObjC for xcframeworks - take 2

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
🌈
This writes relative paths into copy dsyms script which i find very useful for projects where Pods folder is part of the repo and no `pod install` is executed on ci machine
> [Installer] use relative paths in copy dsyms script

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
closes #9906 
supersedes https://github.com/CocoaPods/CocoaPods/pull/9914
> Fix validation when subspec name starts with the name of the root spec

- CHANGELOG.md
- Gemfile.lock
- cocoapods.gemspec
closes: https://github.com/CocoaPods/CocoaPods/issues/10390
supersedes https://github.com/CocoaPods/CocoaPods/pull/10396
> Update `ruby-macho` gem version to support 1.x and 2.x.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Check podfile sources and plugin sources for warning, if the master source is added through `source_provider` hook, do't need to print the warning:
> [!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
> Check the podfile sources and plugin sources when printing warnings without explicitly using the master source.

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
This prevents Xcode from printing a warning message that an info plist file is missing on the generated app.
closes https://github.com/CocoaPods/CocoaPods/issues/8570
> Generate default `Info.plist` for consumer app during validation.

- CHANGELOG.md
- lib/cocoapods/generator/copy_dsyms_script.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/10373
when a target provides multiple vendored frameworks under the same root folder then we always scan and include all bcsymbolmap paths for all frameworks. This ensures we dedup them before we install them in the copy dSYM script phase.
> Dedup bcsymbolmap paths found from multiple vendored frameworks.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/user_interface.rb
- spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
Previously, CocoaPods would not integrate test specs or app specs of pre-built targets. We used to return early. This updates the logic to still integrate test specs and app specs even if the target has no sources to compile.
> Integrate test specs and app specs of pre-built pods.

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
Requires https://github.com/CocoaPods/Core/pull/693 to land.
> Validate vendored library names after they have been expanded.

- examples/AppCenter Example/Examples.xcworkspace/contents.xcworkspacedata
- examples/AppCenter Example/Examples.xcworkspace/xcshareddata/Examples.xcscmblueprint
- examples/AppCenter Example/Examples.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- examples/AppCenter Example/Podfile
- examples/AppCenter Example/Source/AppDelegate.swift
- examples/AppCenter Example/Source/Assets.xcassets/AccentColor.colorset/Contents.json
- examples/AppCenter Example/Source/Assets.xcassets/AppIcon.appiconset/Contents.json
- examples/AppCenter Example/Source/Assets.xcassets/Contents.json
- examples/AppCenter Example/Source/Base.lproj/LaunchScreen.storyboard
- examples/AppCenter Example/Source/Base.lproj/Main.storyboard
- examples/AppCenter Example/Source/Info.plist
- examples/AppCenter Example/Source/SceneDelegate.swift
- examples/AppCenter Example/Source/ViewController.swift
- examples/AppCenter Example/iOS Example.xcodeproj/project.pbxproj
- examples/AppCenter Example/iOS Example.xcodeproj/xcshareddata/xcschemes/iOS Example.xcscheme
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- lib/cocoapods/target/build_settings.rb
- lib/cocoapods/target/pod_target.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
This regressed (but did not ship) with https://github.com/CocoaPods/CocoaPods/pull/10826
wont add a changelog entry as this is an unshipped regression fix.
> Fix xcframework paths when multiple xcframeworks are vended from subspecs.

- CHANGELOG.md
- examples/OnDemandResources Example/Podfile
- examples/OnDemandResources Example/TestLibrary/App1/Classes/AppDelegate.swift
- examples/OnDemandResources Example/TestLibrary/App2/Classes/AppDelegate.swift
- examples/OnDemandResources Example/TestLibrary/TestLibrary.podspec
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
- lib/cocoapods/target/pod_target.rb
This PR enhances the ODR example that was added in the first PR to introduce 2 app specs and 1 test spec, showcasing integration of ODRs for all.
ODRs can only be used on app level targets. For app specs ODRs, this is easy but for test specs we only integrate the ones that the test spec has declared the app spec as its app host.
Existing tests already pass and cover most of this and the enhanced example covers the new stuff.
> Integrate ODRs for app specs.

- Gemfile.lock
- cocoapods.gemspec
1.21.0 of Xcodeproj is required for the 1.11.0 release of cocoapods as it includes support for on demand resources.
> Bump minimum Xcodeproj version to 1.21.0

- Gemfile.lock
- cocoapods.gemspec
Molinilllo 0.8.0 CHANGELOG: https://github.com/CocoaPods/Molinillo/releases/0.8.0
> Bump Molinillo version to 0.8.0

- CHANGELOG.md
- lib/cocoapods/generator/copy_xcframework_script.rb
integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/323
closes #10430
> Pass correct paths for `select_slice` method.

- lib/cocoapods/generator/copy_xcframework_script.rb
integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/325
> Even more correct xcframework paths

- CHANGELOG.md
- lib/cocoapods/generator/copy_xcframework_script.rb
closes https://github.com/CocoaPods/CocoaPods/issues/10378
integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/326
> Correctly process multiple `xcframeworks` a pod provides.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/target_validator.rb
- spec/unit/installer/xcode/target_validator_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/10912
> Do not validate modular header dependencies for pre-built Swift pods.

- .github/workflows/Lint.yml
- .github/workflows/Specs.yml
Pointing to `1-11-stable` because we are still actively working on that branch. It will be auto-merged to `master` after.
See https://github.com/actions/virtual-environments/issues/3287
> Update ubuntu to 18.04

- lib/cocoapods/config.rb
- lib/cocoapods/executable.rb
- lib/cocoapods/external_sources/abstract_external_source.rb
- lib/cocoapods/external_sources/path_source.rb
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/analysis_result.rb
- lib/cocoapods/installer/analyzer/pod_variant.rb
- lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- lib/cocoapods/installer/project_cache/target_cache_key.rb
- lib/cocoapods/installer/xcode/pods_project_generator.rb
- lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb
- lib/cocoapods/native_target_extension.rb
- lib/cocoapods/open-uri.rb
- lib/cocoapods/project.rb
- lib/cocoapods/resolver.rb
- lib/cocoapods/resolver/resolver_specification.rb
- lib/cocoapods/sandbox.rb
- lib/cocoapods/sandbox/file_accessor.rb
- lib/cocoapods/sandbox/path_list.rb
- lib/cocoapods/sources_manager.rb
- lib/cocoapods/target/pod_target.rb
- lib/cocoapods/user_interface.rb
- lib/cocoapods/validator.rb
This PR is to replace `[Bool]` with `[Boolean]` in method comments.
In the project,  `@param [Boolean]` or `@return [Boolean]` and `@param [Bool]` or `@return [Bool]` are mixed up in the method comments, so the goal is to unify them into `@param [Boolean]` or `@return [Boolean]` according to the [YARD convention](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#literals).
> Replace [Bool] with [Boolean] in method comments  according to the YARD convention.

- CHANGELOG.md
- lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/10933
cc @penelopearaujo
> Set `PRODUCT_BUNDLE_IDENTIFIER` for generated app during lint.

- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/10941
> Handle spec repo urls with user info when determining if they are CDN.

- CHANGELOG.md
- Rakefile
- lib/cocoapods/generator/info_plist_file.rb
- lib/cocoapods/target/build_settings.rb
- spec/unit/generator/info_plist_file_spec.rb
Xcode by default uses `${DEVELOPMENT_LANGUAGE}` for this value, however, there is no UI to update it. I put it behind `PODS_DEVELOPMENT_LANGUAGE` so folks can go to build settings to change it.
Integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/327
> Use `${DEVELOPMENT_LANGUAGE}` as the default `CFBundleDevelopmentRegion` value in any generated `Info.plist`.

- CHANGELOG.md
- lib/cocoapods/sandbox/file_accessor.rb
- lib/cocoapods/target/build_settings.rb
- spec/fixtures/xcframeworks/xcframework-spec.podspec
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
If an app (and its aggregate target) only consume pre-built dynamic xcframeworks (xcframeworks with slices that are dynamically linked) then we never set the `LD_RUNTIME_SEARCH_PATHS` because we only do it if any of our dependencies are dynamic or whether vendored *frameworks* are dynamic.
This PR fixes this.
> Fix setting `LD_RUNTIME_SEARCH_PATHS` for aggregate targets that include dynamic xcframeworks.

- CHANGELOG.md
- lib/cocoapods/sources_manager.rb
- spec/unit/sources_manager_spec.rb
Some services (i.e. gitlab) on https://url/repo.git/CocoaPods-version.yml will redirect to login page with http status 200.
Such response body will not be a valid YAML and throw exception.
HTML in a test case was YAML compatible, now it's a real garbage.
> [1-11-stable] cdn_url? check shouldn't crash operations. Catch YAML.load failure

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings/pod_target_settings_spec.rb
Resolves #10058
Has an integration fixture update here: https://github.com/CocoaPods/cocoapods-integration-specs/pull/329
> Fix static Swift XCFramework import paths

- CHANGELOG.md
- lib/cocoapods/installer.rb
- spec/unit/installer_spec.rb
Right now `run_podfile_post_install_hooks ` is only ran when `skip_pods_project_generation` option is set to false
I have a use case where I want to set skip_pods_project_generation to false and still run some post install hooks.
Unless there is explicit reason not to call it when skip_pods_project_generation is false, I see this as a bug? Just that few ppl ever run into my combo. (want skip_pods_project_generation + run post install hook)
TODO:
> Fix post install hooks from Podfile not ran if skip_pods_project_generation

- CHANGELOG.md
- Gemfile.lock
- cocoapods.gemspec
The problem comes from #10390 
The specific repair version of ruby-macho is 2.3.0 [ruby-macho-commit](https://github.com/Homebrew/ruby-macho/commit/f17ed3780ad15db85e5079eafd10b26f5b58c489)
> Change minimal required version of ruby-macho to 2.3.0

- CHANGELOG.md
- lib/cocoapods/generator/acknowledgements.rb
We can change the footer / header as per https://blog.cocoapods.org/Acknowledgements/
But we can't touch the license itself besides copy pasting the entire private method.
Add a method such that we can format license texts without having to copy the entire private method
> Add method for formatting licenses

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
- lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
- spec/unit/installer/analyzer/sandbox_analyzer_spec.rb
This PR landed for 1.11.x release https://github.com/CocoaPods/CocoaPods/pull/10825 which caused a side-effect in which pods inside the Podfile with explicit `source` set are not matching the sandbox manifest.
It seems the sandbox manifest does not load the spec repo when parsing dependencies from the `Manifest.lock` file.
> Do not consider `podspec_repo` when analying sandbox for changes.

- CHANGELOG.md
- lib/cocoapods/installer.rb
- lib/cocoapods/installer/installation_options.rb
- lib/cocoapods/installer/pod_source_downloader.rb
- lib/cocoapods/installer/pod_source_installer.rb
- lib/cocoapods/sandbox.rb
- spec/unit/installer/installation_options_spec.rb
- spec/unit/installer/pod_source_downloader_spec.rb
- spec/unit/installer/pod_source_installer_spec.rb
- spec/unit/installer_spec.rb
Currently, when CocoaPods installs a pod, it first downloads the pod if it's not local or already cached, and then it does the installation for the pod. It does this combined download/installation step serially for each pod that needs to be installed.
While parallelizing the pod installation process itself might be a larger effort given the potential assumptions built in throughout the codebase that installation is performed serially, we can still improve `pod install` times significantly by parallelizing the downloads.
To do this, we first need to separate the download step from the installation step, instead of doing downloading and installing at the same time for each pod. Using the opt-in `:parallel_pod_downloads` option, CocoaPods now downloads all pods in parallel, and then moves on …
> Add the ability to download pods in parallel

- CHANGELOG.md
- lib/cocoapods/generator/copy_xcframework_script.rb
Resolves #11251 
Together with https://github.com/CocoaPods/cocoapods-integration-specs/pull/334
> Fix bad warning

- CHANGELOG.md
- lib/cocoapods/installer/analyzer.rb
Given a repo that has multiple podspecs at the root, it seems all podspecs retrieve a separate instance of `PathList` which in turn calls `read_file_system` which constantly globs the entire repository.
For large repositories this can be very slow.
> Re-use the same path lists for pods that share the same root

- .github/workflows/issue-opened.yml
Example of the architecture check:
- https://github.com/orta/issue-closer-tester/issues/15
Example of the template checks:
- https://github.com/orta/issue-closer-tester/issues/12
> Adds support for auto-replying on either m1 'unrelated architecture' issues or closing default template issues

- CHANGELOG.md
- lib/cocoapods/validator.rb
- spec/unit/validator_spec.rb
As called out in #11558, publishing podspecs that support watchOS platform is currently broken under Xcode 14. Per the `xcodebuild` man page:
> To use a watchOS Simulator device as your destination ... specify the iOS Simulator platform destination that is paired with the watchOS Simulator device you want to use.
Not specifying any `-destination id=...` value and letting Xcode decide works well enough for now, though it won't have the same semantics of always choosing the oldest version available. This at least gets CocoaPods working again for pods that support watchOS.
Resolves #11558
🌈
> Fix publishing podspecs with watchOS support on Xcode 14

- CHANGELOG.md
- lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
- spec/unit/installer/analyzer/sandbox_analyzer_spec.rb
Fix issue where a deleted development pod could be marked as added if its prior directory still exists during an incremental install.
This scenario can happen when a pod has locally generated code that is gitignore'd and that pod is deleted in another branch.  After that change is merged locally and installed with incremental installation enabled, the gitignore'd files still exist on disk in the deleted pod's directory.
Swapping the order to evaluate `pod_deleted` before `pod_added` results in a correct `SpecsState` with the pod marked as deleted.
> Fix incremental installation when development pod is deleted

- CHANGELOG.md
- lib/cocoapods/xcode/xcframework.rb
- spec/unit/generator/copy_xcframeworks_script_spec.rb
Sort the order of the slices parsed from the `.xcframework`'s `Info.plist`'s `AvailableLibraries` array, so that the order of the extracted slices is consistent across multiple runs.
This is especially useful when [generating the `install_xcframeworks` script invocation](https://github.com/CocoaPods/CocoaPods/blob/4a3159879a29d076d16a20b763f61eb96406a6c1/lib/cocoapods/generator/copy_xcframework_script.rb#L166-L176) (used in the `[CP] Copy XCFrameworks` build phase), to make sure this generated shell script is consistent and stable across runs.
Without this fix, every time you re-generate a `xcframework` (using `create_xcframework` fastlane action, for example), the order of the slices generated in the `Info.plist` being arbitrary (even if you pass the arguments to `xcodebuild` in the same …
> Make xcframework's slices order stable

- lib/cocoapods/target/build_settings.rb
BuildSettings::merged_xcconfigs should not assume all config values can be regexed since that was removed in ruby 3.2
Resolves https://github.com/CocoaPods/CocoaPods/issues/11626
> fix: build_settings check for string before regex

- lib/cocoapods/installer/xcode/pods_project_generator.rb
- spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
- spec/unit/installer/xcode/single_pods_project_generator_spec.rb
Hi! 
In our team we are using CocoaPods in a highly-modularized project and we recently came across a need to specify custom build configurations for autogenerated XCSchemes, especially we want to use custom debug config for some of the schemes and a custom test build config for our unit-tests. 
We were surprised when found that this option is not supported, however [Xcodeproj](https://www.rubydoc.info/github/CocoaPods/Xcodeproj/Xcodeproj/XCScheme/AbstractSchemeAction) seems to support this. 
Further investigation turns out, this is quite a simple feature, so here we are! 
If you have any questions, feel free to ask!
> [Pods_project_generator] Added support for specifying build configurations for schemes

- CHANGELOG.md
- lib/cocoapods/generator/embed_frameworks_script.rb
🌈
Fixes the issue where archives fail when using Xcode 14.3. https://github.com/CocoaPods/CocoaPods/issues/11808
Xcode 14.3 is now using a relative path in its symlink for frameworks. Without the -f flag, this relative path would be evaluated relative to the working directory of the script being executed, instead of relative to the framework symlink itself. With the -f flag, it resolves that relative path and returns the full path to the source.
`bundle exec rake spec` failed, but it looks like maybe just because there were changes? Snapshot testing maybe? Also, it might make sense to add a test case to handle this scenario, but I don't know CocoaPods well enough to know what to add or where.
[rake.txt](https://github.com/CocoaPods/CocoaPods/files/11048739/rake.txt)
> Xcode 14.3 fix: Pass the -f option when resolving the path to the symlinked source.

- CHANGELOG.md
- lib/cocoapods/command/lib/lint.rb
- lib/cocoapods/command/repo/push.rb
- lib/cocoapods/command/spec/lint.rb
Fixes typo in a couple command options that listed `--validaton-dir` instead of `--validation-dir` in the help messages.
Resolves #11857
> Fix typo in validation for `--validation-dir` help message  

- CHANGELOG.md
- Gemfile.lock
- examples/AppCenter Example/iOS Example.xcodeproj/xcshareddata/xcschemes/iOS Example.xcscheme
- examples/Headers Example/Headers Example.xcodeproj/xcshareddata/xcschemes/Headers Example.xcscheme
- lib/cocoapods/command/spec/create.rb
- lib/cocoapods/generator/copy_resources_script.rb
- lib/cocoapods/installer/base_install_hooks_context.rb
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb
- lib/cocoapods/validator.rb
- spec/functional/command/repo/push_spec.rb
- spec/unit/validator_spec.rb
This PR introduces `visionOS` as a supported platform. This lays the groundwork for supporting visionOS as a new platform in CocoaPods.
Closes https://github.com/CocoaPods/CocoaPods/issues/11961
Related to https://github.com/CocoaPods/Core/pull/745 and https://github.com/CocoaPods/Xcodeproj/pull/913
> Add `visionos` as a new platform

- CHANGELOG.md
- lib/cocoapods/installer/user_project_integrator/target_integrator.rb
- spec/unit/installer/user_project_integrator/target_integrator_spec.rb
Exposes existing `PBXShellScriptBuildPhase` attribute for enabling it in cases where it input & output file(s) are not possible to be defined.
Without it, Xcode will always give build time warning about missing inputs & outputs.
Related to: https://github.com/CocoaPods/Core/pull/750
> Add support for always_out_of_date flag in script phase

- lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
- lib/cocoapods/installer/project_cache/target_cache_key.rb
- spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
- spec/unit/installer/project_cache/target_cache_key_spec.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/11567: for projects using `incremental_installation: true`, consuming pods were not updated when their dependencies add/rename/remove `resource_bundle`s.  When `SomePodWithResources` updates a resource bundle in its podspec, there should be a corresponding update to `ConsumingPod` in the `ConsumingPod-resources.sh` build script:
```
if [[ "$CONFIGURATION" == "Debug" ]]; then
install_resource "${PODS_CONFIGURATION_BUILD_DIR}/SamplePodWithResources/SomeBundleName.bundle"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
install_resource "${PODS_CONFIGURATION_BUILD_DIR}/SamplePodWithResources/SomeBundleName.bundle"
fi
```
-----
Notable changes:
- The cache calculation now receives a copy of the pod list so it can examine dependent pod …
> Fix incremental installation when dependent pod resources change

- .github/workflows/Lint.yml
Since [479e711](https://github.com/CocoaPods/CocoaPods/commit/479e71131962e3e560e4cc0601d39860c2a590ce) upgraded ruby to 2.7 as minimum version, lint tests are failing, as they were running on Ruby 2.6
This PR solves the current issue
> Setting ruby 2.7 to lint job

- CHANGELOG.md
- lib/cocoapods.rb
As per the official [active_support documentation](https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support), we should import the base library before the specific definitions on files.
This fixes #12081
> Requiring base active_support before definitions

- CHANGELOG.md
- lib/cocoapods.rb
A follow-up to #12082.
Shout out to @movila for [this suggestion comment].
[this suggestion comment]: https://github.com/CocoaPods/CocoaPods/issues/12089#issuecomment-1757863439
> Require active_support/core_ext in cocoapods.rb to fix #12089

- CHANGELOG.md
- lib/cocoapods/downloader.rb
- lib/cocoapods/downloader/cache.rb
- lib/cocoapods/sandbox/pod_dir_cleaner.rb
- spec/unit/downloader/cache_spec.rb
When installing pods from a given repo, we are currently over-doing a bunch of unnecessary work by copying the original repo from within a temp dir N times as many pods we are installing from that repo. We then trim (clean) the copied repo to the files that are only relevant to the pod we are installing.
This can be very slow if a repo is large and offers multiple podspecs.
We also need to do this work _only_ if there is a prepare command to run which currently operates or can operate against the initial cloned repo. 
The PR here optimizes by splitting pods that require a `prepare_command` and ones that do not. For the ones that need one we execute the existing behavior but for the ones that do not, we trim the cloned repo and then copy exactly the files we need.
This can speed up …
> Optimize performance during uncached pod installation.

- CHANGELOG.md
- lib/cocoapods/downloader/cache.rb
This prevents a copy error where the system is unable to copy the ipc file due to being a socket. This would otherwise manifest as errors during pod install with the message "too long unix socket path" if git's `core.fsmonitor` feature is enabled.
Resolves #11640
🌈
> Fix pod install issue when git's `core.fsmonitor` feature is enabled

- CHANGELOG.md
- lib/cocoapods/downloader.rb
The docs for `FileUtils.cp_r` state:
> If `remove_destination` is true, this method removes each destination file before copy.
This isn't the behavior like `rsync --delete` provides, where it removes extraneous files. Instead, [it seems like](https://public--inbox-org.translate.goog/ruby-dev/873bi0lqc0.fsf@m17n.org/T/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#t) this feature was added to Ruby to deal with cases where the file being copied over is potentially actively in use during the copy operation. Instead of overwriting the file, it'll [unlink](https://linux.die.net/man/2/unlink) the file first [here](https://github.com/ruby/ruby/blob/fb7add495454322ea00efa7549feb957cb1ca538/lib/fileutils.rb#L1047), which allows open file handles to continue accessing the old file contents. …
> Don't use :remove_destination option to `FileUtils.cp_r`

- CHANGELOG.md
- lib/cocoapods/command/lib/lint.rb
- lib/cocoapods/validator.rb
Fixes https://github.com/CocoaPods/CocoaPods/pull/11965#issuecomment-1808472679
And possibly Firebase and [RevenueCat](https://github.com/RevenueCat/purchases-ios/pull/3262#issuecomment-1743880127)
- Added `visionos` to `--platforms` in `pod lib lint`
- Changed the validator to use `xros` when passing into `Fourflusher`
- Prevents `ERROR | [visionOS] unknown: Encountered an unknown error (Could not find a `xsos` simulator (valid values: ios, tvos, watchos, xros). Ensure that Xcode -> Window -> Devices has at least one `xsos` simulator listed or otherwise add one.`  
And this is my first CocoaPods pull request so let me know if there is anything else I can do make this PR easier to merge!
> Support `visionos` in `pod lib lint --platforms=` and use `xros` for `Fourflusher`

- CHANGELOG.md
- lib/cocoapods/downloader/cache.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/12226
The underlying issue was attempting to copy a file when it already exists at the destination and does not have the write permission set, causing a write permission error.
The copy is duplicative because a previous pass had already copied a parent directory including the files. The fix is to update the logic to only copy individual files instead of also copying folders.
Note: this logic could be optimized a bit further, but I was looking for a reliable fast solution to the bug for now.
> Fix an issue attempting to re-copy the same file when the destination does not have write permissions

- CHANGELOG.md
- lib/cocoapods/downloader.rb
- lib/cocoapods/downloader/cache.rb
- lib/cocoapods/sandbox/pod_dir_cleaner.rb
- spec/unit/downloader/cache_spec.rb
Fix #12226 
It reverts #12154 and two follow on PRs.  I'm fine to discard this PR if someone comes up with a fix forward solution.
Confirms it fixes this Podfile that broke in 1.15.0:
```
platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'
target 'SymbolCollisionTest' do
use_frameworks!
pod 'GoogleAuthUtilities'
end
```
> Revert 1.15.0 regression

- CHANGELOG.md
- lib/cocoapods/downloader/cache.rb
- spec/unit/validator_spec.rb
Use rsync to exclude copying the `fsmonitor--daemon.ipc` (or anything under the `.git` directory for that matter). From the original PR #12158:
> This prevents a copy error where the system is unable to copy the ipc file due to being a socket. This would otherwise manifest as errors during pod install with the message "too long unix socket path" if git's core.fsmonitor feature is enabled.
I don't think this change was causing any of the issues that led to the revert in #12229 for the 1.15.2 release. I verified that I can reproduce the issue in #12226 against 1.15.0 and it does not reproduce against this branch.
This should again resolve #11640.
> Fix pod install issue when git's `core.fsmonitor` feature is enabled (again)

- CHANGELOG.md
- lib/cocoapods/target/build_settings.rb
- spec/unit/target/build_settings/aggregate_target_settings_spec.rb
The module verifier validates framework modularity in a clean test environment that doesn't work out of the box with the way CocoaPods framework targets are installed in `CONFIGURATION_BUILD_DIR`. Specifically, Xcode's default behaviour is to build framework bundles directly in `$(CONFIGURATION_BUILD_DIR)`, whereas pod framework targets are built in a nested directory `$(PODS_CONFIGURATION_BUILD_DIR)/PodName/`. The result is that any Xcode framework target with `ENABLE_MODULE_VERIFIER` set to `YES` will fail to locate pod framework headers when verifying modularity.
By customizing `OTHER_MODULE_VERIFIER_FLAGS`, we can add pod framework build directories to the framework search path, allowing Xcode framework targets that depend on pod framework targets to use the module verifier.
> Add Support for Xcode 14.3's ENABLE_MODULE_VERIFIER

- .github/workflows/Specs.yml
- CHANGELOG.md
- Gemfile.lock
- cocoapods.gemspec
- examples/AppCenter Example/Podfile
- examples/HeaderMappingsDir Example/HeaderMappingsDir Example.xcodeproj/project.pbxproj
- examples/HeaderMappingsDir Example/Podfile
- examples/Modules Example/Podfile
- lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
- lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
- spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb
Bump xcodeproj to [1.26.0](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0) which includes Xcode 16 support.
> Update minimum Xcodeproj version

- CHANGELOG.md
- Gemfile.lock
- cocoapods.gemspec
To address https://github.com/CocoaPods/CocoaPods/issues/12388, this PR aims to update Ruby macho to 4.1.0, which now supports Mergable libraries. The local tests i ran ran ok, but i will leave it up to the CI to check as well since bundle exec rake spec was having some issue with my ruby 3.3.0. As far as i saw comparing 2.5.1 and 4.1.0, i couldn't see a breaking change in the APIs that cocoapods uses (it is used in `linkage_analyzer.rb` and the `linkage_analyzer_spec.rb`), so no further changes needed as far as i know
> chore: bump ruby macho to 4.1.0 to enable mergable libraries
