CHANGELOG.md
lib/cocoapods/generator/copy_resources_script.rb
lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/generator/copy_resources_script_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/2391.
\c @kylef @mrackwitz

[CopyResourcesScript] Copy only the resources required for the current build configuration.

---

lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb

that way, settings from Project level in xcodeproj could be inherited.

prepended $(inherited) to OTHER_LDFLAGS and HEADER_SEARCH_PATHS to the generated xcconfig

---

CHANGELOG.md
lib/cocoapods/command/outdated.rb
spec/functional/command/outdated_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3137
\c @kylef

[Outdated] Update podfile sources

---

CHANGELOG.md
lib/cocoapods/installer.rb
spec/unit/installer_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/2943.
\c @neonichu @kylef

[Installer] Automatically detect conflicts between framework names.

---

CHANGELOG.md
lib/cocoapods/installer/migrator.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3038.
\c @neonichu @kylef

Migrate local Ruby podspecs to JSON

---

CHANGELOG.md
lib/cocoapods/sandbox/file_accessor.rb
spec/unit/sandbox/file_accessor_spec.rb

Added .tpp header support for C++ header files - so that they are symlinked into the Headers directory as well (now they're ignored.)

Add .tpp header support

---

CHANGELOG.md
lib/cocoapods.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/validator_spec.rb

Use proper TMPDIR instead of /tmp

---

CHANGELOG.md
lib/cocoapods/installer.rb
spec/unit/installer_spec.rb

Configure as extension only for watch extensions

---

CHANGELOG.md
lib/cocoapods/command.rb

fixes #3002 
reviews
it's my first PR, so please offer any advice and suggestions you might have.
although functional, this probably could use some refactoring.
i also had no idea how to write a test for this, especially since i don't currently have a machine where i haven't accepted the license agreement.

implemented Xcode license check for `pod setup`

---

CHANGELOG.md
lib/cocoapods/command/lib.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Lint as framework automatically

---

CHANGELOG.md
lib/cocoapods/project.rb
spec/unit/project_spec.rb

Replaces #2880.
@samdmarshall What do you think?

[Project] Legacy Build Location Support

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
lib/cocoapods/generator/xcconfig/private_pod_xcconfig.rb
lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
spec/unit/generator/xcconfig/private_pod_xcconfig_spec.rb
spec/unit/installer/target_installer/aggregate_target_installer_spec.rb

Set SKIP_INSTALL=YES for all generated targets

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/target_installer.rb
spec/unit/installer/target_installer_spec.rb

Include Swift-specific build settings on target creation

---

lib/cocoapods/generator/copy_resources_script.rb

Fix #3247 by adding quote to $XCASSET_FILES

---

CODE_OF_CONDUCT.md
README.md

[CoC] Adds a code of conduct, thanks for the inspiration @indirect

---

CHANGELOG.md
lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
spec/unit/installer/target_installer/aggregate_target_installer_spec.rb

As requested in #3315, an implementation on the `AggregateTargetInstaller` rather than `CopyResourcesScript`
I couldn't device a way to create a test this under AggregateTargetInstaller for this. Any help is appreciated.

[AggregateTargetInstaller] Unique resources passed to the script generator

---

lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
spec/unit/installer/target_installer/aggregate_target_installer_spec.rb

In #3327 I inadvertently broke every other test (and cocoapods) except the one I added.
In this PR I added back the line that was removed, and all tests I broke now pass.
So sorry about that.

Provide an actual path to save the script to

---

CHANGELOG.md
lib/cocoapods/installer/migrator.rb

Closes #3299.
Probably also closes #3292.
\c @kylef @ayanonagon

[Migrator] Update spec checksums in the manifest

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Do not pass code-sign arguments for OS X targets.

---

CHANGELOG.md
Gemfile
Gemfile.lock
lib/cocoapods/installer/target_installer/pod_target_installer.rb
lib/cocoapods/sandbox/file_accessor.rb
lib/cocoapods/validator.rb
spec/integration.rb
spec/unit/validator_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3003.
I've manually verified that this works with the new RealmSwift podspec, but we'll obviously need to add unit test coverage.
\c @kylef @alloy @neonichu @mrackwitz

Allow the specification of custom module map files

---

README.md

I've aimed for simpler language, directness, and more active verbs. I split the last goal in two, the latter half now in the third spot. Some of these are nontrivial! Thoughts welcome.

[README] Goal updates

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/resolver.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/resolver_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/1241.

[Analyzer] Only warn when there is a minimum deployment target mismatch

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/gem_version.rb

Merge stable-0.36 into master

---

lib/cocoapods/executable.rb

[Executable] Get rid of redundant run calls

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

[TargetIntegrator] Only embed application and unit test bundle targets

---

CHANGELOG.md
lib/cocoapods/installer/pod_source_installer.rb

Just remove write permissions from files, so executables are unaffected

---

CHANGELOG.md
lib/cocoapods/downloader.rb
lib/cocoapods/downloader/cache.rb
spec/unit/downloader/cache_spec.rb

[Downloader] Actually allow skipping the cache entirely

---

lib/cocoapods/config.rb
spec/unit/config_spec.rb

[Config] Add #with_changes

---

CHANGELOG.md
lib/cocoapods/command/repo/push.rb
spec/functional/command/repo/push_spec.rb

[pod repo push] Discover and push JSON specs while pushing from a directory

---

.travis.yml

[Travis] Only build master and stable branches

---

CHANGELOG.md
lib/cocoapods/installer/file_references_installer.rb
lib/cocoapods/sandbox/file_accessor.rb
spec/unit/installer/file_references_installer_spec.rb

Symlink vendored framework headers into the public headers dir

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/downloader/cache.rb
spec/unit/downloader/cache_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3542

[Cache] Remove cache when CocoaPods version changes

---

lib/cocoapods/command/lib.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb
spec/functional/command/spec_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3476.

[Validator] Explain why linting failed

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/command/lib.rb
spec/functional/command/lib_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/2160.

[Create] Allow passing additional args to the configure script

---

Gemfile.lock
lib/cocoapods/executable.rb
spec/unit/executable_spec.rb

Should close https://github.com/CocoaPods/CocoaPods/issues/3556.
\c @neonichu @floere

[Executable] Use readpartial instead of gets

---

spec/integration.rb

[IntegrationSpecs] Use developer tools when available

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb
spec/unit/sources_manager_spec.rb

importance of updating to the latest version when one is available

[Sourcemanager] Include a recommendation to user that highlighs the

---

lib/cocoapods/installer/analyzer.rb
lib/cocoapods/sandbox/podspec_finder.rb
spec/unit/installer/analyzer_spec.rb

This pull request depends on https://github.com/CocoaPods/Core/pull/247 and adds support for the cocoapods_version

Add support for cocoapods_version

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb

This addresses #2747 and #2704.
Integration tests need to be fixed, but I just wanted to get this looked at before I went through all that stuff.  Please let me know if I should reword or move the changelog entry.

Fix building of static libs that depend on other libs

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb

This will also filter out the top-level symlinks, which was previously causing MAS submission to fail.
\c @mrackwitz @neonichu

[EmbedFrameworksScript] Allow submitting to the MAS

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb

Always codesign if target is codesigned, not just if required.

---

CHANGELOG.md
lib/cocoapods/resolver.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/resolver_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/2443.
The code style is terrible, but I want some feedback before I try and clean this up.

[Resolver] Take supported platforms into account when resolving

---

CHANGELOG.md
lib/cocoapods/downloader.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3674

[Downloader] Run prepare_command even when skipping the cache

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer.rb

Depends upon https://github.com/CocoaPods/Xcodeproj/pull/283.
Closes some issues, I'm sure.

[Installer] Save the Pods project with deterministic UUIDs

---

CHANGELOG.md
Gemfile
Gemfile.lock
cocoapods.gemspec
lib/cocoapods/installer.rb
spec/integration.rb
spec/unit/installer_spec.rb

[Installer] Add support for default plugins

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb

[EmbedFrameworksScript] Quote all the things

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
spec/unit/generator/xcconfig/private_pod_xcconfig_spec.rb
spec/unit/generator/xcconfig/xcconfig_helper_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3537, I think? 
\c @neonichu

[XCConfig] Only include -ObjC flag when linking against a static lib

---

Gemfile.lock
spec/integration.rb

[Integration] Fix cleaning of plugin paths

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/config.rb
lib/cocoapods/installer.rb
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
lib/cocoapods/target/pod_target.rb

[Installer] Ensure no duplicate target deps are created

---

lib/cocoapods/resolver.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/2854.
\c @orta @kylef

[Resolver] Make verbose resolution less so

---

lib/cocoapods/executable.rb
lib/cocoapods/validator.rb
spec/spec_helper.rb
spec/unit/executable_spec.rb
spec/unit/generator/bridge_support_spec.rb
spec/unit/validator_spec.rb

[Executable] Dont use a subprocess for which

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3842.
\c @tapi

[AggregateXCConfig] Only include settings for the current build config

---

lib/cocoapods/generator/copy_resources_script.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3819 ?

[CopyResourcesScript] Ensure rsync target directory exists

---

lib/cocoapods/installer/target_installer/pod_target_installer.rb
spec/unit/installer/target_installer/pod_target_installer_spec.rb

This was originally from #2976.
Back then, I lost this change through a rebase and force push, just before we merged the long running swift branch into master. I somehow forgot, that I wanted to fix that. Here it is again finally.

[Frameworks] Add project/dylib/compatibility versions.

---

CHANGELOG.md
lib/cocoapods/generator/module_map.rb
lib/cocoapods/installer/target_installer/pod_target_installer.rb
lib/cocoapods/sandbox/headers_store.rb
lib/cocoapods/validator.rb
spec/functional/command/repo/push_spec.rb
spec/unit/generator/module_map_spec.rb
spec/unit/installer/target_installer/pod_target_installer_spec.rb
spec/unit/validator_spec.rb

Successor to https://github.com/CocoaPods/CocoaPods/pull/3796.
Closes https://github.com/CocoaPods/CocoaPods/issues/3878.
This is now passing (except for the integration specs, which I'll update upon merge).
This does ugly things to the validator, in the name of making its use more pleasant.
\c @tomaslinhart @neonichu @kylef

Add modules support for static libraries

---

CHANGELOG.md
lib/cocoapods/installer.rb
lib/cocoapods/installer/pod_source_installer.rb

Also, make sure to unlock the sandbox when preparing the sandbox
Closes #3529

[Installer] Delay source file locking

---

CHANGELOG.md
lib/cocoapods/command/repo/push.rb
spec/functional/command/repo/push_spec.rb

Add --sources option to push command

---

lib/cocoapods/command/spec/create.rb

Changed the default template Podspec description to be a comment.

---

lib/cocoapods/installer.rb

[Copy] Framework support is out of beta

---

examples/watchOS Example/Podfile

Closes https://github.com/CocoaPods/CocoaPods/issues/4020.

Fix watchOS Example Podfile referencing non-existent branch

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb

[TargetIntegrator] Remove embed frameworks build phase where not needed

---

CHANGELOG.md
Gemfile
Gemfile.lock
lib/cocoapods/command/lib.rb
lib/cocoapods/command/repo/lint.rb
lib/cocoapods/command/repo/push.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb

Depends upon https://github.com/CocoaPods/Core/compare/seg-linter-private-mode.
Closes https://github.com/CocoaPods/Core/issues/190.
Closes https://github.com/CocoaPods/CocoaPods/issues/2682.
\c @orta, @kylef

[Validator] Add private mode

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

Embed frameworks into app and watch extensions.

---

lib/cocoapods/installer.rb
lib/cocoapods/installer/pod_source_installer.rb

[Installer] Fix source locking/unlocking

---

lib/cocoapods/installer/target_installer/pod_target_installer.rb

[PodTargetInstaller] Mark all headers with availability levels

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/target/pod_target.rb
spec/unit/installer/analyzer_spec.rb

[Analyzer] Dont create cycles when computing transitive dependencies

---

CHANGELOG.md
lib/cocoapods/sandbox/file_accessor.rb
spec/unit/sandbox/file_accessor_spec.rb

[FileAccessor] Take exclude_files into account for resource_bundles

---

CHANGELOG.md
lib/cocoapods/installer.rb

[Installer] Print a post-install message

---

CHANGELOG.md
lib/cocoapods/installer/target_installer/pod_target_installer.rb
spec/unit/installer/target_installer/pod_target_installer_spec.rb

This fixes an issue with archiving introduced by changing header accessibility attributes.
Fixes #4119

Clear out PRIVATE/PUBLIC_HEADERS_FOLDER_PATH

---

CHANGELOG.md
lib/cocoapods/command/repo/add.rb
spec/functional/command/repo/add_spec.rb

Hi, this is my first time at coding in Ruby but wanted to give it a shot. I apologize if this is completely off.
The issue description didn't specify what to do after handling the exception so I assumed it needed to be raised as an `Informative` (not sure what else could be done).
I've also taken the liberty to do a bit of refactoring to make the main `run` method more readable.
Comments welcomed!
Thanks

[Repo Command] Handle add repo mkpath exception

---

Gemfile
Gemfile.lock
cocoapods.gemspec
lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb
lib/cocoapods/resolver.rb
spec/unit/resolver_spec.rb

See https://github.com/CocoaPods/Molinillo/blob/master/CHANGELOG.md#040-2015-07-27
\c @kylef

Update Molinillo to 0.4

---

lib/cocoapods/hooks_manager.rb

[HooksManager] Send user options as a HashWithIndifferentAccess

---

Gemfile.lock
spec/unit/sandbox/file_accessor_spec.rb

RE https://github.com/CocoaPods/Xcodeproj/pull/320

Update Xcodeproj and support .hxx headers

---

CHANGELOG.md
lib/cocoapods/command/init.rb
spec/functional/command/init_spec.rb

[Init] Only create target definitions for native targets

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

[Validator] Compile with -Wincomplete-umbrella

---

CHANGELOG.md
lib/cocoapods/generator/info_plist_file.rb
spec/unit/generator/info_plist_file_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/4421

[InfoPlistFile] Ensure the version string is exactly three dot-separated numbers

---

CHANGELOG.md
lib/cocoapods/sandbox/podspec_finder.rb
spec/unit/sandbox/podspec_finder_spec.rb

[PodspecFinder] Only consider toplevel podspecs

---

CHANGELOG.md
lib/cocoapods/generator/info_plist_file.rb
lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
spec/unit/generator/info_plist_file_spec.rb
spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
spec/unit/installer/target_installer/aggregate_target_installer_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/4426.
\c @neonichu

Set the CFBundleIdentifier using the PRODUCT_BUNDLE_IDENTIFIER build setting

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

[Validator] Allow specifying only the subspec name

---

CHANGELOG.md
lib/cocoapods/external_sources/abstract_external_source.rb
lib/cocoapods/validator.rb
spec/unit/external_sources/abstract_external_source_spec.rb

[AbstractExternalSource] Quickly validate specs

---

CHANGELOG.md
lib/cocoapods/installer/target_installer/pod_target_installer.rb
spec/unit/installer/target_installer/pod_target_installer_spec.rb

[PodTargetInstaller] Set deployment target for resource bundle targets

---

CHANGELOG.md
lib/cocoapods/generator/info_plist_file.rb
spec/unit/generator/info_plist_file_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/4514.

[InfoPlistFile] Include UIRequiredDeviceCapabilities for tvOS pods

---

CHANGELOG.md
lib/cocoapods/command.rb
lib/cocoapods/command/env.rb
lib/cocoapods/command/spec/env_spec.rb
lib/cocoapods/user_interface/error_report.rb
spec/unit/command_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/3660.

Adding pod env command to print environment

---

lib/cocoapods/user_interface.rb

Related to CocoaPods/cocoapods-search#17

Add IO type setting to UI module

---

lib/cocoapods/user_interface.rb
spec/unit/user_interface_spec.rb

Do we need a CHANGELOG for it?

[User Interface] add method to pipe outputs to a pager

---

lib/cocoapods/validator.rb

[Validator] Dont assume every pod target has a native target

---

lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Add @import UIKit; or @import Cocoa; for generated main.m

---

lib/cocoapods/external_sources/abstract_external_source.rb
lib/cocoapods/installer/target_installer/pod_target_installer.rb
spec/unit/external_sources/abstract_external_source_spec.rb

Fix issues found during Podfile testing

---

Gemfile.lock

Updates core to serialize the default platforms for specs (and the corresponding integration spec changes)

[Bundle] Update Core

---

Gemfile.lock
lib/cocoapods/generator/acknowledgements/plist.rb
spec/unit/generator/acknowledgements/plist_spec.rb
spec/unit/generator/info_plist_file_spec.rb

Just want this to run on CI before merging

[Bundle] Update Xcodeproj

---

Gemfile.lock
lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
lib/cocoapods/installer/pod_source_installer.rb
lib/cocoapods/resolver.rb
lib/cocoapods/sandbox.rb
spec/unit/generator/info_plist_file_spec.rb
spec/unit/installer/analyzer/sandbox_analyzer_spec.rb
spec/unit/installer/pod_source_installer_spec.rb
spec/unit/installer_spec.rb
spec/unit/resolver_spec.rb
spec/unit/sandbox_spec.rb

Closes #4673.
Depends upon https://github.com/CocoaPods/Core/pull/286.
@CocoaPods/core made a separate PR for this since this is a huge change. Please everyone :+1:  or :-1: this change.

Remove head dependencies

---

CHANGELOG.md
lib/cocoapods/command/outdated.rb
spec/functional/command/outdated_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/4716

[Outdated] Friendly error when no podspec present for external source deps

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/generator/info_plist_file.rb
lib/cocoapods/installer/target_installer/pod_target_installer.rb
spec/unit/generator/info_plist_file_spec.rb

See https://github.com/CocoaPods/Xcodeproj/issues/259

[InfoPlist] Generate properly for bundles

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb

closes #4783.
/cc @segiddins @OneSadCookie

Generate valid xcconfig when target includes spaces

---

lib/cocoapods/sources_manager.rb

[SourcesManager] Link directly to GH release for new version message

---

CHANGELOG.md
lib/cocoapods/installer.rb

Fixes nothing :(
@jpsim I believe this should fix your issue.

[Installer] Recreate schemes after generating deterministic UUIDs

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
spec/unit/installer/analyzer_spec.rb

[Analyzer] Fix #4751

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
lib/cocoapods/installer/analyzer/specs_state.rb
spec/unit/installer/analyzer/sandbox_analyzer_spec.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/installer_spec.rb

[SpecsState] Ensure only root names are stored

---

CHANGELOG.md
Gemfile
Gemfile.lock
spec/unit/installer/analyzer_spec.rb
spec/unit/installer/target_installer/aggregate_target_installer_spec.rb
spec/unit/installer/target_installer/pod_target_installer_spec.rb
spec/unit/installer/target_installer_spec.rb
spec/unit/installer/user_project_integrator_spec.rb
spec/unit/installer_spec.rb

Belongs to https://github.com/CocoaPods/Core/issues/299.

[Podfile] Adopt renaming from xcodeproj to project

---

CHANGELOG.md
lib/cocoapods/command/repo/lint.rb
spec/functional/command/repo/lint_spec.rb

Fix repo lint for path arguments

---

.github/ISSUE_TEMPLATE.md

I was a bit shy with my initial proposal. These bigger headings bring an underline with GitHub's stylesheets which gives the different sections better visual distinction.

[ISSUE_TEMPLATE] Bigger headings

---

Gemfile
Gemfile.lock

See https://github.com/segiddins/cocoapods-debug.

[Gemfile] Add cocoapods_debug

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb
spec/unit/sources_manager_spec.rb

[SourcesManager] Dont return non-functioning master sources

---

CHANGELOG.md
lib/cocoapods/project.rb
spec/unit/project_spec.rb

[Project] Set explicit_file_type for the added Podfile file ref

---

CHANGELOG.md
lib/cocoapods/installer/analyzer/target_inspector.rb
spec/unit/installer/analyzer/target_inspector_spec.rb

platform
Closes https://github.com/CocoaPods/CocoaPods/issues/4790.

[TargetInspector] Raise a friendly error when unable to determine

---

CHANGELOG.md
lib/cocoapods/installer/podfile_validator.rb
spec/unit/installer/podfile_validator_spec.rb

Validate no duplicate targets in Podfile

---

CHANGELOG.md
lib/cocoapods/installer/target_installer/pod_target_installer.rb
lib/cocoapods/target/pod_target.rb
spec/unit/installer/target_installer/pod_target_installer_spec.rb
spec/unit/target/pod_target_spec.rb

Fix resource bundle build path

---

CHANGELOG.md
lib/cocoapods/installer.rb

[Installer] List all found configurations when an unknown one is encountered

---

lib/cocoapods/command/init.rb

I did some [testing](https://github.com/CocoaPods/CocoaPods-app/pull/277) on our App's `pod init` and spotted a few minor issues at CocoaPods level.

Update `pod init` for 1.0

---

CHANGELOG.md
lib/cocoapods/resolver.rb
spec/unit/resolver_spec.rb

The majority of the discussion is in #5135 - for now this will handle the implementation aspects

Improve 1.0 error messages around not-found dependencies

---

lib/cocoapods/command/install.rb

Updates the install summary to be a bit more descriptive

---

.rubocop.yml
.travis.yml
Dangerfile
Gemfile
Gemfile.lock

I don't want to go overboard and try and introduce a big `Dangerfile` - so just trying to cover something I've accidentally shipped already in #5163

Introduce a danger file to check for `fit` and `fdescribe` in tests

---

Dangerfile

Fixes https://github.com/CocoaPods/CocoaPods/pull/5205#issuecomment-215090020.

[Danger] Restrict specs check to specs/

---

CHANGELOG.md
lib/cocoapods/command/repo/push.rb
spec/unit/command_spec.rb

Fix `pod repo push --help`

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
lib/cocoapods/target/pod_target.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
spec/unit/generator/xcconfig/pod_xcconfig_spec.rb
spec/unit/installer/target_installer/aggregate_target_installer_spec.rb
spec/unit/target/pod_target_spec.rb

[XCConfig] Support customized build dirs in user project

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/resolver.rb
spec/unit/installer/analyzer_spec.rb

[Resolver] Handle when an abstract target has no platform

---

CHANGELOG.md

Fixes two links in the v1.0.0.rc.1 release notes.

[CHANGELOG] Fix broken links to issues

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

[Validator] Validate that resource bundles contain resources

---

.travis.yml

[Travis] Update RubyGems

---

CHANGELOG.md
lib/cocoapods/resolver.rb
spec/unit/resolver_spec.rb

Fixes #5260 
Does this feel right? Can do tests etc then

Improve messaging when dependencies conflict

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
lib/cocoapods/target/pod_target.rb
spec/integration.rb

[PodXCConfig] Use recursive dependent targets

---

.github/ISSUE_TEMPLATE.md
.travis.yml
spec/integration.rb

[Issue Template] Update for pod env & ask for project

---

lib/cocoapods/sources_manager.rb
spec/unit/sources_manager_spec.rb

Update copy around updating to the latest build

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb

[SourcesManager] Require set before using it

---

lib/cocoapods/user_interface.rb

I also removed some whitespace.

[Docs] Remove vestigial comment

---

CHANGELOG.md
examples/HeaderMappingsDir Example/Examples.xcworkspace/contents.xcworkspacedata
examples/HeaderMappingsDir Example/HeaderMappingsDir Example.xcodeproj/project.pbxproj
examples/HeaderMappingsDir Example/HeaderMappingsDir Example.xcodeproj/xcshareddata/xcschemes/HeaderMappingsDir Example.xcscheme
examples/HeaderMappingsDir Example/HeaderMappingsDir Example/AppDelegate.swift
examples/HeaderMappingsDir Example/HeaderMappingsDir Example/Assets.xcassets/AppIcon.appiconset/Contents.json
examples/HeaderMappingsDir Example/HeaderMappingsDir Example/Info.plist
examples/HeaderMappingsDir Example/HeaderMappingsDirPod/Foo.m
examples/HeaderMappingsDir Example/HeaderMappingsDirPod/HeaderMappingsDirPod.podspec
examples/HeaderMappingsDir Example/HeaderMappingsDirPod/include/Foo.h
examples/HeaderMappingsDir Example/HeaderMappingsDirPod/module.modulemap
examples/HeaderMappingsDir Example/Podfile
lib/cocoapods/installer/target_installer/pod_target_installer.rb
spec/unit/installer/target_installer/pod_target_installer_spec.rb

Symlink the header folders in the framework bundle's root directory by script build phase if header_mappings_dir is used with frameworks.
Fixes #5313.
```shell
PUBLIC_HEADERS_FOLDER_PATH  = $(CONTENTS_FOLDER_PATH)/PrivateHeaders
PRIVATE_HEADERS_FOLDER_PATH = $(CONTENTS_FOLDER_PATH)/Headers
WRAPPER_NAME                = $(PRODUCT_NAME)$(WRAPPER_EXTENSION)
CONTENTS_FOLDER_PATH        = $(WRAPPER_NAME)/Versions/$(FRAMEWORK_VERSION)
```

Symlink header folders by script build phase

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/command/init.rb
spec/functional/command/init_spec.rb

[Init] Use target product type to determine test targets

---

CHANGELOG.md
lib/cocoapods/target/pod_target.rb
spec/unit/installer/analyzer_spec.rb

[PodTarget] Allow non-deduped targets to be frameworks

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

[Validator] Support linting pods that link against XCTest

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Use `require` instead of `autoload` for fourflusher

---

CHANGELOG.md
lib/cocoapods/resolver.rb
spec/unit/resolver_spec.rb

Fix minimum deployment target error for local pods.

---

.travis.yml
spec/integration.rb

Blocked by https://github.com/travis-ci/travis-ci/issues/5361.

[Travis] Add Ruby 2.3 to matrix

---

CHANGELOG.md
lib/cocoapods/target/pod_target.rb
spec/integration.rb
spec/unit/target/pod_target_spec.rb

[PodTarget] Make #recursive_dependent_targets handle cyclic dependencies

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

fixes https://github.com/CocoaPods/CocoaPods/issues/5250

[Installer] Embed Pods Frameworks in UI Tests

---

CHANGELOG.md
lib/cocoapods/user_interface.rb

[UI] Ensure printing a path does not raise

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb

This should fix building Pods for device using Xcode 8 beta.
Fixes #5523

Fix code signing in Xcode 8

---

CHANGELOG.md
lib/cocoapods/installer.rb
lib/cocoapods/validator.rb
spec/unit/installer_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/4014

[Installer] Verify no duplicate static libs

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

This fixes two minor issues in the script as described in the commit messages.

Fix shellscript in '📦 Check Pods Manifest.lock'

---

CHANGELOG.md
lib/cocoapods/installer.rb
spec/unit/installer_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/5517

[Installer] Print message when skipping user project integration

---

CHANGELOG.md

Also moved "Improve handling of app extensions…" back into enhancements, where I moved it during the PR

Removed extra bug fixes section in CHANGELOG.md

---

.travis.yml

See https://github.com/CocoaPods/CocoaPods/pull/5269

[Travis] Account for system ruby going from p645 -> p648

---

CHANGELOG.md
lib/cocoapods/generator/acknowledgements/plist.rb
spec/unit/generator/acknowledgements/plist_spec.rb

[Acknowledgements] Prevent crash when license type is nil

---

CHANGELOG.md

re https://github.com/CocoaPods/CocoaPods/issues/5875

Include a note in the CHANGELOG about how to lint with Swift 3.0

---

CHANGELOG.md

Should be hyphen `.swift-version` was underscore `.swift_version`. 🌈

[Readme] Minor typo

---

CHANGELOG.md
lib/cocoapods/sandbox/headers_store.rb

This fixes #5891.
This is my first contribution to CocoaPods, so please let me know if I missed anything ;)

Fix linting of private pods when using libraries

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

@orta - Would appreciate any thoughts on the message for this.

[Validator] Inform people of .swift-version on err

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/analyzer/pod_variant.rb
spec/unit/installer/analyzer/pod_variant_spec.rb
spec/unit/installer/analyzer_spec.rb

Improve handling of mismatched Swift versions

---

.gitmodules
CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer.rb

Greenify success message

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb

Only use EMBEDDED_CONTAINT_CONTAINS_SWIFT on Swift <= 2.3

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/6041

[Validator] Use Swift 3.0 by default

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb
spec/unit/sources_manager_spec.rb

**Edit (@dantoml)**
closes https://github.com/CocoaPods/CocoaPods/issues/6032

Exit with non-zero exit status if pod repo update fails

---

.travis.yml
CHANGELOG.md
Gemfile
Gemfile.lock
Rakefile
cocoapods.gemspec
lib/cocoapods/sandbox/file_accessor.rb
lib/cocoapods/validator.rb
spec/integration.rb
spec/integration/file_tree.rb
spec/unit/generator/info_plist_file_spec.rb
spec/unit/sandbox_spec.rb
spec/unit/validator_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/5724
Removes dependencies on FFI, Xcode, and macOS.
Blocked by https://github.com/CocoaPods/Xcodeproj/pull/430

Use native ruby plist serialization

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb
spec/unit/generator/embed_frameworks_script_spec.rb

This speeds up the embed frameworks script phase by 50% on my machine.

Run codesigning in parallel if COCOAPODS_PARALLEL_CODE_SIGN is set to true

---

README.md

Thought I'd submit a small PR fixing the wording for the sake of consistency!

[README] Made capitalization and wording consistent 🌈

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/project.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

completes #5441 by adding specs
closes #5427 
closes #5525

Raise an exception if unable to find a reference for a path and handle symlink references

---

CHANGELOG.md
Dangerfile
lib/cocoapods/command/spec/lint.rb
spec/functional/command/spec_spec.rb
spec/integration.rb
spec/spec_helper.rb
spec/spec_helper/webmock.rb

Also updates the integration specs so they'll pass post-sharding

[Spec::Lint] Fail gracefully when downloading podspec fails

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb

It\'s been months, time for this hack to go

[SourcesManager] Remove const_missing hack

---

CHANGELOG.md
lib/cocoapods/command.rb
spec/unit/command_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/6078

[Command] Raise when using git < 1.8.5

---

CHANGELOG.md
lib/cocoapods/command/update.rb
spec/functional/command/update_spec.rb

🌈  this is for #5807 
Again the primary example for the use of this is that, I want to update all the pods in my private Pods repo but not any from master.

[update] adding --sources to specify to only update pods from a repo

---

spec/unit/sandbox/file_accessor_spec.rb

Fixes CI, doesn't need a changelog entry.

[FileAccessor] Sort vendored_framework_headers in tests

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb

closes #6006 
Will probably need integration specs bump

Fix default LD_RUNPATH_SEARCH_PATHS for host targets

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb

Finishes #5514 
Integration specs already merged. This PR exists for CI purposes.

Add aggregated search paths targets to vendored build settings

---

CHANGELOG.md
lib/cocoapods/command/repo/push.rb

`pod repo push` now accepts the `--swift-version` argument.

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb
spec/unit/sources_manager_spec.rb

Getting sources ready for squashing of the specs repo

[Sources] reset --hard rather than git pull

---

.github/ISSUE_TEMPLATE.md

Adds a note about nanimo LoadErrors and cleans up the structure a little.

[ISSUE TEMPLATE] Add a note about Nanaimo LoadError's

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
spec/unit/generator/xcconfig/xcconfig_helper_spec.rb

closes #6065 
Tests to come and changelog

Do not link static frameworks when inheriting search paths

---

.travis.yml
Gemfile.lock
spec/unit/validator_spec.rb

shouldn't depend on changes to core

[Travis] Test Ruby 2.4

---

CHANGELOG.md
lib/cocoapods/command/lib/lint.rb
lib/cocoapods/command/repo/push.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

@segiddins this completes https://github.com/CocoaPods/CocoaPods/pull/5677
* I dont think I could have forced pushed to your branch, let me know if you want me to do that instead
* I rebased to latest and fixed conflicts
* Reverted your change for the `import_statement`
* Added a spec and updated existing ones to pass
* Added CHANGELOG entry
The committer name is still your name, because you did 99.9% of this.

[Validator] Allow skipping import validation (complete)

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

closes #6373 
completes #6393 by adding a test and extracting a method.
/cc @Westacular @benasher44

Fix resources with PBXVariantGroups outside of a resource bundle

---

CHANGELOG.md
Gemfile.lock
Rakefile
cocoapods.gemspec
lib/cocoapods/command.rb
lib/cocoapods/user_interface.rb
spec/integration.rb

Continues the work from https://github.com/CocoaPods/Xcodeproj/pull/463

Migrate to colored2 instead of unmaintained colored

---

CHANGELOG.md
lib/cocoapods/generator/info_plist_file.rb
spec/unit/generator/info_plist_file_spec.rb

closes #6193
/cc @nicolasbraun

Do not generate UIRequiredDeviceCapabilities for tvOS info plists

---

CHANGELOG.md
lib/cocoapods/generator/copy_resources_script.rb

Properly compile storyboard for watch device family

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/sources_manager.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/sources_manager_spec.rb

Hi everyone,
This is related to the issue #6525 and enables the progress while doing `pod repo update` and `pod install --repo-update`
It's my first PR, so let me know if I got everything right or I missed something.
Thanks a lot!

Provide progress when updating specs

---

CHANGELOG.md
lib/cocoapods/external_sources/abstract_external_source.rb
lib/cocoapods/sandbox/podspec_finder.rb
spec/unit/external_sources/abstract_external_source_spec.rb
spec/unit/sandbox/podspec_finder_spec.rb

Provide a better error message if a DSLError is raised

---

CHANGELOG.md
lib/cocoapods/generator/copy_resources_script.rb

Make copy resources echoes always return true

---

.github/stale.yml

Cc @orta and @dnkoutso any thoughts on wording?

[GitHub] Add probot/stale configuration

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Use unique temp folder during lint for parallel execution

---

CHANGELOG.md

[CHANGELOG] Add missing double space

---

spec/functional/user_interface_spec.rb
spec/unit/installer/analyzer/pod_variant_set_spec.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/sources_manager_spec.rb

Update specs for dependency changes

Get master green

---

lib/cocoapods/installer/xcode/target_validator.rb
lib/cocoapods/target.rb

Fix a few typos

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
lib/cocoapods/target/aggregate_target.rb
spec/unit/generator/embed_frameworks_script_spec.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb
spec/unit/installer/user_project_integrator_spec.rb
spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
spec/unit/target/aggregate_target_spec.rb

Add inputs and outputs to check manifest lock and embed framework script phases

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/target/pod_target.rb

closes https://github.com/CocoaPods/CocoaPods/issues/6765

Include test schemes within library schemes

---

CHANGELOG.md
lib/cocoapods/generator/copy_resources_script.rb

closes https://github.com/CocoaPods/CocoaPods/issues/6927

Do not use `--delete` when copying resources to app target folder

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Fix validation when using --swift-version

---

.travis.yml

See https://github.com/travis-ci/travis-ci/issues/8302

Update travis ruby versions

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

Depends on https://github.com/CocoaPods/Core/pull/389
What have I done...

Add custom shell script integration from Podfile

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7065
@paulb777 last pr to complete the script phases feature! Deals with execution position and managing that.

Integrate execution position for shell script phases

---

CHANGELOG.md
lib/cocoapods/target/aggregate_target.rb
spec/unit/target/aggregate_target_spec.rb

This is a fix for #7094 along with unit tests.

Copy resources for static frameworks

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb

Strip vendored dSYMs during embed script phase

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/target/pod_target.rb

Updating docs from https://github.com/CocoaPods/CocoaPods/pull/7147

Fix docs for prefix header paths

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
spec/unit/generator/xcconfig/xcconfig_helper_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7172

Do not propagate test spec frameworks and libraries into pod target xcconfig

---

Gemfile.lock
cocoapods.gemspec

[Gemspec] Bump Molinillo to `~> 0.6.4`

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7187

Fix unnecessary whole project recompilation

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb

Be more lenient when stripping frameworks and dSYMs for non fat binaries

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator.rb
spec/unit/installer/xcode/pods_project_generator_spec.rb

Do not link system frameworks of test specs to library targets

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb

rsync does not automatically follow file links and was silently failing to copy the fat archive
Thanks to @noppefoxwolf and @roxiemobile for trouble-shooting and raising the issue in #7207!

Fix static framework archive regression from #7187

---

CHANGELOG.md
lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
spec/unit/generator/xcconfig/xcconfig_helper_spec.rb

[XCConfigHelper] Quote framework names in OTHER_LDFLAGS

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/target/pod_target.rb
lib/cocoapods/validator.rb
spec/unit/target/pod_target_spec.rb
spec/unit/validator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7134

Integrate `swift_version` DSL support into pod targets

---

CONTRIBUTING.md

This is something that took me a few minutes to find, so let's make it easier for new people to know how to run a specific test, as that's very commonly used when preparing a PR. 
As there is a lot of potential small changes in this PR, please feel free to directly apply any changes and merge from there. Y'all have push access to my fork, making it easy to edit the text directly on GitHub.com 👍

Add information about how to run tests

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

Fix duplicate framework/resource output paths caused by the same output file name

---

CHANGELOG.md
lib/cocoapods/resolver.rb
lib/cocoapods/resolver/lazy_specification.rb
spec/unit/resolver_spec.rb

Closes #7031 by ensuring that specs are properly ordered by both version _and_ source preference.
Mostly took so long because I had to build out the test infrastructure to be able to reproduce the issue without live git repos.
cc @justinseanmartin

 [Resolver] Fix multi-source resolution

---

.github/ISSUE_TEMPLATE.md

- Replaced top quote with HTML code in case the user doesn't remove it
- Removed top instruction removal request as it's not needed anymore
- Replaced `this` with `these` so its clearer that the example on the second line must be removed too

Simplify GitHub issue template

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7362

Clear input/output paths if they exceed an arbitrary limit

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
lib/cocoapods/project.rb
lib/cocoapods/resolver.rb
lib/cocoapods/sandbox/path_list.rb
lib/cocoapods/target/pod_target.rb
spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb
spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
spec/unit/installer_spec.rb
spec/unit/sandbox/path_list_spec.rb
spec/unit/target/aggregate_target_spec.rb

Got most of these off of profiling our `pod install` times, which are currently over three minutes long.

(Not so) Small performance improvements

---

Gemfile.lock
lib/cocoapods/resolver.rb
lib/cocoapods/resolver/lazy_specification.rb

No CHANGELOG since this all unreleased code

[SpecWithSource] Rename #spec_source for consistency with LazySpecification

---

CHANGELOG.md
lib/cocoapods/installer/pod_source_installer.rb
lib/cocoapods/validator.rb
spec/unit/installer/pod_source_installer_spec.rb
spec/unit/validator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7460

Do not warn when http source uses `file:///` URI scheme

---

lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/analyzer/specs_state.rb
lib/cocoapods/installer/analyzer/target_inspector.rb
lib/cocoapods/resolver.rb
spec/unit/resolver_spec.rb

Next up will try `pod_target.rb` which will be more complicated.

Make more classes immutable

---

CHANGELOG.md
lib/cocoapods/installer/xcode/target_validator.rb
spec/unit/installer/xcode/target_validator_spec.rb

Fixes #7495 
I haven't run the tests locally, but I hope they'll pass 🙌

Fix typo when integrating Swift pods as static libraries

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

Regression caused by https://github.com/CocoaPods/CocoaPods/pull/6964

Fix iOS test native target signing settings

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Ensure `SWIFT_VERSION` is set for test only pod targets during validation

---

CHANGELOG.md
lib/cocoapods/command/update.rb

Document format of POD_NAMES in pod update

---

lib/cocoapods/sandbox/path_list.rb
spec/unit/sandbox/path_list_spec.rb

Closes #7518.
@paulb777 could you verify that this solves the issue?

Return list of files preserving given pattern order on glob

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Inhibit warnings for all dependencies during validation except for the one being validated  

---

lib/cocoapods/command/outdated.rb

Fix indent in outdated messages

---

lib/cocoapods/resolver.rb
spec/unit/resolver_spec.rb

This fixes a regression in my performance improvements PR

Fix determining whether specs are test-only when there are multiple target definitions

---

CHANGELOG.md
lib/cocoapods/generator/module_map.rb
spec/unit/generator/module_map_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7589

Remove [system] declaration attribute from generated module maps

---

lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb

For https://github.com/CocoaPods/CocoaPods/issues/7589 (Part 2)
/cc @MaximeLM

Do not force `[system]` value for custom module maps

---

CHANGELOG.md
lib/cocoapods/installer/pod_source_installer.rb
spec/unit/installer/pod_source_installer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7705
/cc @KrauseFx @larsxschneider

Warn if 'git://' protocol is used as the source of a pod

---

CHANGELOG.md
lib/cocoapods/installer/xcode/target_validator.rb
lib/cocoapods/validator.rb
spec/unit/installer/xcode/target_validator_spec.rb
spec/unit/installer_spec.rb
spec/unit/validator_spec.rb

https://github.com/CocoaPods/CocoaPods/issues/7770

Raise an error if user target `SWIFT_VERSION` is missing

---

lib/cocoapods/installer/pod_source_installer.rb
spec/unit/installer/pod_source_installer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7790
Tried `git@code.byted.org:ugc/OpenCV.git` from the issue and it worked.
/cc @Whirlwind

Fix source validation for local URLs and SSH repos

---

lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/pod_target_settings_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7798

Correctly merge pod target xcconfigs for pod target build settings

---

lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb

#1216 #7793
It seem that the code is missing.

Exclude `USE_HEADERMAP`

---

lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/target/build_settings.rb
lib/cocoapods/target/pod_target.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb
spec/unit/target/build_settings/pod_target_settings_spec.rb
spec/unit/target/build_settings_spec.rb

Another incremental step for https://github.com/CocoaPods/CocoaPods/issues/7573
Changes 0 logic just prepares for future changes.

Pass the test spec build settings are intended for

---

lib/cocoapods/installer/pod_source_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb
lib/cocoapods/sandbox/file_accessor.rb
spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
spec/unit/sandbox/file_accessor_spec.rb
spec/unit/validator_spec.rb

Used the built in support for ruby-prof to try and profile some of the heavy areas. I plan to do some more but need to get a better test project to measure the performance changes with.
@dnkoutso 
@segiddins can you try this with one of your projects?

Performance improvements & refactoring

---

lib/cocoapods/installer.rb
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/analyzer/analysis_result.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/installer/xcode/pods_project_generator_spec.rb
spec/unit/installer_spec.rb

cc @amorde 
This should also help performance a bit

Only calculate Installer#pod_targets once

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Warn instead of error when `public_header_files` or `private_header_files` do not match any files

---

CHANGELOG.md
lib/cocoapods/installer.rb
spec/unit/installer_spec.rb

saw this https://twitter.com/rickbdotcom/status/1011275123599527937
And decided to handle it.

Do not display a source was changed if it uses different casing

---

CHANGELOG.md
examples/Alamofire Example/iOS Example.xcodeproj/project.pbxproj
examples/HeaderMappingsDir Example/HeaderMappingsDir Example.xcodeproj/project.pbxproj
examples/Modules Example/iOS Modules.xcodeproj/project.pbxproj
examples/Modules Example/macOS Modules.xcodeproj/project.pbxproj
examples/Resource Bundle Example/Resource Bundle Example.xcodeproj/project.pbxproj
examples/TestInclusions/TestInclusions.xcodeproj/project.pbxproj
examples/Vendored Framework Example/Vendored Framework Example.xcodeproj/project.pbxproj
examples/watchOS Example/watchOSsample.xcodeproj/project.pbxproj
lib/cocoapods/target/aggregate_target.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb
spec/unit/library_spec.rb
spec/unit/target/aggregate_target_spec.rb

Keep all script path is relative the Pods folder, rather than `SRCROOT`. So we could use the symlink of `Pods` folder.
This is a separate PR for #7781.

change shell script relative path to ${PODS_ROOT} instead of ${SRCROOT}/Pods

---

CHANGELOG.md
lib/cocoapods/external_sources/abstract_external_source.rb
spec/unit/external_sources/abstract_external_source_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7625

Always display downloader error message

---

CHANGELOG.md
lib/cocoapods/command/repo/push.rb
spec/functional/command/repo/push_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7926

Do not ignore `--no-overwrite` parameter if a commit message is specified

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/target/pod_target.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7950

Set the `SWIFT_VERSION` on resource bundle targets that contain compiled sources and use Swift

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
spec/unit/installer/analyzer_spec.rb

Fixes #7148 
Requires https://github.com/CocoaPods/cocoapods-integration-specs/pull/174

Require 64-bit architectures for iOS 11.0 and up

---

examples/multiple test specs Example/TestLib/TestLib.podspec
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/target/build_settings.rb
lib/cocoapods/target/pod_target.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
spec/unit/target/pod_target_spec.rb

Fix recent regressions with app hosts, test specs, & modular headers

---

CHANGELOG.md
lib/cocoapods/sandbox/file_accessor.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/7867

Use `require` for MachO instead of `autoload`

---

lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/target/pod_target.rb
lib/cocoapods/validator.rb
spec/fixtures/watermelon-lib/Tests/WatermelonSwiftTests.swift
spec/fixtures/watermelon-lib/WatermelonLib.podspec
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
spec/unit/target/pod_target_spec.rb
spec/unit/validator_spec.rb

This can wait for 1.6.0.beta.1 to ship.

Correctly scope Swift language for each test spec

---

lib/cocoapods/installer/analyzer/analysis_result.rb

"Use `attr_reader` in `analysis_result`

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
spec/unit/installer/analyzer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/8011

Scope embedded pods to their host targets by their configuration

---

CHANGELOG.md
lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/7872
/cc @Whirlwind

Fix `weak_frameworks` missing regression.

---

CHANGELOG.md
lib/cocoapods/command/outdated.rb
lib/cocoapods/installer/analyzer.rb
spec/integration.rb

closes https://github.com/CocoaPods/CocoaPods/issues/8025

Fix running pod outdated with externally sourced pods

---

CHANGELOG.md
lib/cocoapods/project.rb
spec/unit/project_spec.rb

Use 2 space indentation from ruby guide

mark_ruby_file_ref add indent width and tab width config

---

CHANGELOG.md
lib/cocoapods/command/cache/clean.rb

Quick fix for this issue on the website:

Wording hack to fix rendering on website

---

CHANGELOG.md
lib/cocoapods/installer/installation_options.rb
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
spec/unit/installer/installation_options_spec.rb

Make user can keep folder structure by add "keep_folder_structure" into Podfile
I know this is not a good practice.
What is the correct way?

Provide an installation option to preserve folder structure

---

.gitmodules
CHANGELOG.md
lib/cocoapods/generator/app_target_helper.rb
lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/app_host_installer_spec.rb

Nests test specs host apps inside that Pod's directory for cleaner project navigators.

---

CHANGELOG.md
lib/cocoapods/validator.rb

Fix #8129
I verified the bug report is fixed by this. If unit tests are needed, I'd appreciate tips on the right approach.

Fix linting when armv7 is included but i386 isn't

---

lib/cocoapods/sandbox.rb

Always set the JSON checksum on first install

---

CHANGELOG.md
lib/cocoapods/installer/installation_options.rb
lib/cocoapods/installer/pod_source_installer.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/8198
Closes https://github.com/CocoaPods/guides.cocoapods.org/issues/142
I took an initial pass at this with the knowledge I have, but could use some help verifying these

[Installer] Add documentation for installation options

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/analyzer/pod_variant.rb
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
lib/cocoapods/resolver.rb
lib/cocoapods/resolver/resolver_specification.rb
lib/cocoapods/target/aggregate_target.rb
lib/cocoapods/target/build_settings.rb
lib/cocoapods/target/pod_target.rb
lib/cocoapods/validator.rb
spec/functional/command/init_spec.rb
spec/unit/installer/analyzer/pod_variant_set_spec.rb
spec/unit/installer/analyzer/pod_variant_spec.rb
spec/unit/installer/analyzer/target_inspector_spec.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/installer/xcode/pods_project_generator/app_host_installer_spec.rb
spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb
spec/unit/installer_spec.rb
spec/unit/resolver_spec.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb
spec/unit/target/build_settings/pod_target_settings_spec.rb
spec/unit/target/build_settings_spec.rb
spec/unit/target/pod_target_spec.rb

App spec integration into cocoapods

---

.gitmodules

See https://github.com/CocoaPods/CocoaPods/commit/2be7f2912f31485b72e32c5cf18ab76eea5cef1e#r31073029
/cc @Whirlwind

Fix submodule branch reference

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/xcode/target_validator.rb
lib/cocoapods/project.rb
lib/cocoapods/target/pod_target.rb
lib/cocoapods/validator.rb
spec/fixtures/multi-swift/MultiSwift.podspec
spec/fixtures/multi-swift/Source/MultiSwift.swift
spec/unit/installer/xcode/target_validator_spec.rb
spec/unit/target/pod_target_spec.rb
spec/unit/validator_spec.rb

Requires https://github.com/CocoaPods/Core/pull/467
closes https://github.com/CocoaPods/CocoaPods/issues/8191
Note: This PR does not add Swift variants (i.e splitting pods across Swift versions) it maintains the status quo and ensures validation occurs.

Multiple Swift versions support

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/app_host_installer_spec.rb

- App specs should not add main

Add option to app host installer whether or not ot add a main

---

CHANGELOG.md

[fixes accidental changes in the changlelog]

update in changelog

---

CHANGELOG.md
lib/cocoapods/config.rb
spec/unit/config_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/8171
Requires https://github.com/CocoaPods/Core/pull/471

[Config] Add support for .rb extension for Podfiles

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
spec/unit/installer/analyzer_spec.rb

[Analyzer] Do not force 64-bit architectures on Xcode 10 or higher

---

CHANGELOG.md
lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb
spec/unit/target/build_settings/pod_target_settings_spec.rb

Remove unnecessary linker flags from pod targets

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator_result.rb
lib/cocoapods/target/pod_target.rb
spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
spec/unit/installer/xcode/single_pods_project_generator_spec.rb
spec/unit/target/pod_target_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/7577
Requires https://github.com/CocoaPods/Core/pull/475

Scheme configuration support

---

lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/pod_target_settings_spec.rb

Fix #8333 - a regression introduced in #8314 
Let me know if this is reasonable and I'll update the integration tests

Fix OTHER_LDFLAGS regression

---

CHANGELOG.md
lib/cocoapods/target/build_settings.rb

Fix runpath_search_paths for inherit search_path targets

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb

This was missed by review https://github.com/CocoaPods/CocoaPods/pull/8222#discussion_r247291889

Fix setting correct resource `xcfilelist` paths for pod targets

---

CHANGELOG.md
lib/cocoapods/command/list.rb

the detailed error information is `undefined method `new' for ["list", "--update", "--verbose"]:Array`

FIX error when execute pod list --update --verbose command

---

lib/cocoapods/command/lib/lint.rb

complete pod lib lint command help banner

---

examples/multiple test specs Example/Podfile
lib/cocoapods/command/init.rb
spec/functional/command/init_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/8399 . Let me know if this message looks good, and also if the code formatting is good. I will then test it and update the tests that would be affected by it.

Provide more information about use_frameworks! in the auto-generated Podfile

---

.github/ISSUE_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
lib/cocoapods/command/lib/create.rb
lib/cocoapods/command/spec/create.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/open-uri.rb
lib/cocoapods/user_interface.rb
lib/cocoapods/user_interface/inspector_reporter.rb
spec/fixtures/orange-framework/.gitignore
spec/functional/command/lib/create_spec.rb

I've followed all the http: links to see if they redirect to https and I've updated accordingly.
I've ignored the Changelog file, as there were too many links.

http -> https

---

CHANGELOG.md
Gemfile.lock

This right after release of 1.6.0.rc.2

Merge `1-6-stable` into `master`

---

lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/8484
Regressed on https://github.com/CocoaPods/CocoaPods/commit/2401391d9b1c278802542c8a4c8c56d492d832d3#diff-7f0b2bce7920a8edef5824debd63ffabR92 due to a missing test that exercises this logic.

Fix validator from crashing during test spec validation

---

CHANGELOG.md
lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/pod_target_settings_spec.rb

closes #8493
Verified consuming the pod in the issue properly works.
Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/213

Properly link system frameworks and weak frameworks into dynamic framework targets.

---

CHANGELOG.md
lib/cocoapods/command/repo/add.rb
lib/cocoapods/command/repo/list.rb
lib/cocoapods/command/repo/push.rb
lib/cocoapods/command/spec/create.rb
lib/cocoapods/executable.rb
lib/cocoapods/sources_manager.rb
spec/functional/command/repo/add_spec.rb
spec/functional/command/repo/list_spec.rb
spec/functional/command/repo/update_spec.rb
spec/spec_helper/temporary_repos.rb

[Repo::Add] Fix file:// URLs on Ruby 2.6

---

lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/8033
Closes https://github.com/CocoaPods/CocoaPods/issues/8497

Merge xcconfig from inherited targets

---

CHANGELOG.md
lib/cocoapods/target/build_settings.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb
spec/unit/target/build_settings/pod_target_settings_spec.rb

Includes https://github.com/CocoaPods/CocoaPods/pull/8500 and https://github.com/CocoaPods/CocoaPods/pull/8498

Merge 1-6-stable (1.6.1) into master (1.7.0)

---

Gemfile.lock
cocoapods.gemspec

[Gemspec] Bump ruby-macho to '~> 1.4'

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

closes #8296
requires: https://github.com/CocoaPods/cocoapods-integration-specs/pull/217 and https://github.com/CocoaPods/cocoapods-deintegrate/pull/35

Clean up old integrated framework references.

---

lib/cocoapods/target/pod_target.rb

Handles post-merge comment at https://github.com/CocoaPods/CocoaPods/pull/8456#discussion_r251222833

Update ivar name

---

CHANGELOG.md
lib/cocoapods/target/framework_paths.rb
lib/cocoapods/target/pod_target.rb
spec/unit/target/framework_paths_spec.rb
spec/unit/target/pod_target_spec.rb

Follow up on https://github.com/CocoaPods/CocoaPods/pull/8470 /cc @dacaiguoguogmail

Follow up improvements for `bcsymbolmap` paths

---

Gemfile.lock
cocoapods.gemspec

This is the merge for the 1.6.1 release.

Merge 1-6-stable into master

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

cc @florianbuerger does this look correct to you?

Include `bcsymbolmap` file output paths into script phase.

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb

Fix: unset GIT_DIR and GIT_WORK_TREE for git operations #7958

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

Needs https://github.com/CocoaPods/Core/pull/517

Integrate `xcfilelist` input/output paths for script phases.

---

CHANGELOG.md
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Validator should filter our app specs from subspec analysis.

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/gem_version.rb

This is due to release of 1.7.0.beta.2.

Merge `1-7-stable` into `master`

---

lib/cocoapods/installer/podfile_validator.rb
spec/unit/installer/podfile_validator_spec.rb

Changed the wording of the error string when multiple targets are declared
Updated tests

[podfile_validator] Changed wording from 'twice' to 'multiple times'

---

CHANGELOG.md
lib/cocoapods/config.rb
spec/unit/config_spec.rb

closes #8515 
cache_root read from config.yaml is a string

Fix set cache_root from config file error #8515

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

Fix regression not compiling xcdatamodeld files in static frameworks

---

CHANGELOG.md
Gemfile.lock
Rakefile
examples/multiple test specs Example/HostedTestLib/App/AppDelegate.swift
examples/multiple test specs Example/HostedTestLib/HostedTestLib.podspec
examples/multiple test specs Example/HostedTestLib/UnitTests3/HostedTestLib3Tests.swift
examples/multiple test specs Example/HostedTestLib/UnitTests4/HostedTestLib4Tests.swift
examples/multiple test specs Example/InstallMultipleTestSpecs.xcodeproj/project.pbxproj
examples/multiple test specs Example/InstallMultipleTestSpecs.xcodeproj/xcshareddata/xcschemes/Test_HostedTestLib.xcscheme
examples/multiple test specs Example/Podfile
examples/multiple test specs Example/TestLib/TestLib.podspec
examples/multiple test specs Example/TestLib/TestLib/App/AppDelegate.swift
examples/multiple test specs Example/TestLib/TestLib/UnitTests1/Test1.swift
examples/multiple test specs Example/TestLib/TestLib/UnitTests2/Test2.swift
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/target_installation_result.rb
lib/cocoapods/resolver.rb
lib/cocoapods/target/build_settings.rb
lib/cocoapods/target/pod_target.rb
spec/spec_helper/mock_source.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
spec/unit/installer/xcode/single_pods_project_generator_spec.rb
spec/unit/resolver_spec.rb
spec/unit/target/pod_target_spec.rb

NEEDED:
See cocoapods/core#520

Use app spec as app host for test specs.

---

lib/cocoapods/installer.rb
lib/cocoapods/installer/xcode/target_validator.rb
lib/cocoapods/resolver.rb

Speeds up resolution even more, mostly by reducing graph traversals down to a single iteration through every vertex

More resolver performance improvements

---

Gemfile.lock

Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/227

Update dependency to xcodeproj

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/gem_version.rb
lib/cocoapods/generator/info_plist_file.rb
lib/cocoapods/installer/xcode/multi_pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_dependency_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/project.rb
lib/cocoapods/resolver.rb
lib/cocoapods/target/pod_target.rb
lib/cocoapods/version_metadata.rb
spec/unit/generator/info_plist_file_spec.rb
spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
spec/unit/installer_spec.rb
spec/unit/project_spec.rb
spec/unit/resolver_spec.rb
spec/unit/target/pod_target_spec.rb

Integration specs 1-7-stable -> master PR is here https://github.com/CocoaPods/cocoapods-integration-specs/pull/228

Merge 1-7-stable into master

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
spec/unit/installer/analyzer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/8608

Ensure all embedded pod targets are copied over to the host target.

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/target.rb
spec/fixtures/Sample Extensions Project/Sample Extensions Project.xcodeproj/project.pbxproj
spec/fixtures/Sample Extensions Project/SampleCommandLineTool/main.swift
spec/unit/installer/analyzer_spec.rb

[Analyzer] Warn when integrating dynamic frameworks into CLI targets

---

CHANGELOG.md
lib/cocoapods/sandbox/pod_dir_cleaner.rb

…ct when file count is very large

Addressing (#8797) issue

---

CHANGELOG.md
lib/cocoapods/command/lib/lint.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Add --analyze option for the linters

---

spec/unit/installer/xcode/target_validator_spec.rb

No logical changes in this PR. Just updating the tests to be more correct as I have found they were not in another PR of mine.
No changelog entry needed and targeting master.

Update target validator specs to point to the right project path.

---

CHANGELOG.md

CHANGELOG only diff is correct.

Merge 1-6-stable (1.6.2) branch into 1-7-stable

---

Gemfile.lock

~I expect the first PR to fail due to integration specs.~ It did. Updated.

Update Core dependency

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/gem_version.rb
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/target/pod_target.rb
spec/fixtures/watermelon-lib/WatermelonLib.podspec
spec/unit/installer/analyzer_spec.rb

Integration specs PR https://github.com/CocoaPods/cocoapods-integration-specs/pull/232

Merge 1-7-stable (1.7.0.rc.2) into master

---

CHANGELOG.md
lib/cocoapods/generator/embed_frameworks_script.rb

closes https://github.com/CocoaPods/CocoaPods/issues/8827
/cc @benasher44 @steipete

Update dSYM stripping string matcher for 64-bit only dSYMs.

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/gem_version.rb
lib/cocoapods/generator/embed_frameworks_script.rb

Two integration specs PRs:
CocoaPods/cocoapods-integration-specs#234 (from merging integration specs repo 1-7-stable into master)
CocoaPods/cocoapods-integration-specs#235 for the added integration specs that need this change.

Merge 1-7-stable (1.7.0) into master (Take 2)

---

CHANGELOG.md
lib/cocoapods/installer/sandbox_dir_cleaner.rb
lib/cocoapods/installer/target_uuid_generator.rb
lib/cocoapods/target/pod_target.rb
lib/cocoapods/version_metadata.rb
spec/unit/installer/sandbox_dir_cleaner_spec.rb
spec/unit/installer/target_uuid_generator_spec.rb
spec/unit/target/pod_target_spec.rb

Should also fix https://github.com/CocoaPods/CocoaPods/issues/8850

Merge `1-7-stable` (1.7.1) into `master`

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator.rb
lib/cocoapods/target/pod_target.rb
spec/unit/target/pod_target_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/8880

Prevent crash when configuring schemes for subspecs.

---

Gemfile.lock
cocoapods.gemspec

For 1.10.0 release of Xcodeproj gem which includes support for Xcode 11.

Update Xcodeproj gem dependency

---

CHANGELOG.md
lib/cocoapods/installer.rb
lib/cocoapods/installer/pod_source_installer.rb
lib/cocoapods/sandbox.rb
spec/unit/installer/pod_source_installer_spec.rb
spec/unit/sandbox_spec.rb

Supersedes https://github.com/CocoaPods/CocoaPods/pull/8826

Clean stale local podspec

---

CHANGELOG.md
lib/cocoapods/target/pod_target.rb
spec/unit/target/pod_target_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/8850 (again)

Handle scheme configuration for specs with unsupported platforms.

---

CHANGELOG.md
lib/cocoapods/installer.rb
lib/cocoapods/installer/project_cache/project_cache_analyzer.rb
lib/cocoapods/installer/project_cache/target_cache_key.rb
lib/cocoapods/installer/sandbox_dir_cleaner.rb
lib/cocoapods/installer/xcode/multi_pods_project_generator.rb
lib/cocoapods/installer/xcode/target_validator.rb
lib/cocoapods/target/pod_target.rb
spec/unit/installer/project_cache/project_cache_analyzer_spec.rb
spec/unit/installer/project_cache/target_cache_key_spec.rb
spec/unit/installer/sandbox_dir_cleaner_spec.rb
spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
spec/unit/installer/xcode/target_validator_spec.rb
spec/unit/target/pod_target_spec.rb

Requires https://github.com/CocoaPods/Core/pull/547

Integrate a pod into a custom project name if specified.

---

CHANGELOG.md
lib/cocoapods/sources_manager.rb
spec/unit/sources_manager_spec.rb

Improve heuristic for determining whether the source URL to be added is CDN

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb

Wasn't sure where I could add specs for checking the compiled output?

Update symlink script to prevent duplicate files

---

Gemfile.lock

PR to accompany CocoaPods/cocoapods-integration-specs#240.

Update xcodeproj gem and integration specs

---

spec/integration.rb

Accompanying PR to CocoaPods/cocoapods-integration-specs#241.

Add header mappings spec for macOS

---

CHANGELOG.md
lib/cocoapods/config.rb
lib/cocoapods/installer.rb
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/resolver.rb
lib/cocoapods/sources_manager.rb
spec/functional/command/outdated_spec.rb
spec/unit/installer/analyzer_spec.rb
spec/unit/installer_spec.rb
spec/unit/sources_manager_spec.rb

Closes #8540
@fabiopelosin could you try this out on your project to confirm that it resolves the issue you are experiencing?

[Analyzer] Ensure plugin sources are added to the sources manager

---

lib/cocoapods/generator/embed_frameworks_script.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
lib/cocoapods/target/aggregate_target.rb

Feedback from https://github.com/CocoaPods/CocoaPods/pull/9069/files#r309414109

Use `each_value` instead of `values`

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/9082

Add support for integrating dependency file in user script phases.

---

Gemfile.lock
cocoapods.gemspec

Due to https://github.com/CocoaPods/CocoaPods/issues/9112

Update cocoapods-trunk gem minimum version requirement

---

lib/cocoapods/command/setup.rb
spec/functional/command/setup_spec.rb

Closes https://github.com/CocoaPods/CocoaPods/issues/9184

Print out a message when setup is completed.

---

lib/cocoapods/sources_manager.rb

Very small improvement that will simplify resolve https://github.com/CocoaPods/CocoaPods/issues/9151 issue

Check CDN repo URL procedure changed with common one

---

CHANGELOG.md

There was an extraneous `(` which prevented it to render properly.

Fix link to issue in changelog

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator.rb
spec/unit/installer/xcode/multi_pods_project_generator_spec.rb
spec/unit/installer/xcode/single_pods_project_generator_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/8921

Support for scheme code coverage.

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/analyzer.rb
spec/unit/installer/analyzer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/9233

Search in users xcconfig's for figuring out when to set `APPLICATION_EXTENSION_API_ONLY`.

---

.rubocop_todo.yml
Gemfile
Gemfile.lock
lib/cocoapods/sources_manager.rb
spec/unit/sources_manager_spec.rb

Added body content check in order to detect CDN repo. This will allow to avoid false positive request results

Changed CDN repo detection

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/fixtures/HeadersMappingSubspec/HeadersMappingSubspec.podspec
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/9308
@drcapulet can you also take a look that this seems correct to you?

Do not apply header mapping copy if the spec does not provide a header mappings dir.

---

.travis.yml
CHANGELOG.md
lib/cocoapods/validator.rb
spec/functional/command/repo/push_spec.rb
spec/integration.rb
spec/unit/executable_spec.rb
spec/unit/validator_spec.rb

Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/261

Fix validator to properly integration project during `lint`.

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

Fix pod install crash on projects with atypical configuration names

---

lib/cocoapods/generator/copy_dsyms_script.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb

Follow up for https://github.com/CocoaPods/CocoaPods/issues/9185

Follow up fix to use `DWARF_DSYM_FOLDER_PATH` instead.

---

lib/cocoapods/generator/prepare_artifacts_script.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb

Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/271

Fix syntax error with dSYM revamp, remove duplicate method.

---

CHANGELOG.md
lib/cocoapods/generator/prepare_artifacts_script.rb

Fix an issue that prevented the correct XCFramework slice from being selected for watchOS extensions

---

CHANGELOG.md
lib/cocoapods/installer/analyzer/target_inspection_result.rb
spec/unit/installer/analyzer/target_inspector_spec.rb

Fix #6268 
Follows on #8355 with unit tests.
This PR depends on https://github.com/CocoaPods/Xcodeproj/pull/739

Fix project path handling issue causing bad cmake generated projects

---

CHANGELOG.md
lib/cocoapods/command/lib/lint.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb
spec/unit/validator_spec.rb

Option to lint a specified set of test_specs

---

Gemfile
Gemfile.lock
cocoapods.gemspec
examples/Modules Example/Podfile
examples/MultiXcodeProject Example/Podfile
lib/cocoapods/installer.rb
spec/unit/installer_spec.rb

Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/278

Remove cocoapods-stats as a default plugin

---

CHANGELOG.md
lib/cocoapods/installer/xcode/target_validator.rb
spec/unit/installer/xcode/target_validator_spec.rb

Fix crash when targets missing in Podfile

---

CHANGELOG.md
lib/cocoapods/command/lib/lint.rb
lib/cocoapods/command/spec/lint.rb
lib/cocoapods/validator.rb
spec/functional/command/lib/list_spec.rb
spec/functional/command/spec_spec.rb

add a `--configuration` option to `pod lint`.

---

lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

Fix app spec framework paths

---

lib/cocoapods/installer.rb
lib/cocoapods/installer/pod_source_installer.rb

* Only clean pod sources if new pods have been installed
* Lock pod sources only if they have been previously unlocked

Performance improvements for incremental install

---

CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

Ensure that the non-compilable resource skipping in static frameworks happens only for the pod itself

---

.github/workflows/Specs.yml

Following @endocrimes' recommendation.

Make CI job name more verbose

---

README.md

* Replace old Travis badge with GH Actions badge
* Fix the gem version shield to use HTTPS

Fix badges in the README

---

Gemfile.lock
cocoapods.gemspec
lib/cocoapods/installer/xcode/pods_project_generator/app_host_installer.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb

integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/303

Bump minimum version of Xcodeproj to 1.19.0

---

CHANGELOG.md
lib/cocoapods/downloader/cache.rb
spec/unit/downloader/cache_spec.rb

this fix 1.0.1 cached as 1.0
see #10228

fix: ensure cached spec path uniq

---

lib/cocoapods/installer/podfile_validator.rb

Fix typo in comment

---

.github/workflows/Lint.yml
.github/workflows/Specs.yml

@dnkoutso I think Ruby compatibility is what's been causing those weird CI fails in #10320. Rebase on it and check?

Shard GH Action cache key by Ruby version

---

Gemfile
Gemfile.lock

It looks like we no longer need that fork, trying to remove it

Remove forked json

---

.github/workflows/Lint.yml
.github/workflows/Specs.yml

* Fix cache keys for Linux builds
* Remove caching for macOS builds as the cached gems don't work on subsequent builds

Fix cache keys to reflect OS version

---

.github/workflows/Lint.yml
.github/workflows/Specs.yml

Using suggestion from https://github.com/actions/virtual-environments/issues/2489#issuecomment-763785078

Use build image version var in cache keys

---

.rubocop_cocoapods.yml
.rubocop_todo.yml
spec/unit/installer/analyzer_spec.rb

Also opened https://github.com/CocoaPods/shared/pull/12.
This PR unblocks https://github.com/CocoaPods/CocoaPods/pull/10238 and https://github.com/CocoaPods/CocoaPods/pull/10477.

disable `Metrics/BlockLength`

---

.github/workflows/Lint.yml
.github/workflows/Specs.yml
CHANGELOG.md
Gemfile.lock
cocoapods.gemspec

* Update minimum Ruby >= 2.6
* Remove older Ruby from CI matrix
* Bundler update (CI only)

Update minimum Ruby to >= 2.6

---

CHANGELOG.md
lib/cocoapods/external_sources/podspec_source.rb

Use `OpenURI.open_uri` instead

---

.rubocop_todo.yml
CHANGELOG.md
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb

For https://github.com/CocoaPods/CocoaPods/issues/10235
Core PR: https://github.com/CocoaPods/Core/pull/664

Added possibility to skip modulemap generation

---

CHANGELOG.md
Gemfile.lock
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb

requires https://github.com/CocoaPods/Core/pull/686
closes https://github.com/CocoaPods/CocoaPods/issues/10770

Add support for `before_headers` and `after_headers` script phase DSL.

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
spec/unit/installer/analyzer_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/10777

Correctly filter dependencies for pod variants across different platforms.

---

CHANGELOG.md
Gemfile.lock
cocoapods.gemspec

closes https://github.com/CocoaPods/CocoaPods/issues/10802

Bump addressable dependency to 2.8.

---

CHANGELOG.md
lib/cocoapods/generator/script_phase_constants.rb

closes #10488 
supersedes https://github.com/CocoaPods/CocoaPods/pull/10752

Fix touch on a missing directory for dSYM copy phase script.

---

Gemfile.lock

integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/318

Update Xcodeproj gem

---

CHANGELOG.md
lib/cocoapods/installer/analyzer.rb
lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
spec/unit/installer/analyzer/sandbox_analyzer_spec.rb

`pod install`  cannot update pod in Pods folder when changing the pod from branch to version in Podfie.
change pod in Podfile like this:
```ruby
pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :branch => 'master'
```
push some code changes to the master branch (`commit A`), but make sure the version number is `4.0.1`, and then execute `pod install`
change the pod from branch to version in Podfile like this:
```ruby
pod 'AFNetworking', '4.0.1'
```
because the pod version number has not been changed, command `pod install`  cannot update pod in Pods folder, still contains the `commit A` changes.

Update pod in Pods folder when changing the pod from branch to version in Podfie

---

CHANGELOG.md
lib/cocoapods/generator/copy_xcframework_script.rb
lib/cocoapods/generator/embed_frameworks_script.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
lib/cocoapods/sandbox/file_accessor.rb
lib/cocoapods/target/build_settings.rb
lib/cocoapods/target/pod_target.rb
lib/cocoapods/xcode/xcframework.rb
spec/unit/generator/copy_xcframeworks_script_spec.rb
spec/unit/generator/embed_frameworks_script_spec.rb
spec/unit/installer/user_project_integrator/target_integrator_spec.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb
spec/unit/target/aggregate_target_spec.rb
spec/unit/target/build_settings/aggregate_target_settings_spec.rb
spec/unit/xcode/xcframework_spec.rb

closes https://github.com/CocoaPods/CocoaPods/issues/10106
integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/319
Verified project https://github.com/CocoaPods/CocoaPods/issues/10106 successfully compiled now.

Place frameworks from xcframeworks into a unique folder name to avoid duplicate outputs.

---

CHANGELOG.md
lib/cocoapods/generator/copy_xcframework_script.rb

supersedes https://github.com/CocoaPods/CocoaPods/pull/10130
integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/321

Remove unused `install_xcframework_library` code.

---

CHANGELOG.md
lib/cocoapods/installer/user_project_integrator/target_integrator.rb
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb
spec/unit/installer/xcode/pods_project_generator/pod_target_integrator_spec.rb

closes #10652 
integration specs https://github.com/CocoaPods/cocoapods-integration-specs/pull/320

Fix adding embed frameworks script phase to unit test targets if xcframeworks are present.

---

lib/cocoapods/installer.rb
spec/unit/installer_spec.rb

Follow up on https://github.com/CocoaPods/CocoaPods/pull/11213
This ensures deleted pods and changed pods are cleaned up from the sandbox even if project generation is skipped.
Integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/330

Always clean sandbox for changed pods

---

.github/workflows/Specs.yml
Gemfile.lock

Bump integration specs for Xcode 13, build examples with Xcode 13, bump Xcodeproj gem.

---

Gemfile
Gemfile.lock

This updates the gem `kramdown` to 2.3.x which resolves a high vulnerability issue in this repo.

Try updating Danger to 8.x

---

cocoapods.gemspec

Fixes CocoaPods/CocoaPods#11040

Update cocoapods-trunk gem minimum version requirement.

---

.github/workflows/Specs.yml
Gemfile
Gemfile.lock
lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb

closes https://github.com/CocoaPods/CocoaPods/issues/11402
integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/338

Build samples with Xcode 14.2, fix resource bundle code signing issue

---

lib/cocoapods/validator.rb
lib/cocoapods/xcode/xcframework/xcframework_slice.rb

It might need to put some warnings to mention people that .dylib app will be rejected by App Store, only for special use cases.

Support .dylib for special use cases

---

CHANGELOG.md
lib/cocoapods/generator/app_target_helper.rb
spec/unit/generator/app_target_helper_spec.rb

Xcode 14.3 fix: pod lib lint warning generation from main.m.

---

bin/sandbox-pod

chore: fix typo in bin/sandbox-pod

---

.github/ISSUE_TEMPLATE.md

Update ISSUE_TEMPLATE to set expectations about a lack of response

---

CHANGELOG.md
lib/cocoapods/validator.rb

Fixes https://github.com/CocoaPods/CocoaPods/issues/12664

Fix validation failure from new xcodeproj settings

---

.github/workflows/Specs.yml

This isn't working and is failing on master

Remove coverage
